---
title: "Clustering"
author: "Jackson Pullman"
date: "2022-12-24"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Clustering
library(ggplotify)
#Imports Rand Index
library(mclust)
#citation("mclust")
#Get observed metric

set.seed(1)
E(strain_rate_vil_graph_1)$weight[is.na(E(strain_rate_vil_graph_1)$weight)] <- 0
E(strain_rate_vil_graph_2)$weight[is.na(E(strain_rate_vil_graph_2)$weight)] <- 0
E(strain_rate_vil_graph_3)$weight[is.na(E(strain_rate_vil_graph_3)$weight)] <- 0
E(strain_rate_vil_graph_4)$weight[is.na(E(strain_rate_vil_graph_4)$weight)] <- 0
E(strain_rate_vil_graph_5)$weight[is.na(E(strain_rate_vil_graph_5)$weight)] <- 0
E(strain_rate_vil_graph_6)$weight[is.na(E(strain_rate_vil_graph_6)$weight)] <- 0
E(strain_rate_vil_graph_7)$weight[is.na(E(strain_rate_vil_graph_7)$weight)] <- 0
E(strain_rate_vil_graph_8)$weight[is.na(E(strain_rate_vil_graph_8)$weight)] <- 0
E(strain_rate_vil_graph_9)$weight[is.na(E(strain_rate_vil_graph_9)$weight)] <- 0
E(strain_rate_vil_graph_10)$weight[is.na(E(strain_rate_vil_graph_10)$weight)] <- 0
E(strain_rate_vil_graph_11)$weight[is.na(E(strain_rate_vil_graph_11)$weight)] <- 0
E(strain_rate_vil_graph_12)$weight[is.na(E(strain_rate_vil_graph_12)$weight)] <- 0
E(strain_rate_vil_graph_13)$weight[is.na(E(strain_rate_vil_graph_13)$weight)] <- 0
E(strain_rate_vil_graph_14)$weight[is.na(E(strain_rate_vil_graph_14)$weight)] <- 0
E(strain_rate_vil_graph_15)$weight[is.na(E(strain_rate_vil_graph_15)$weight)] <- 0
E(strain_rate_vil_graph_16)$weight[is.na(E(strain_rate_vil_graph_16)$weight)] <- 0
E(strain_rate_vil_graph_17)$weight[is.na(E(strain_rate_vil_graph_17)$weight)] <- 0
E(strain_rate_vil_graph_18)$weight[is.na(E(strain_rate_vil_graph_18)$weight)] <- 0

for(i in 1:length(village_names)){
  assign(paste0("strain_rate_vil_graph_scram_", i), get(paste0("strain_rate_vil_graph_", i)))
}


strain_rate_cluster_1_leiden <- cluster_leiden(strain_rate_vil_graph_1, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_1))[2] / (gorder(strain_rate_vil_graph_1) - 1))
strain_rate_cluster_2_leiden <- cluster_leiden(strain_rate_vil_graph_2, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_2))[2] / (gorder(strain_rate_vil_graph_2) - 1))
strain_rate_cluster_3_leiden <- cluster_leiden(strain_rate_vil_graph_3, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_3))[2] / (gorder(strain_rate_vil_graph_3) - 1))
strain_rate_cluster_4_leiden <- cluster_leiden(strain_rate_vil_graph_4, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_4))[2] / (gorder(strain_rate_vil_graph_4) - 1))
strain_rate_cluster_5_leiden <- cluster_leiden(strain_rate_vil_graph_5, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_5))[2] / (gorder(strain_rate_vil_graph_5) - 1))
strain_rate_cluster_6_leiden <- cluster_leiden(strain_rate_vil_graph_6, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_6))[2] / (gorder(strain_rate_vil_graph_6) - 1))
strain_rate_cluster_7_leiden <- cluster_leiden(strain_rate_vil_graph_7, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_7))[2] / (gorder(strain_rate_vil_graph_7) - 1))
strain_rate_cluster_8_leiden <- cluster_leiden(strain_rate_vil_graph_8, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_8))[2] / (gorder(strain_rate_vil_graph_8) - 1))
strain_rate_cluster_9_leiden <- cluster_leiden(strain_rate_vil_graph_9, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_9))[2] / (gorder(strain_rate_vil_graph_9) - 1))
strain_rate_cluster_10_leiden <- cluster_leiden(strain_rate_vil_graph_10, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_10))[2] / (gorder(strain_rate_vil_graph_10) - 1))
strain_rate_cluster_11_leiden <- cluster_leiden(strain_rate_vil_graph_11, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_11))[2] / (gorder(strain_rate_vil_graph_11) - 1))
strain_rate_cluster_12_leiden <- cluster_leiden(strain_rate_vil_graph_12, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_12))[2] / (gorder(strain_rate_vil_graph_12) - 1))
strain_rate_cluster_13_leiden <- cluster_leiden(strain_rate_vil_graph_13, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_13))[2] / (gorder(strain_rate_vil_graph_13) - 1))
strain_rate_cluster_14_leiden <- cluster_leiden(strain_rate_vil_graph_14, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_14))[2] / (gorder(strain_rate_vil_graph_14) - 1))
strain_rate_cluster_15_leiden <- cluster_leiden(strain_rate_vil_graph_15, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_15))[2] / (gorder(strain_rate_vil_graph_15) - 1))
strain_rate_cluster_16_leiden <- cluster_leiden(strain_rate_vil_graph_16, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_16))[2] / (gorder(strain_rate_vil_graph_16) - 1))
strain_rate_cluster_17_leiden <- cluster_leiden(strain_rate_vil_graph_17, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_17))[2] / (gorder(strain_rate_vil_graph_17) - 1))
strain_rate_cluster_18_leiden <- cluster_leiden(strain_rate_vil_graph_18, objective_function = 'modularity') #r = quantile(strength(strain_rate_vil_graph_18))[2] / (gorder(strain_rate_vil_graph_18) - 1))

set.seed(1)
#Get social network clustering for each village
sn_cluster_1_leiden <- cluster_leiden(sn_vil_graph_1, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_1))[2] / (gorder(sn_vil_graph_1) - 1))
sn_cluster_2_leiden <- cluster_leiden(sn_vil_graph_2, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_2))[2] / (gorder(sn_vil_graph_2) - 1))
sn_cluster_3_leiden <- cluster_leiden(sn_vil_graph_3, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_3))[2] / (gorder(sn_vil_graph_3) - 1))
sn_cluster_4_leiden <- cluster_leiden(sn_vil_graph_4, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_4))[2] / (gorder(sn_vil_graph_4) - 1))
sn_cluster_5_leiden <- cluster_leiden(sn_vil_graph_5, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_5))[2] / (gorder(sn_vil_graph_5) - 1))
sn_cluster_6_leiden <- cluster_leiden(sn_vil_graph_6, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_6))[2] / (gorder(sn_vil_graph_6) - 1))
sn_cluster_7_leiden <- cluster_leiden(sn_vil_graph_7, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_7))[2] / (gorder(sn_vil_graph_7) - 1))
sn_cluster_8_leiden <- cluster_leiden(sn_vil_graph_8, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_8))[2] / (gorder(sn_vil_graph_8) - 1))
sn_cluster_9_leiden <- cluster_leiden(sn_vil_graph_9, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_9))[2] / (gorder(sn_vil_graph_9) - 1))
sn_cluster_10_leiden <- cluster_leiden(sn_vil_graph_10, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_10))[2] / (gorder(sn_vil_graph_10) - 1))
sn_cluster_11_leiden <- cluster_leiden(sn_vil_graph_11, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_11))[2] / (gorder(sn_vil_graph_11) - 1))
sn_cluster_12_leiden <- cluster_leiden(sn_vil_graph_12, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_12))[2] / (gorder(sn_vil_graph_12) - 1))
sn_cluster_13_leiden <- cluster_leiden(sn_vil_graph_13, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_13))[2] / (gorder(sn_vil_graph_13) - 1))
sn_cluster_14_leiden <- cluster_leiden(sn_vil_graph_14, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_14))[2] / (gorder(sn_vil_graph_14) - 1))
sn_cluster_15_leiden <- cluster_leiden(sn_vil_graph_15, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_15))[2] / (gorder(sn_vil_graph_15) - 1))
sn_cluster_16_leiden <- cluster_leiden(sn_vil_graph_16, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_16))[2] / (gorder(sn_vil_graph_16) - 1))
sn_cluster_17_leiden <- cluster_leiden(sn_vil_graph_17, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_17))[2] / (gorder(sn_vil_graph_17) - 1))
sn_cluster_18_leiden <- cluster_leiden(sn_vil_graph_18, objective_function = 'modularity') # r = quantile(strength(sn_vil_graph_18))[2] / (gorder(sn_vil_graph_18) - 1))


#Order names for both clusters
mbiome_member_1_leiden <- membership(strain_rate_cluster_1_leiden)[match(names(membership(sn_cluster_1_leiden)),
                                                           names(membership(strain_rate_cluster_1_leiden)))] +100
mbiome_member_2_leiden <- membership(strain_rate_cluster_2_leiden)[match(names(membership(sn_cluster_2_leiden)),
                                                           names(membership(strain_rate_cluster_2_leiden)))] +200
mbiome_member_3_leiden <- membership(strain_rate_cluster_3_leiden)[match(names(membership(sn_cluster_3_leiden)),
                                                           names(membership(strain_rate_cluster_3_leiden)))] +300
mbiome_member_4_leiden <- membership(strain_rate_cluster_4_leiden)[match(names(membership(sn_cluster_4_leiden)),
                                                           names(membership(strain_rate_cluster_4_leiden)))] +400
mbiome_member_5_leiden <- membership(strain_rate_cluster_5_leiden)[match(names(membership(sn_cluster_5_leiden)),
                                                           names(membership(strain_rate_cluster_5_leiden)))] +500
mbiome_member_6_leiden <- membership(strain_rate_cluster_6_leiden)[match(names(membership(sn_cluster_6_leiden)),
                                                           names(membership(strain_rate_cluster_6_leiden)))] +600
mbiome_member_7_leiden <- membership(strain_rate_cluster_7_leiden)[match(names(membership(sn_cluster_7_leiden)),
                                                           names(membership(strain_rate_cluster_7_leiden)))] +700
mbiome_member_8_leiden <- membership(strain_rate_cluster_8_leiden)[match(names(membership(sn_cluster_8_leiden)),
                                                           names(membership(strain_rate_cluster_8_leiden)))] +800
mbiome_member_9_leiden <- membership(strain_rate_cluster_9_leiden)[match(names(membership(sn_cluster_9_leiden)),
                                                           names(membership(strain_rate_cluster_9_leiden)))] +900
mbiome_member_10_leiden <- membership(strain_rate_cluster_10_leiden)[match(names(membership(sn_cluster_10_leiden)),
                                                           names(membership(strain_rate_cluster_10_leiden)))] +1000
mbiome_member_11_leiden <- membership(strain_rate_cluster_11_leiden)[match(names(membership(sn_cluster_11_leiden)),
                                                           names(membership(strain_rate_cluster_11_leiden)))] +1100
mbiome_member_12_leiden <- membership(strain_rate_cluster_12_leiden)[match(names(membership(sn_cluster_12_leiden)),
                                                           names(membership(strain_rate_cluster_12_leiden)))] +1200
mbiome_member_13_leiden <- membership(strain_rate_cluster_13_leiden)[match(names(membership(sn_cluster_13_leiden)),
                                                           names(membership(strain_rate_cluster_13_leiden)))] +1300
mbiome_member_14_leiden <- membership(strain_rate_cluster_14_leiden)[match(names(membership(sn_cluster_14_leiden)),
                                                           names(membership(strain_rate_cluster_14_leiden)))] +1400
mbiome_member_15_leiden <- membership(strain_rate_cluster_15_leiden)[match(names(membership(sn_cluster_15_leiden)),
                                                           names(membership(strain_rate_cluster_15_leiden)))] +1500
mbiome_member_16_leiden <- membership(strain_rate_cluster_16_leiden)[match(names(membership(sn_cluster_16_leiden)),
                                                           names(membership(strain_rate_cluster_16_leiden)))] +1600
mbiome_member_17_leiden <- membership(strain_rate_cluster_17_leiden)[match(names(membership(sn_cluster_17_leiden)),
                                                           names(membership(strain_rate_cluster_17_leiden)))] +1700
mbiome_member_18_leiden <- membership(strain_rate_cluster_18_leiden)[match(names(membership(sn_cluster_18_leiden)),
                                                           names(membership(strain_rate_cluster_18_leiden)))] +1800


#Create social network membership vectors, shifted by village
sn_member_1_leiden <- membership(sn_cluster_1) + 100
sn_member_2_leiden <- membership(sn_cluster_2) + 200
sn_member_3_leiden <- membership(sn_cluster_3) + 300
sn_member_4_leiden <- membership(sn_cluster_4) + 400
sn_member_5_leiden <- membership(sn_cluster_5) + 500
sn_member_6_leiden <- membership(sn_cluster_6) + 600
sn_member_7_leiden <- membership(sn_cluster_7) + 700
sn_member_8_leiden <- membership(sn_cluster_8) + 800
sn_member_9_leiden <- membership(sn_cluster_9) + 900
sn_member_10_leiden <- membership(sn_cluster_10) + 1000
sn_member_11_leiden <- membership(sn_cluster_11) + 1100
sn_member_12_leiden <- membership(sn_cluster_12) + 1200
sn_member_13_leiden <- membership(sn_cluster_13) + 1300
sn_member_14_leiden <- membership(sn_cluster_14) + 1400
sn_member_15_leiden <- membership(sn_cluster_15) + 1500
sn_member_16_leiden <- membership(sn_cluster_16) + 1600
sn_member_17_leiden <- membership(sn_cluster_17) + 1700
sn_member_18_leiden <- membership(sn_cluster_18) + 1800


#Get rand index across all villages
all_mbiome_membership_leiden <-c(mbiome_member_1_leiden,
                          mbiome_member_2_leiden,
                          mbiome_member_3_leiden,
                          mbiome_member_4_leiden,
                          mbiome_member_5_leiden,
                          mbiome_member_6_leiden,
                          mbiome_member_7_leiden,
                          mbiome_member_8_leiden,
                          mbiome_member_9_leiden,
                          mbiome_member_10_leiden,
                          mbiome_member_11_leiden,
                          mbiome_member_12_leiden,
                          mbiome_member_13_leiden,
                          mbiome_member_14_leiden,
                          mbiome_member_15_leiden,
                          mbiome_member_16_leiden,
                          mbiome_member_17_leiden,
                          mbiome_member_18_leiden)

all_sn_membership_leiden <- c(sn_member_1_leiden,
                       sn_member_2_leiden,
                       sn_member_3_leiden,
                       sn_member_4_leiden,
                       sn_member_5_leiden,
                       sn_member_6_leiden,
                       sn_member_7_leiden,
                       sn_member_8_leiden,
                       sn_member_9_leiden,
                       sn_member_10_leiden,
                       sn_member_11_leiden,
                       sn_member_12_leiden,
                       sn_member_13_leiden,
                       sn_member_14_leiden,
                       sn_member_15_leiden,
                       sn_member_16_leiden,
                       sn_member_17_leiden,
                       sn_member_18_leiden)
```

#Get Statistics on clustering
```{r}
all_sn_membership_df_leiden <- data.frame(name = names(all_sn_membership_leiden),
                                   cluster = unname(all_sn_membership_leiden))

all_mbiome_membership_df_leiden <- data.frame(name = names(all_mbiome_membership_leiden),
                                   cluster = unname(all_mbiome_membership_leiden))
```

#Average number of people in social network clusters
```{r}
all_sn_membership_df_leiden %>%
  group_by(cluster) %>%
  summarize(n = n()) %>%
  summarise(mean(n), median(n), sd(n))
```
#Average number of people in strain-sharing network clusters
```{r}
all_mbiome_membership_df_leiden %>%
  group_by(cluster) %>%
  summarize(n = n()) %>%
  summarise(mean(n), median(n), sd(n))
```
```{r}
all_mbiome_membership_df_leiden %>%
  group_by(cluster) %>%
  summarize(n = n()) %>%
  arrange(n)
```

#Average strain-sharing rate within cluster
```{r}
uniq_clusters_leiden <- unique(all_mbiome_membership_df_leiden$cluster)
cluster_sharing_all_leiden <- c()
for(i in 1:length(uniq_clusters_leiden)){
  cluster_names <- all_mbiome_membership_df_leiden %>% filter(cluster == uniq_clusters_leiden[i]) %>% pull(name)
  cluster_sharing <- strain_rate[rownames(strain_rate) %in% cluster_names,
                                 colnames(strain_rate) %in% cluster_names]
  cluster_sharing[lower.tri(cluster_sharing, diag = TRUE)] <- NA
  #cluster_sharing_all <- c(cluster_sharing_all,
   #                        na.omit(unlist(as.list(cluster_sharing))))
  cluster_sharing_all_leiden <- c(cluster_sharing_all_leiden,
                           mean(unlist(as.list(cluster_sharing)), na.rm = TRUE))
  
}
median(cluster_sharing_all_leiden, na.rm = TRUE)
```

#Average number of ties
```{r}
uniq_clusters_leiden <- unique(all_sn_membership_df_leiden$cluster)
cluster_ties_all_leiden <- c()

SN_Graph_all <- as_adjacency_matrix(simplify(graph_from_data_frame(SN, directed = FALSE)))

for(i in 1:length(uniq_clusters_leiden)){
  cluster_names <- all_sn_membership_df_leiden %>% filter(cluster == uniq_clusters_leiden[i]) %>% pull(name)
  cluster_count <- SN_Graph_all[rownames(SN_Graph_all) %in% cluster_names,
                                 colnames(SN_Graph_all) %in% cluster_names]
  cluster_count[lower.tri(cluster_count, diag = TRUE)] <- NA
  #cluster_sharing_all <- c(cluster_sharing_all,
   #                        na.omit(unlist(as.list(cluster_sharing))))
  cluster_ties_all_leiden <- c(cluster_ties_all_leiden,
                           sum(unlist(as.list(cluster_count)), na.rm = TRUE))
  
}
mean(cluster_ties_all_leiden)
```

```{r}
rand_stat_strain_rate_leiden <- mclust::adjustedRandIndex(all_mbiome_membership_leiden, all_sn_membership_leiden)
#rand_stat_strain <- adjustedRandIndex(all_mbiome_membership_strain, all_sn_membership)

null_rands_strain_rate_leiden <- numeric(10000)
#null_rands_strain <- numeric(1000)

#Create null distribution metrics
cl <- parallel::makeCluster(10)
doParallel::registerDoParallel(cl)
foreach(i= c(1:10000), .combine=rbind, .packages = c('igraph') ) %dopar% {
  #Scramble microbiome
  strain_rate_vil_graph_scram_1 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_1, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_1, "name")))
  strain_rate_vil_graph_scram_2 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_2, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_2, "name")))
  strain_rate_vil_graph_scram_3 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_3, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_3, "name")))
  strain_rate_vil_graph_scram_4 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_4, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_4, "name")))
  strain_rate_vil_graph_scram_5 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_5, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_5, "name")))
  strain_rate_vil_graph_scram_6 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_6, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_6, "name")))
  strain_rate_vil_graph_scram_7 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_7, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_7, "name")))
  strain_rate_vil_graph_scram_8 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_8, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_8, "name")))
  strain_rate_vil_graph_scram_9 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_9, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_9, "name")))
  strain_rate_vil_graph_scram_10 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_10, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_10, "name")))
  strain_rate_vil_graph_scram_11 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_11, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_11, "name")))
  strain_rate_vil_graph_scram_12 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_12, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_12, "name")))
  strain_rate_vil_graph_scram_13 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_13, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_13, "name")))
  strain_rate_vil_graph_scram_14 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_14, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_14, "name")))
  strain_rate_vil_graph_scram_15 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_15, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_15, "name")))
  strain_rate_vil_graph_scram_16 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_16, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_16, "name")))
  strain_rate_vil_graph_scram_17 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_17, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_17, "name")))
  strain_rate_vil_graph_scram_18 <- igraph::set.vertex.attribute(strain_rate_vil_graph_scram_18, "name",
                                                        value = sample(vertex_attr(strain_rate_vil_graph_scram_18, "name")))
  

  #Get scrambled microbiome membership
  
  strain_rate_cluster_1_scram <- cluster_leiden(strain_rate_vil_graph_scram_1, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_1))[2] / (gorder(strain_rate_vil_graph_scram_1) - 1))
  strain_rate_cluster_2_scram <- cluster_leiden(strain_rate_vil_graph_scram_2, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_2))[2] / (gorder(strain_rate_vil_graph_scram_2) - 1))
  strain_rate_cluster_3_scram <- cluster_leiden(strain_rate_vil_graph_scram_3, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_3))[2] / (gorder(strain_rate_vil_graph_scram_3) - 1))
  strain_rate_cluster_4_scram <- cluster_leiden(strain_rate_vil_graph_scram_4, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_4))[2] / (gorder(strain_rate_vil_graph_scram_4) - 1))
  strain_rate_cluster_5_scram <- cluster_leiden(strain_rate_vil_graph_scram_5, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_5))[2] / (gorder(strain_rate_vil_graph_scram_5) - 1))
  strain_rate_cluster_6_scram <- cluster_leiden(strain_rate_vil_graph_scram_6, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_6))[2] / (gorder(strain_rate_vil_graph_scram_6) - 1))
  strain_rate_cluster_7_scram <- cluster_leiden(strain_rate_vil_graph_scram_7, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_7))[2] / (gorder(strain_rate_vil_graph_scram_7) - 1))
  strain_rate_cluster_8_scram <- cluster_leiden(strain_rate_vil_graph_scram_8, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_8))[2] / (gorder(strain_rate_vil_graph_scram_8) - 1))
  strain_rate_cluster_9_scram <- cluster_leiden(strain_rate_vil_graph_scram_9, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_9))[2] / (gorder(strain_rate_vil_graph_scram_9) - 1))
  strain_rate_cluster_10_scram <- cluster_leiden(strain_rate_vil_graph_scram_10, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_10))[2] / (gorder(strain_rate_vil_graph_scram_10) - 1))
  strain_rate_cluster_11_scram <- cluster_leiden(strain_rate_vil_graph_scram_11, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_11))[2] / (gorder(strain_rate_vil_graph_scram_11) - 1))
  strain_rate_cluster_12_scram <- cluster_leiden(strain_rate_vil_graph_scram_12, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_12))[2] / (gorder(strain_rate_vil_graph_scram_12) - 1))
  strain_rate_cluster_13_scram <- cluster_leiden(strain_rate_vil_graph_scram_13, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_13))[2] / (gorder(strain_rate_vil_graph_scram_13) - 1))
  strain_rate_cluster_14_scram <- cluster_leiden(strain_rate_vil_graph_scram_14, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_14))[2] / (gorder(strain_rate_vil_graph_scram_14) - 1))
  strain_rate_cluster_15_scram <- cluster_leiden(strain_rate_vil_graph_scram_15, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_15))[2] / (gorder(strain_rate_vil_graph_scram_15) - 1))
  strain_rate_cluster_16_scram <- cluster_leiden(strain_rate_vil_graph_scram_16, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_16))[2] / (gorder(strain_rate_vil_graph_scram_16) - 1))
  strain_rate_cluster_17_scram <- cluster_leiden(strain_rate_vil_graph_scram_17, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_17))[2] / (gorder(strain_rate_vil_graph_scram_17) - 1))
  strain_rate_cluster_18_scram <- cluster_leiden(strain_rate_vil_graph_scram_18, objective_function = 'modularity') #, r = quantile(strength(strain_rate_vil_graph_scram_18))[2] / (gorder(strain_rate_vil_graph_scram_18) - 1))

  
  #Order scrambled microbiome membership and make separate by villages
  mbiome_member_1_scram <- membership(strain_rate_cluster_1_scram)[match(names(membership(sn_cluster_1)),
                                                             names(membership(strain_rate_cluster_1_scram)))] + 100
  mbiome_member_2_scram <- membership(strain_rate_cluster_2_scram)[match(names(membership(sn_cluster_2)),
                                                             names(membership(strain_rate_cluster_2_scram)))] + 200
  mbiome_member_3_scram <- membership(strain_rate_cluster_3_scram)[match(names(membership(sn_cluster_3)),
                                                             names(membership(strain_rate_cluster_3_scram)))] + 300
  mbiome_member_4_scram <- membership(strain_rate_cluster_4_scram)[match(names(membership(sn_cluster_4)),
                                                             names(membership(strain_rate_cluster_4_scram)))] + 400
  mbiome_member_5_scram <- membership(strain_rate_cluster_5_scram)[match(names(membership(sn_cluster_5)),
                                                             names(membership(strain_rate_cluster_5_scram)))] + 500
  mbiome_member_6_scram <- membership(strain_rate_cluster_6_scram)[match(names(membership(sn_cluster_6)),
                                                             names(membership(strain_rate_cluster_6_scram)))] + 600
  mbiome_member_7_scram <- membership(strain_rate_cluster_7_scram)[match(names(membership(sn_cluster_7)),
                                                             names(membership(strain_rate_cluster_7_scram)))] + 700
  mbiome_member_8_scram <- membership(strain_rate_cluster_8_scram)[match(names(membership(sn_cluster_8)),
                                                             names(membership(strain_rate_cluster_8_scram)))] + 800
  mbiome_member_9_scram <- membership(strain_rate_cluster_9_scram)[match(names(membership(sn_cluster_9)),
                                                             names(membership(strain_rate_cluster_9_scram)))] + 900
  mbiome_member_10_scram <- membership(strain_rate_cluster_10_scram)[match(names(membership(sn_cluster_10)),
                                                             names(membership(strain_rate_cluster_10_scram)))] + 1000
  mbiome_member_11_scram <- membership(strain_rate_cluster_11_scram)[match(names(membership(sn_cluster_11)),
                                                             names(membership(strain_rate_cluster_11_scram)))] + 1100
  mbiome_member_12_scram <- membership(strain_rate_cluster_12_scram)[match(names(membership(sn_cluster_12)),
                                                             names(membership(strain_rate_cluster_12_scram)))] + 1200
  mbiome_member_13_scram <- membership(strain_rate_cluster_13_scram)[match(names(membership(sn_cluster_13)),
                                                             names(membership(strain_rate_cluster_13_scram)))] + 1300
  mbiome_member_14_scram <- membership(strain_rate_cluster_14_scram)[match(names(membership(sn_cluster_14)),
                                                             names(membership(strain_rate_cluster_14_scram)))] + 1400
  mbiome_member_15_scram <- membership(strain_rate_cluster_15_scram)[match(names(membership(sn_cluster_15)),
                                                             names(membership(strain_rate_cluster_15_scram)))] + 1500
  mbiome_member_16_scram <- membership(strain_rate_cluster_16_scram)[match(names(membership(sn_cluster_16)),
                                                             names(membership(strain_rate_cluster_16_scram)))] + 1600
  mbiome_member_17_scram <- membership(strain_rate_cluster_17_scram)[match(names(membership(sn_cluster_17)),
                                                             names(membership(strain_rate_cluster_17_scram)))] + 1700
  mbiome_member_18_scram <- membership(strain_rate_cluster_18_scram)[match(names(membership(sn_cluster_18)),
                                                             names(membership(strain_rate_cluster_18_scram)))] + 1800

  #combine membership
  all_mbiome_membership_scram_leiden <-c(mbiome_member_1_scram,
                            mbiome_member_2_scram,
                            mbiome_member_3_scram,
                            mbiome_member_4_scram,
                            mbiome_member_5_scram,
                            mbiome_member_6_scram,
                            mbiome_member_7_scram,
                            mbiome_member_8_scram,
                            mbiome_member_9_scram,
                            mbiome_member_10_scram,
                            mbiome_member_11_scram,
                            mbiome_member_12_scram,
                            mbiome_member_13_scram,
                            mbiome_member_14_scram,
                            mbiome_member_15_scram,
                            mbiome_member_16_scram,
                            mbiome_member_17_scram,
                            mbiome_member_18_scram)
  
  # all_mbiome_membership_scram_strain <-c(mbiome_member_1_scram_strain,
  #                                 mbiome_member_2_scram_strain,
  #                                 mbiome_member_3_scram_strain,
  #                                 mbiome_member_4_scram_strain,
  #                                 mbiome_member_5_scram_strain,
  #                                 mbiome_member_6_scram_strain,
  #                                 mbiome_member_7_scram_strain,
  #                                 mbiome_member_8_scram_strain,
  #                                 mbiome_member_9_scram_strain)
  
  #Get null statistic
  null_rands_strain_rate_leiden[i] <- mclust::adjustedRandIndex(all_mbiome_membership_scram_leiden, all_sn_membership_leiden)
  
  data.frame(rand_inds = c(mclust::adjustedRandIndex(mbiome_member_1_scram, sn_member_1),
                                              mclust::adjustedRandIndex(mbiome_member_2_scram, sn_member_2),
                                              mclust::adjustedRandIndex(mbiome_member_3_scram, sn_member_3),
                                              mclust::adjustedRandIndex(mbiome_member_4_scram, sn_member_4),
                                              mclust::adjustedRandIndex(mbiome_member_5_scram, sn_member_5),
                                              mclust::adjustedRandIndex(mbiome_member_6_scram, sn_member_6),
                                              mclust::adjustedRandIndex(mbiome_member_7_scram, sn_member_7),
                                              mclust::adjustedRandIndex(mbiome_member_8_scram, sn_member_8),
                                              mclust::adjustedRandIndex(mbiome_member_9_scram, sn_member_9),
                                              mclust::adjustedRandIndex(mbiome_member_10_scram, sn_member_10),
                                              mclust::adjustedRandIndex(mbiome_member_11_scram, sn_member_11),
                                              mclust::adjustedRandIndex(mbiome_member_12_scram, sn_member_12),
                                              mclust::adjustedRandIndex(mbiome_member_13_scram, sn_member_13),
                                              mclust::adjustedRandIndex(mbiome_member_14_scram, sn_member_14),
                                              mclust::adjustedRandIndex(mbiome_member_15_scram, sn_member_15),
                                              mclust::adjustedRandIndex(mbiome_member_16_scram, sn_member_16),
                                              mclust::adjustedRandIndex(mbiome_member_17_scram, sn_member_17),
                                              mclust::adjustedRandIndex(mbiome_member_18_scram, sn_member_18)),
                                vils = village_names)
} -> null_clusters_leiden
parallel::stopCluster(cl)

null_clusters_leiden$vils <- village_map$village_name_deid[match(null_clusters_leiden$vils, village_map$village_code)]
```


```{r}
village_names_temp <- village_names
observed_leiden <- data.frame(
  vils = village_map$village_name_deid[match(village_names_temp, village_map$village_code)],
  obs = c(
    mclust::adjustedRandIndex(mbiome_member_1_leiden, sn_member_1_leiden),
    mclust::adjustedRandIndex(mbiome_member_2_leiden, sn_member_2_leiden),
    mclust::adjustedRandIndex(mbiome_member_3_leiden, sn_member_3_leiden),
    mclust::adjustedRandIndex(mbiome_member_4_leiden, sn_member_4_leiden),
    mclust::adjustedRandIndex(mbiome_member_5_leiden, sn_member_5_leiden),
    mclust::adjustedRandIndex(mbiome_member_6_leiden, sn_member_6_leiden),
    mclust::adjustedRandIndex(mbiome_member_7_leiden, sn_member_7_leiden),
    mclust::adjustedRandIndex(mbiome_member_8_leiden, sn_member_8_leiden),
    mclust::adjustedRandIndex(mbiome_member_9_leiden, sn_member_9_leiden),
    mclust::adjustedRandIndex(mbiome_member_10_leiden, sn_member_10_leiden),
    mclust::adjustedRandIndex(mbiome_member_11_leiden, sn_member_11_leiden),
    mclust::adjustedRandIndex(mbiome_member_12_leiden, sn_member_12_leiden),
    mclust::adjustedRandIndex(mbiome_member_13_leiden, sn_member_13_leiden),
    mclust::adjustedRandIndex(mbiome_member_14_leiden, sn_member_14_leiden),
    mclust::adjustedRandIndex(mbiome_member_15_leiden, sn_member_15_leiden),
    mclust::adjustedRandIndex(mbiome_member_16_leiden, sn_member_16_leiden),
    mclust::adjustedRandIndex(mbiome_member_17_leiden, sn_member_17_leiden),
    mclust::adjustedRandIndex(mbiome_member_18_leiden, sn_member_18_leiden)
  )
)

p_vals_leiden <- data.frame(
  vils = observed_leiden$vils,
  p_val = c(
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[1]] >= observed_leiden$obs[1]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[2]] >= observed_leiden$obs[2]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[3]] >= observed_leiden$obs[3]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[4]] >= observed_leiden$obs[4]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[5]] >= observed_leiden$obs[5]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[6]] >= observed_leiden$obs[6]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[7]] >= observed_leiden$obs[7]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[8]] >= observed_leiden$obs[8]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[9]] >= observed_leiden$obs[9]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[10]] >= observed_leiden$obs[10]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[11]] >= observed_leiden$obs[11]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[12]] >= observed_leiden$obs[12]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[13]] >= observed_leiden$obs[13]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[14]] >= observed_leiden$obs[14]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[15]] >= observed_leiden$obs[15]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[16]] >= observed_leiden$obs[16]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[17]] >= observed_leiden$obs[17]) /
      10000,
    sum(null_clusters_leiden$rand_inds[null_clusters_leiden$vils ==
                                  observed_leiden$vils[18]] >= observed_leiden$obs[18]) /
      10000
  )
)

for(i in 1:nrow(p_vals_leiden)){
  if(p_vals_leiden$p_val[i] == 0){
    p_vals_leiden$p_val[i] <- paste0("p <= .0001")
  }
  else{
    p_vals_leiden$p_val[i] <- paste0("p = ", p_vals_leiden$p_val[i])
  }
}



null_clusters_leiden$dummy = null_clusters_leiden$rand_inds

cluster_pvals_fig_leiden <- ggplot(null_clusters_leiden, aes(x=rand_inds ))+
  geom_histogram(color="black",fill="grey", bins = 100, show.legend = FALSE)+
  #facet_grid(as.factor(vils) ~ .) +
  facet_wrap(~ as.factor(vils), ncol=2) +
  geom_vline(data=observed_leiden,
             aes(xintercept=obs, color="red"),
             linetype="solid", show.legend = FALSE) +
  theme_pubr() +
  ylab("Frequency") +
  xlab("Adjusted Rand Index") +
  ggtitle("Permutation Null Distributions")+
  #scale_x_break(breaks = c(.3,.4), ticklabels=c(-.1,0,.05,.1,.15,.2,.25,.3,.4,.45)) +
  geom_text(data = p_vals_leiden, aes(label = p_val,
                               y = 2000,
                               x = .52)) +
  theme_pubr()+
  theme(
    axis.text.x.top = element_blank(),
    axis.ticks.x.top = element_blank(),
    strip.background = element_blank(),
    strip.text.x = element_text(size = 10),
    plot.title = element_text(hjust = .5, face = "bold"),
    axis.title  = element_text(face = "bold"),
    axis.text  = element_text(face = "bold")
  ) +
  coord_cartesian(ylim = c(0,4000)) +
  scale_y_continuous(limits = c(0, 4000), breaks = c(0, 2000, 4000))
#Plan el peroicso and mirasol and sesimel
```

Combine with clustering coef bucket fig from centralitysharing
```{r}
ggarrange(cluster_pvals_fig_leiden, cluster_bucket_fig, nrow = 1, labels = c("", "h"))
```



Village Plots
```{r}

add.alpha <- function(col, alpha = 1) {
  if (missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb) / 255, 2,
        function(x)
          rgb(x[1], x[2], x[3], alpha = alpha))
}


par(mar=c(0,0,0,0))
for(i in 1:length(village_names)){
  #i<- 1
  #SN_Village <- SN %>% filter(village_name_w3 == village_names[i])
  set.seed(1)
  #min(E(mbiome_all)$weight)
  #mbiome_all <- mbiome_all - E(mbiome_all)[E(mbiome_all)$weight ==0]
  SN_Village <- SN %>% filter(village_code_w3 == village_names[i])
  #Filter to relationships of interest
  #Get ids for that village
  village_ids <- unique(c(SN_Village$ego, SN_Village$alter))
  #mbiome_all <- get(paste0("strain_rate_vil_graph_",i))
  strain_vil <- strain_rate[rownames(strain_rate) %in% village_ids ,
                            colnames(strain_rate) %in% village_ids]
  #Create social network and microbiome networks
  sn_vil <- igraph::simplify(graph_from_data_frame(SN_Village, directed = FALSE))
  
  mbiome_all <- simplify(graph_from_adjacency_matrix(strain_vil,
                                                     mode = "undirected", weighted = TRUE))
  
  #Cluster
  #sum(is.na(E(mbiome_all)$weight))
  mbiome_all <- mbiome_all - E(mbiome_all)[is.na(E(mbiome_all)$weight)]
mbiome_cluster <-  cluster_leiden(mbiome_all, weights = E(mbiome_all)$weight, objective_function = 'modularity')
sn_cluster <- cluster_leiden(sn_vil, objective_function = 'modularity')
  
  max_cluster <- max(max(membership(mbiome_cluster)), max(membership(sn_cluster)))
  
  colors <- pals::cols25(max_cluster)
  colors <- add.alpha(colors, alpha = .5)

  mbiome_cols <- colors[membership(mbiome_cluster)]
  #Want colors here to best visually map to social network

  plot(mbiome_cluster,
       mbiome_all,
       col = mbiome_cols,
       #mark.groups = mbiome_cols,
       mark.col = colors,
       mark.border=colors,
       vertex.label = NA,
       vertex.size =5,
       edge.width=E(mbiome_all)$weight/50,
       edge.color = "black",
       layout = layout_with_fr,
       main = paste(village_names[i], "Strain Clusters")
  )
  # table(membership(sn_cluster))
  # table(membership(mbiome_cluster))
  # temp <- membership(mbiome_cluster)
  # swap <- c(temp)
  # swap <- case_when(
  #   swap == 1 ~ 5,
  #   swap == 5 ~ 2,
  #   swap == 3 ~ 6,
  #   swap == 2 ~ 1,
  #   swap == 4 ~ 3,
  #   TRUE ~ swap
  # )
  # names(swap) <- names(temp)


  
  V(sn_vil)$color <- colors[membership(sn_cluster)]
  set.seed(1)
  sn_colors <- colors[membership(sn_cluster)]
  plot(sn_vil,
       vertex.label = NA,
       vertex.size =5,
       mark.col = colors,
       mark.border=colors,
       col = sn_colors,
       edge.color = "black",
       layout = layout_with_fr,
      main = paste(village_names[i], "Social Network Clusters")
  )

  #Could Change these to match colors, hard would have to do manually
  #V(sn_vil)$color <- swap[match(V(sn_vil)$name, names(swap))]
  V(sn_vil)$color <- membership(mbiome_cluster)[match(V(sn_vil)$name, names(membership(mbiome_cluster)))]
  V(sn_vil)$color <- colors[as.numeric(V(sn_vil)$color)]
  set.seed(1)
  plot(sn_vil,
       vertex.label = NA,
       vertex.size =5,
       edge.color = "black",
       #vertex.color = new_cols,
       layout = layout_with_fr,
       main = paste(village_names[i], "Microbiome Clusters Overlay")
  )

  
  
}
```


Basauri Visualization
```{r}

add.alpha <- function(col, alpha = 1) {
  if (missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb) / 255, 2,
        function(x)
          rgb(x[1], x[2], x[3], alpha = alpha))
}

SN_Village <- SN %>% filter(village_code_w3 == 116)

village_ids <- unique(c(SN_Village$ego, SN_Village$alter))

strain_vil <-
  strain_rate[rownames(strain_rate) %in% village_ids ,
                  colnames(strain_rate) %in% village_ids]

#Create social network and microbiome networks
sn_vil <- igraph::simplify(graph_from_data_frame(SN_Village, directed = FALSE))

mbiome_all <- igraph::simplify(graph_from_adjacency_matrix(strain_vil, mode = "undirected", weighted = TRUE))

#Cluster
mbiome_cluster <- cluster_leiden(mbiome_all, objective_function = 'modularity')
sn_cluster <- cluster_leiden(sn_vil,objective_function = 'modularity')

max_cluster <-
  max(max(membership(mbiome_cluster)), max(membership(sn_cluster)))

colors <- pals::cols25(max_cluster)


temp <- membership(mbiome_cluster)
swap <- c(temp)
swap <- case_when(swap == 4 ~ 5,
                  swap == 3 ~ 2,
                  swap == 2 ~ 4,
                  swap == 1 ~ 3,
                  TRUE ~ swap)
names(swap) <- names(temp)


V(sn_vil)$color <- colors[membership(sn_cluster)]
sn_colors <- colors[membership(sn_cluster)]

set.seed(1)
mariposal_sn_leiden <- as.ggplot(expression(plot(#sn_cluster,
  sn_vil,
  vertex.label = NA,
  vertex.size = 5,
  mark.col = colors,
  mark.border = colors,
  col = sn_colors,
  edge.color = "black",
  layout = layout_with_fr,
  #main = "Social Network Clusters"
),
title("Social Network Clusters",line = 0)))

#Could Change these to match colors, hard would have to do manually
V(sn_vil)$color <- swap[match(V(sn_vil)$name, names(swap))]
V(sn_vil)$color <- colors[as.numeric(V(sn_vil)$color)]

set.seed(1)
mariposal_overlay_leiden <- as.ggplot(expression(plot(
  sn_vil,
  vertex.label = NA,
  vertex.size = 5,
  edge.color = "black",
  layout = layout_with_fr#,
  #main = "Microbiome Similarity Clusters\non Social Network"
),
title("Microbiome Similarity Clusters\non Social Network", line = -.75)))

colors <- add.alpha(colors, alpha = .5)
mbiome_cols <- colors[swap]
mbiome_cols_rect <- colors
mbiome_cols_rect <- mbiome_cols_rect[c(3,4,2,5)]
V(mbiome_all)$color <- mbiome_cols

mariposal_mbiome_leiden <- as.ggplot(expression(plot(
  mbiome_cluster,
  mbiome_all,
  col = mbiome_cols,
  mark.col = mbiome_cols_rect,
  mark.border = mbiome_cols_rect,
  vertex.label = NA,
  vertex.size = 5,
  edge.width = E(mbiome_all)$weight / 25,
  edge.color = "black",
  layout = layout_with_fr#,
  #main = "Microbiome Similarity Clusters"
),
title("Microbiome Similarity Clusters",line = 0)))
```

create_figure
```{r}
fig_13l <- ggarrange(mariposal_mbiome_leiden,mariposal_sn_leiden,mariposal_overlay_leiden,
                      labels = c("A", "B", "C"),
                      ncol = 1)

fig_13 <- ggarrange(fig_13l, 
                    ggarrange(cluster_pvals_fig_leiden, labels = 'D'),
                    widths = c(0.8,0.9)
)

svglite("Figures/sfigure13.svg", height = )
fig_13
dev.off()

png("Figures/sfigure13.png", )
fig_13
dev.off()
```


