---
title: "LinkPrediction"
author: "Jackson Pullman"
date: "2024-04-25"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pROC)
```

```{r}
#Change format of covariates to merge onto edge list
Covars_ego <- covariates %>% merge(household_wealth_data) %>%
  unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |> 
  rename(ego = respondent_master_id, ego_age = age_at_survey, ego_gender = gender,
         ego_household = building_id,
         ego_household_wealth = household_wealth_index_w3, ego_education = b0100, ego_indigenous = indigenous_status, 
         ego_religion = b0600, ego_length_in_village = b0800, ego_length_in_village_years = b0900,
         ego_bristol = mb_m0300,
         ego_DDS = DDS, ego_watersource = l0400,
         ego_med_painkillers = med_painkillers, 
         ego_med_antibiotics = med_antibiotics,  
         ego_med_antidiarrheal = med_antidiarrheal,  
         ego_med_antiparasite = med_antiparasite,  
         ego_med_vitamins = med_vitamins, 
         ego_med_zinc = med_zinc,  
         ego_med_antifungal = med_antifungal,  
         ego_med_antihypertensives = med_antihypertensives,  
         ego_med_antidiabetics = med_antidiabetics,  
         ego_med_antiacids = med_antiacids,  
         ego_med_laxatives = med_laxatives,
         ego_latitude = building_latitude, ego_longitude = building_longitude) %>%
  mutate(ego_education = dplyr::recode(ego_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         ego_indigenous = recode(ego_indigenous, "Lenca" = 1, "Ch'orti'/Maya Chorti" = 1, .default = 0),
         ego_bristol = as.numeric(ego_bristol)) %>% 
  dplyr::select(-c("village_name", "marital_name"))

Covars_alter <- covariates %>% merge(household_wealth_data) %>%
    unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |>
  rename(alter = respondent_master_id, alter_age = age_at_survey, alter_gender = gender,
         alter_household = building_id,
         alter_household_wealth = household_wealth_index_w3, alter_education = b0100, alter_indigenous = indigenous_status, 
         alter_religion = b0600, alter_length_in_village = b0800, alter_length_in_village_years = b0900,
         alter_bristol = mb_m0300,
         alter_DDS = DDS, alter_watersource = l0400, 
         alter_med_painkillers = med_painkillers,  
         alter_med_antibiotics = med_antibiotics,  
         alter_med_antidiarrheal = med_antidiarrheal,  
         alter_med_antiparasite = med_antiparasite,  
         alter_med_vitamins = med_vitamins, 
         alter_med_zinc = med_zinc,  
         alter_med_antifungal = med_antifungal,  
         alter_med_antihypertensives = med_antihypertensives,  
         alter_med_antidiabetics = med_antidiabetics,  
         alter_med_antiacids = med_antiacids,  
         alter_med_laxatives = med_laxatives,
         alter_latitude = building_latitude, alter_longitude = building_longitude) %>%
  mutate(alter_education = recode(alter_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         alter_indigenous = recode(alter_indigenous, "Lenca" = 1, "Ch'orti'/Maya Chorti" = 1, .default = 0),
         alter_bristol = as.numeric(alter_bristol)) %>% 
  dplyr::select(-c("village_name", "marital_name"))

#Merge covariate data onto edge list
SN_All_Covars <- merge(SN, Covars_ego, by = "ego")
SN_All_Covars <- merge(SN_All_Covars, Covars_alter, by = "alter")

#Get covariate matrix for people without a relationship
cl <- parallel::makeCluster(10)
doParallel::registerDoParallel(cl)
foreach(v = village_names, .combine = rbind) %dopar% {
  #Split up matrix into villages
  SN_Village <- SN_All_Covars[SN_All_Covars$village_code_w3 == v,]
  #IDs of everyone in village
  Village_IDs <- unique(c(as.character(SN_Village$ego), as.character(SN_Village$alter)))

  Village_Pairs <- unique(SN_Village$pair_key)
  
  Village_NoRels <- data.frame(matrix(NA,
                                      nrow = length(Village_IDs) * (length(Village_IDs)-1)/2 - length(Village_Pairs),
                                      ncol = 17))
  colnames(Village_NoRels) <- c("ego","alter","gender.mm","gender.ff", "gender.mf", "indigenous.both", "indigenous.one", "indigenous.none",
                                "religion.same", "age_difference_abs","average_age",
                                "wealth_difference_abs", "average_weatlh", "education_difference_abs",
                                "average_education", "village_code_w3", "household.same")
  
  k <- 1
  for(i in 1:length(Village_IDs)){
    j <- i+1
    while(j <=  length(Village_IDs)){
      pair <- paste((sort(stringr::str_split(paste0(Village_IDs[i], Village_IDs[j]),"")[[1]])),sep="", collapse="")
      if(!pair %in% Village_Pairs){
        p1 <- Covars_ego[Covars_ego$ego == Village_IDs[i],]
        p2 <- Covars_alter[Covars_alter$alter == Village_IDs[j],]
        Village_NoRels$ego[k] <- p1$ego
        Village_NoRels$alter[k] <- p2$alter
        Village_NoRels$gender.mm[k] <- p1$ego_gender == "man" & p2$alter_gender == "man"
        Village_NoRels$gender.mf[k] <-  p1$ego_gender == "man" & p2$alter_gender == "woman" | p1$ego_gender == "woman" & p2$alter_gender == "man"
        Village_NoRels$gender.ff[k] <- p1$ego_gender == "woman" & p2$alter_gender == "woman"
        Village_NoRels$indigenous.both[k] <- p1$ego_indigenous == 1 & p2$alter_indigenous == 1
        Village_NoRels$indigenous.one[k] <- 
          p1$ego_indigenous == 1 & p2$alter_indigenous == 0 | p1$ego_indigenous == 0 & p2$alter_indigenous == 1
        Village_NoRels$indigenous.none[k] <- p1$ego_indigenous == 0 & p2$alter_indigenous == 0
        Village_NoRels$religion.same[k] <- p1$ego_religion == p2$alter_religion
        Village_NoRels$age_difference_abs[k] <- abs(p1$ego_age - p2$alter_age)
        Village_NoRels$average_age[k] <- (p1$ego_age + p2$alter_age)/2
        Village_NoRels$wealth_difference_abs[k] <- abs(p1$ego_household_wealth - p2$alter_household_wealth)
        Village_NoRels$average_wealth[k] <- (p1$ego_household_wealth + p2$alter_household_wealth)/2
        Village_NoRels$education_difference_abs[k] <- abs(p1$ego_education - p2$alter_education)
        Village_NoRels$average_education[k] <- (p1$ego_education + p2$alter_education)/2
        Village_NoRels$village_code_w3[k] <- v
        Village_NoRels$household_same[k] <- p1$ego_household == p2$alter_household
        Village_NoRels$average_diet[k] <- (p1$ego_DDS == p2$alter_DDS) / 2
        Village_NoRels$different_diet[k] <- abs(p1$ego_DDS - p2$alter_DDS)
        Village_NoRels$average_bristol[k] <- (p1$ego_bristol == p2$alter_bristol) / 2
        Village_NoRels$different_bristol[k] <- abs(p1$ego_bristol - p2$alter_bristol)
        Village_NoRels$watersource_same[k] <- p1$ego_watersource == p2$alter_watersource
        Village_NoRels$same_usage_painkillers[k] <- p2$alter_med_painkillers == p1$ego_med_painkillers
        Village_NoRels$same_usage_antibiotics[k] <- p2$alter_med_antibiotics == p1$ego_med_antibiotics
        Village_NoRels$same_usage_antidiarrheal[k] <- p2$alter_med_antidiarrheal == p1$ego_med_antidiarrheal
        Village_NoRels$same_usage_antiparasite[k] <- p2$alter_med_antiparasite == p1$ego_med_antiparasite
        Village_NoRels$same_usage_vitamins[k] <- p2$alter_med_vitamins == p1$ego_med_vitamins
        Village_NoRels$same_usage_zinc[k] <- p2$alter_med_zinc == p1$ego_med_zinc
        Village_NoRels$same_usage_antifungal[k] <- p2$alter_med_antifungal == p1$ego_med_antifungal
        Village_NoRels$same_usage_antihypertensives[k] <- p2$alter_med_antihypertensives == p1$ego_med_antihypertensives
        Village_NoRels$same_usage_antidiabetics[k] <- p2$alter_med_antidiabetics == p1$ego_med_antidiabetics
        Village_NoRels$same_usage_antiacids[k] <- p2$alter_med_antiacids == p1$ego_med_antiacids
        Village_NoRels$same_usage_laxatives[k] <- p2$alter_med_laxatives == p1$ego_med_laxatives
        
        k <- k+1
      }
      j <- j+1
    }
  }
  #Check progress
  print(v)
  Village_NoRels
} -> All_NoRel_Covars     #Get covariated for people without relationship ties

parallel::stopCluster(cl)

#Set Un-nominated same village realtionship
All_NoRel_Covars$relationship <- "Un-Nominated Same Village"

#Attach strain sharing data to non-nominated relationships
for(i in 1:nrow(All_NoRel_Covars)){
  All_NoRel_Covars$strain_sharing_rate[i] <- strain_rate[rownames(strain_rate) == All_NoRel_Covars$ego[i],
                                                         colnames(strain_rate) == All_NoRel_Covars$alter[i]]
}

#Attach species similarity for non-nominated relationships
for(i in 1:nrow(All_NoRel_Covars)){
  All_NoRel_Covars$bray_curtis_sim[i] <- species_bray[rownames(species_bray) == All_NoRel_Covars$ego[i],
                                                         colnames(species_bray) == All_NoRel_Covars$alter[i]]
}

# for(i in 1:nrow(All_NoRel_Covars)){
#   All_NoRel_Covars$jaccard_sim[i] <- species_jaccard_sim[rownames(species_jaccard_sim) == All_NoRel_Covars$ego[i],
#                                                          colnames(species_jaccard_sim) == All_NoRel_Covars$alter[i]]
# }


#Get dataframe of all known relationships into format for regression
SN_All_Covars_for_Regression <- SN_All_Covars |> 
  distinct(pair_key, .keep_all = TRUE) |> 
  mutate(gender.mm = ego_gender == "man" & alter_gender == "man",
         gender.mf = ego_gender == "woman" & alter_gender == "man" | ego_gender == "man" & alter_gender == "woman",
         gender.ff = ego_gender == "woman" & alter_gender == "woman",
         indigenous.both = ego_indigenous == 1 & alter_indigenous == 1,
         indigenous.one = ego_indigenous == 1 & alter_indigenous == 0 | ego_indigenous == 0 & alter_indigenous == 1,
         indigenous.none = ego_indigenous == 0 & alter_indigenous == 0,
         religion.same = ego_religion == alter_religion,
         age_difference_abs = abs(ego_age - alter_age),
         average_age = (ego_age + alter_age)/2,
         wealth_difference_abs = abs(ego_household_wealth - alter_household_wealth),
         average_wealth = (ego_household_wealth + alter_household_wealth)/2,
         education_difference_abs = abs(ego_education - alter_education),
         average_education = (ego_education + alter_education)/2,
         household_same = ego_household == alter_household,
        average_diet = (ego_DDS == alter_DDS) / 2,
        different_diet = abs(ego_DDS - alter_DDS),
        average_bristol = (ego_bristol == alter_bristol) / 2,
        different_bristol = abs(ego_bristol - alter_bristol),
        watersource_same = ego_watersource == alter_watersource, 
        same_usage_painkillers = alter_med_painkillers == ego_med_painkillers,
        same_usage_antibiotics = alter_med_antibiotics == ego_med_antibiotics,
        same_usage_antidiarrheal = alter_med_antidiarrheal == ego_med_antidiarrheal,
        same_usage_antiparasite = alter_med_antiparasite == ego_med_antiparasite,
        same_usage_vitamins = alter_med_vitamins == ego_med_vitamins,
        same_usage_zinc = alter_med_zinc == ego_med_zinc,
        same_usage_antifungal = alter_med_antifungal == ego_med_antifungal,
        same_usage_antihypertensives = alter_med_antihypertensives == ego_med_antihypertensives,
        same_usage_antidiabetics = alter_med_antidiabetics == ego_med_antidiabetics,
        same_usage_antiacids = alter_med_antiacids == ego_med_antiacids,
        same_usage_laxatives = alter_med_laxatives == ego_med_laxatives
         )

#Make dataframe with only non-kin in different house
SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
  filter(!(pair_key %in% family_house_pairs))


#select predictors
SN_All_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
  mutate(related = 1) %>% 
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
         "age_difference_abs", "average_age", "wealth_difference_abs",
         "average_wealth", "education_difference_abs","average_education", "household_same",
         "average_diet","different_diet", "average_bristol","different_bristol", "watersource_same", starts_with('same_usage'),
         "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")

SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_Non_Kin_Dif_House_Covars_for_Regression %>%
  mutate(related = 1) %>% 
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
         "age_difference_abs", "average_age", "wealth_difference_abs",
         "average_wealth", "education_difference_abs","average_education","household_same",
         "average_diet","different_diet", "average_bristol","different_bristol", "watersource_same", starts_with('same_usage'),
         "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")


All_NoRel_Covars_for_Regression <- All_NoRel_Covars %>%
  mutate(related = 0) %>%
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
                "age_difference_abs", "average_age", "wealth_difference_abs",
                "average_wealth", "education_difference_abs","average_education","household_same",
                "average_diet","different_diet", "average_bristol","different_bristol", "watersource_same", starts_with('same_usage'),
                "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")


#Combine relationships and non relationship dataframe
SN_All_Covars_for_Regression_complete <- SN_All_Covars_for_Regression[complete.cases(SN_All_Covars_for_Regression),]

SN_Non_Kin_Dif_House_Covars_for_Regression_complete <- SN_Non_Kin_Dif_House_Covars_for_Regression[complete.cases(SN_Non_Kin_Dif_House_Covars_for_Regression),]

All_for_Regression <- rbind(All_NoRel_Covars_for_Regression, SN_All_Covars_for_Regression)

Non_Kin_House_for_Regression <- rbind(All_NoRel_Covars_for_Regression,
                                      SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

#May want to check if this is missing completely at random or input columns
#filter to complete cases
All_for_Regression_complete <- All_for_Regression[complete.cases(All_for_Regression),]

All_NoRel_Covars_for_Regression_complete <- All_NoRel_Covars_for_Regression[complete.cases(All_NoRel_Covars_for_Regression),]

Non_Kin_House_for_Regression_complete <-
  Non_Kin_House_for_Regression[complete.cases(Non_Kin_House_for_Regression),]

edge_counts <- SN_All_Covars_for_Regression_complete %>%
  group_by(village_code_w3) %>%
  summarize(edge_count = sum(related)) 

edge_counts <- edge_counts[match(village_names, edge_counts$village_code_w3),] %>%
  pull(edge_count)

edge_counts_nkh <- SN_Non_Kin_Dif_House_Covars_for_Regression_complete %>%
  group_by(village_code_w3) %>%
  summarize(edge_count = sum(related))

edge_counts_nkh <- edge_counts_nkh[match(village_names, edge_counts_nkh$village_code_w3),] %>%
  pull(edge_count)
```

Downsample
```{r}
#Downsample

Downsamp1 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[1]) %>% slice_sample(n = edge_counts[1])
Downsamp2 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[2]) %>% slice_sample(n = edge_counts[2])
Downsamp3 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[3]) %>% slice_sample(n = edge_counts[3])
Downsamp4 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[4]) %>% slice_sample(n = edge_counts[4])
Downsamp5 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[5]) %>% slice_sample(n = edge_counts[5])
Downsamp6 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[6]) %>% slice_sample(n = edge_counts[6])
Downsamp7 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[7]) %>% slice_sample(n = edge_counts[7])
Downsamp8 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[8]) %>% slice_sample(n = edge_counts[8])
Downsamp9 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[9]) %>% slice_sample(n = edge_counts[9])
Downsamp10 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[10]) %>% slice_sample(n = edge_counts[10])
Downsamp11 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[11]) %>% slice_sample(n = edge_counts[11])
Downsamp12 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[12]) %>% slice_sample(n = edge_counts[12])
Downsamp13 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[13]) %>% slice_sample(n = edge_counts[13])
Downsamp14 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[14]) %>% slice_sample(n = edge_counts[14])
Downsamp15 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[15]) %>% slice_sample(n = edge_counts[15])
Downsamp16 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[16]) %>% slice_sample(n = edge_counts[16])
Downsamp17 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[17]) %>% slice_sample(n = edge_counts[17])
Downsamp18 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[18]) %>% slice_sample(n = edge_counts[18])

Downsamp_all <- rbind(Downsamp1,Downsamp2,Downsamp3,Downsamp4,Downsamp5,
                      Downsamp6,Downsamp7,Downsamp8,Downsamp9,Downsamp10,Downsamp11,
                      Downsamp12,Downsamp13,Downsamp14,Downsamp15,
                      Downsamp16,Downsamp17,Downsamp18)

Downsamp_all <- rbind(Downsamp_all, SN_All_Covars_for_Regression_complete)

Downsamp_all <- Downsamp_all[complete.cases(Downsamp_all),]

#Non-kin different house

Downsamp1_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[1]) %>% slice_sample(n = edge_counts_nkh[1])
Downsamp2_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[2]) %>% slice_sample(n = edge_counts_nkh[2])
Downsamp3_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[3]) %>% slice_sample(n = edge_counts_nkh[3])
Downsamp4_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[4]) %>% slice_sample(n = edge_counts_nkh[4])
Downsamp5_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[5]) %>% slice_sample(n = edge_counts_nkh[5])
Downsamp6_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[6]) %>% slice_sample(n = edge_counts_nkh[6])
Downsamp7_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[7]) %>% slice_sample(n = edge_counts_nkh[7])
Downsamp8_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[8]) %>% slice_sample(n = edge_counts_nkh[8])
Downsamp9_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[9]) %>% slice_sample(n = edge_counts_nkh[9])
Downsamp10_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[10]) %>% slice_sample(n = edge_counts_nkh[10])
Downsamp11_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[11]) %>% slice_sample(n = edge_counts_nkh[11])
Downsamp12_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[12]) %>% slice_sample(n = edge_counts_nkh[12])
Downsamp13_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[13]) %>% slice_sample(n = edge_counts_nkh[13])
Downsamp14_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[14]) %>% slice_sample(n = edge_counts_nkh[14])
Downsamp15_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[15]) %>% slice_sample(n = edge_counts_nkh[15])
Downsamp16_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[16]) %>% slice_sample(n = edge_counts_nkh[16])
Downsamp17_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[17]) %>% slice_sample(n = edge_counts_nkh[17])
Downsamp18_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_code_w3 == village_names[18]) %>% slice_sample(n = edge_counts_nkh[18])


Downsamp_all_nkh <- rbind(Downsamp1_nkh,Downsamp2_nkh,Downsamp3_nkh,Downsamp4_nkh,Downsamp5_nkh,
                      Downsamp6_nkh,Downsamp7_nkh,Downsamp8_nkh,Downsamp9_nkh,Downsamp10_nkh,
                      Downsamp11_nkh,Downsamp12_nkh,Downsamp13_nkh,Downsamp14_nkh,Downsamp15_nkh,
                      Downsamp16_nkh,Downsamp17_nkh,Downsamp18_nkh)

Downsamp_all_nkh <- rbind(Downsamp_all_nkh, SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

Downsamp_all_nkh <- Downsamp_all_nkh[complete.cases(Downsamp_all_nkh),]
```



```{r}
#Test out of sample
#Average over 5 CVs
cl <- parallel::makeCluster(5)
doParallel::registerDoParallel(cl)
foreach(i = c(1:5)) %dopar% {
  inds <- c(1:nrow(Downsamp_all))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]

  train1 <- Downsamp_all[train1_inds,]
  test1 <- Downsamp_all[test1_inds,]
  train2 <- Downsamp_all[train2_inds,]
  test2 <- Downsamp_all[test2_inds,]
  train3 <- Downsamp_all[train3_inds,]
  test3 <- Downsamp_all[test3_inds,]
  
  logit.test.1.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                                              same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train1, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  logit.test.2.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                                              same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train2, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  logit.test.3.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                                              same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train3, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  preds.1.onlycovars <- predict(logit.test.1.onlycovars, newdata = test1, type = "response")
  preds.2.onlycovars <- predict(logit.test.2.onlycovars, newdata = test2, type = "response")
  preds.3.onlycovars <- predict(logit.test.3.onlycovars, newdata = test3, type = "response")
  names(preds.3.onlycovars) <- test3_inds
  names(preds.2.onlycovars) <- test2_inds
  names(preds.1.onlycovars) <- test1_inds
  preds.round.onlycovars <- c(preds.1.onlycovars, preds.2.onlycovars, preds.3.onlycovars)
  preds.round.onlycovars <- preds.round.onlycovars[order(as.numeric(names(preds.round.onlycovars)))]
  
  
  logit.test.1 <- lme4::glmer(related ~ strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        education_difference_abs + average_education + household_same +
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        education_difference_abs + average_education + household_same +
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education + household_same +
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  list(preds.round, preds.round.onlycovars, preds.round.covars, preds.round.all)
} -> preds
parallel::stopCluster(cl)

pred.all <- rowSums(sapply(preds, `[[`, 1))/5
pred.all.onlycovars <- rowSums(sapply(preds, `[[`, 2))/5
pred.all.covars <- rowSums(sapply(preds, `[[`, 3))/5
pred.all.all <- rowSums(sapply(preds, `[[`, 4))/5

#add on predictions from strain-sharing only model
pred.all.acc <- pred.all.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all$predicted <- pred.all.acc

#Create ROC object weird it got worse, could do this over multiple downsamples as well
#I think my predictions will be fairly consistent
logit.base.roc <- pROC::roc(Downsamp_all$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.onlycovars.roc <- pROC::roc(Downsamp_all$related, pred.all.onlycovars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")


roc.list <- list("Strain-Sharing Rate" = logit.base.roc,
                 "Only Socio-Dem Covars" = logit.onlycovars.roc,
                 "SSR + Age + Gender + Household Sharing" = logit.covars.roc,
                 "SSR + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=1, color = "grey") +
  coord_equal()

for(i in 1:4) {
  roc.plot <- roc.plot + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot <- roc.plot + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", 'Orange', "Green", "Blue"), 
                       labels=c(paste("Strain-Sharing Rate: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(pROC::var(logit.base.roc)),3), sep=""), 
                                paste("Only Socio-Dem Covars:", round(logit.onlycovars.roc$auc,2 ),
                                      " ± ",round(sqrt(pROC::var(logit.onlycovars.roc)),3), sep=""), 
                                paste("SSR + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(pROC::var(logit.covars.roc)),3), sep=""),
                                paste("SSR + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(pROC::var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("All Social or Familial Relationships")

roc.plot <- roc.plot +
  theme_pubr(legend =  c(0.6, 0.2)) +
  theme(plot.title = element_text(size = 10, hjust = .5)) +
  labs_pubr()

roc.plot <- roc.plot + theme(
  plot.title = element_text(size = 10, hjust = .5),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8)
)

```

# Calculate R2 for all relationships
```{r}
llm_all_kin_for2 <- lme4::lmer(strain_sharing_rate ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education + household_same +
                        related + (1|village_code_w3),
                              data = Downsamp_all)
r2glmm::r2beta(llm_all_kin_for2, method = 'nsj')
write_tsv(r2glmm::r2beta(llm_all_kin_for2, method = 'nsj'), 'tables/r2_beta_all_relationships.tsv')
```
Non-Kin different house model
```{r}
cl <- parallel::makeCluster(5)
doParallel::registerDoParallel(cl)
foreach(i = c(1:5)) %dopar% {
  inds <- c(1:nrow(Downsamp_all_nkh))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all_nkh)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]
  
  train1 <- Downsamp_all_nkh[train1_inds,]
  test1 <- Downsamp_all_nkh[test1_inds,]
  train2 <- Downsamp_all_nkh[train2_inds,]
  test2 <- Downsamp_all_nkh[test2_inds,]
  train3 <- Downsamp_all_nkh[train3_inds,]
  test3 <- Downsamp_all_nkh[test3_inds,]
  
  logit.test.1 <- lme4::glmer(related ~ strain_sharing_rate + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ strain_sharing_rate + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ strain_sharing_rate + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train1, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  logit.test.2.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train2, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  logit.test.3.onlycovars <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                                              indigenous.one + religion.same + age_difference_abs +
                                              average_age + wealth_difference_abs + average_wealth +
                                              education_difference_abs + average_education + household_same + (1|village_code_w3),
                                              data = train3, family = binomial, control=lme4::glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
  preds.1.onlycovars <- predict(logit.test.1.onlycovars, newdata = test1, type = "response")
  preds.2.onlycovars <- predict(logit.test.2.onlycovars, newdata = test2, type = "response")
  preds.3.onlycovars <- predict(logit.test.3.onlycovars, newdata = test3, type = "response")
  names(preds.3.onlycovars) <- test3_inds
  names(preds.2.onlycovars) <- test2_inds
  names(preds.1.onlycovars) <- test1_inds
  preds.round.onlycovars <- c(preds.1.onlycovars, preds.2.onlycovars, preds.3.onlycovars)
  preds.round.onlycovars <- preds.round.onlycovars[order(as.numeric(names(preds.round.onlycovars)))]

  logit.test.1.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ strain_sharing_rate + gender.mm + gender.mf +
                        age_difference_abs + average_age + household_same + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        education_difference_abs + average_education + household_same + 
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        education_difference_abs + average_education + household_same + 
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        education_difference_abs + average_education + household_same + 
                        strain_sharing_rate + (0+strain_sharing_rate|village_code_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  list(preds.round, preds.round.onlycovars, preds.round.covars, preds.round.all)
} -> preds
parallel::stopCluster(cl)


pred.all <- rowSums(sapply(preds, `[[`, 1))/5
pred.all.onlycovars <- rowSums(sapply(preds, `[[`, 2))/5
pred.all.covars <- rowSums(sapply(preds, `[[`, 3))/5
pred.all.all <- rowSums(sapply(preds, `[[`, 4))/5

pred.all.acc <- pred.all.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all_nkh$predicted <- pred.all.acc

logit.base.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.onlycovars.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.onlycovars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

pROC::auc(logit.base.roc)[1]
pROC::auc(logit.covars.roc)[1]
pROC::auc(logit.all.roc)[1]

roc.list <- list("Strain-Sharing Rate" = logit.base.roc,
                 "Only Socio-Dem Covars" = logit.onlycovars.roc,
                 "SSR + Age + Gender" = logit.covars.roc,
                 "SSR + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot.nkh <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=1, color = "grey") +
  coord_equal()

for(i in 1:3) {
  roc.plot.nkh <- roc.plot.nkh + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot.nkh <- roc.plot.nkh + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", 'Orange', "Green", "Blue"), 
                       labels=c(paste("Strain-Sharing Rate: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(pROC::var(logit.base.roc)),3), sep=""), 
                                paste("Only Socio-Dem Covars:", round(logit.onlycovars.roc$auc,2 ),
                                      " ± ",round(sqrt(pROC::var(logit.onlycovars.roc)),3), sep=""), 
                                paste("SSR + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(pROC::var(logit.covars.roc)),3), sep=""),
                                paste("SSR + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(pROC::var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("Non-Kin Different House Relationships")

roc.plot.nkh <- roc.plot.nkh +
  theme_pubr(legend =  c(0.6, 0.2)) +
  theme(plot.title = element_text(size = 10, hjust = .5)) +
  labs_pubr()

roc.plot.nkh <- roc.plot.nkh + theme(
  plot.title = element_text(size = 10, hjust = .5),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8)
)
```

```{r}
rocs_1_ext <-ggarrange(roc.plot, roc.plot.nkh, nrow = 1, labels = c("A", "B"))

svglite("Figures/fig21_extended_covariates.svg", fix_text_size = FALSE)
rocs_1_ext
dev.off()
```

# Calculate R2 for non-kin relationships
```{r}
llm_non_kin_for2 <- lme4::lmer(strain_sharing_rate ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education + household_same + related + (1|village_code_w3),
                              data = Downsamp_all_nkh)
r2glmm::r2beta(llm_non_kin_for2, method = 'nsj')
write_tsv(r2glmm::r2beta(llm_non_kin_for2, method = 'nsj'), 'tables/r2_beta_nonkin_relationships.tsv')
```

# Predicted network of all social or familial relationships
```{r}
metrics_all_predictions <- Downsamp_all |> 
  inner_join(village_map, by = join_by(village_code_w3==village_code)) |> 
  group_by(village_name_deid) |>  
  summarize( `Percent predicted` = mean(predicted),
             `Percent real` = mean(related),
             TP = sum(predicted == 1 & related == 1 ),
             TN = sum(predicted == 0 & related == 0 ),
             FP = sum(predicted == 1 & related == 0 ),
             FN = sum(predicted == 0 & related == 1 ),
             TPR = TP/(TP+FN),
             FNR = FN/(TP+FN),
             TNR = TN/(TN+FP),
             Precision = TP/(TP+FP),
             Accuracy = (TP+TN)/(TP+TN+FP+FN),
             F1 = 2*TP / (2*TP + FP + FN)
          ) |> 
  rename(`Village name` = village_name_deid)
metrics_all_predictions
```
```{r}
write_tsv(metrics_all_predictions, 'tables/metrics_all_relationships_network_villages_prediction_expanded.tsv')
writexl::write_xlsx(metrics_all_predictions, 'tables/metrics_all_relationships_network_villages_prediction_expanded.xlsx')
```

#Predicted network of non-kin relationships
```{r}
metrics_non_kin_prediction <- Downsamp_all_nkh |> 
  inner_join(village_map, by = join_by(village_code_w3==village_code)) |> 
  group_by(village_name_deid) |>  
  summarize( `Percent predicted` = mean(predicted),
             `Percent real` = mean(related),
             TP = sum(predicted == 1 & related == 1 ),
             TN = sum(predicted == 0 & related == 0 ),
             FP = sum(predicted == 1 & related == 0 ),
             FN = sum(predicted == 0 & related == 1 ),
             TPR = TP/(TP+FN),
             FNR = FN/(TP+FN),
             TNR = TN/(TN+FP),
             Precision = TP/(TP+FP),
             Accuracy = (TP+TN)/(TP+TN+FP+FN),
             F1 = 2*TP / (2*TP + FP + FN)
          ) |> 
      rename(`Village name` = village_name_deid)

metrics_non_kin_prediction
```

```{r}
write_tsv(metrics_non_kin_prediction, 'tables/metrics_non_kin_network_villages_prediction_expanded.tsv')
writexl::write_xlsx(metrics_non_kin_prediction, 'tables/metrics_non_kin_network_villages_prediction_expanded.xlsx')
```


# Permutation feature importance: all relationships
```{r}
Downsamp_all_importance <- Downsamp_all %>%
  select(-c(ego, alter, bray_curtis_sim, predicted))

mse_perms_ssr <- data.frame(matrix(nrow = 100, ncol = 17))
colnames(mse_perms_ssr) <- c("gender", "indigenous_status", "religion", "age_difference","average_age","wealth_difference", "average_wealth",
                             "education_difference","average_education","household_same","related","average_diet", "different_diet", 'average_bristol','different_bristol',
                             'watersource_same','same_med_usage')

#Gender
print("gender")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  gender_cols <- dat_permuted[,c("gender.mm", "gender.mf")]
  gender_cols <- gender_cols[sample(nrow(gender_cols)),]
  dat_permuted[,c("gender.mm", "gender.mf")] <- gender_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$gender[i] <- mean(lm_perm$residuals^2)

}

#indigenous status
print("indigenous status")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  indigenous_cols <- dat_permuted[,c("indigenous.both", "indigenous.one")]
  indigenous_cols <- indigenous_cols[sample(nrow(indigenous_cols)),]
  dat_permuted[,c("indigenous.both", "indigenous.one")] <- indigenous_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$indigenous_status[i] <- mean(lm_perm$residuals^2)

}
#religion
print("religion")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$religion.same <- sample(dat_permuted$religion.same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$religion[i] <- mean(lm_perm$residuals^2)

}
#age difference
print("age difference")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$age_difference_abs <- sample(dat_permuted$age_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$age_difference[i] <- mean(lm_perm$residuals^2)

}
#average age
print("average age")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_age <- sample(dat_permuted$average_age)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_age[i] <- mean(lm_perm$residuals^2)

}
#wealth difference
print("wealth difference")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$wealth_difference_abs <- sample(dat_permuted$wealth_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$wealth_difference[i] <- mean(lm_perm$residuals^2)

}
#average wealth
print("average wealth")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_wealth <- sample(dat_permuted$average_wealth)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_wealth[i] <- mean(lm_perm$residuals^2)

}
#education
print("education")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$education_difference_abs <- sample(dat_permuted$education_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$education_difference[i] <- mean(lm_perm$residuals^2)

}
#average education
print("average education")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_education <- sample(dat_permuted$average_education)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_education[i] <- mean(lm_perm$residuals^2)

}
#related
print("related")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$related <- sample(dat_permuted$related)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$related[i] <- mean(lm_perm$residuals^2)

}

print("same_household")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$household_same <- sample(dat_permuted$household_same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$household_same[i] <- mean(lm_perm$residuals^2)

}
print("different diet")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$different_diet <- sample(dat_permuted$different_diet)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$different_diet[i] <- mean(lm_perm$residuals^2)

}
print("average diet")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_diet <- sample(dat_permuted$average_diet)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_diet[i] <- mean(lm_perm$residuals^2)

}
print("different bristol")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$different_bristol <- sample(dat_permuted$different_bristol)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$different_bristol[i] <- mean(lm_perm$residuals^2)

}
print("average bristol")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_bristol <- sample(dat_permuted$average_bristol)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_bristol[i] <- mean(lm_perm$residuals^2)

}
print("watersource_same")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$watersource_same <- sample(dat_permuted$watersource_same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$watersource_same[i] <- mean(lm_perm$residuals^2)

}

print("same_med_usage")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  med_cols <- dat_permuted[,c('same_usage_painkillers', 'same_usage_antibiotics', 'same_usage_antidiarrheal', 'same_usage_antiparasite', 
                              'same_usage_vitamins', 'same_usage_zinc', 'same_usage_antifungal', 'same_usage_antihypertensives', 
                              'same_usage_antidiabetics', 'same_usage_antiacids', 'same_usage_laxatives')]
  med_cols <- med_cols[sample(nrow(med_cols)),]
  dat_permuted[,c('same_usage_painkillers', 'same_usage_antibiotics', 'same_usage_antidiarrheal', 'same_usage_antiparasite', 
                              'same_usage_vitamins', 'same_usage_zinc', 'same_usage_antifungal', 'same_usage_antihypertensives', 
                              'same_usage_antidiabetics', 'same_usage_antiacids', 'same_usage_laxatives')] <- med_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$same_med_usage[i] <- mean(lm_perm$residuals^2)

}

#Get original linear regression model
lm_ssr <- lm(strain_sharing_rate ~ . ,
                 data = Downsamp_all_importance)
#Get original mse
mse_ssr <- mean(lm_ssr$residuals^2)

#Get percent change in auc from original under permutation
#mse_perms_percent_ssr <- (as.numeric(mse_ssr) - mse_perms_percent_ssr) / as.numeric(mse_ssr) * 100
mse_perms_percent_ssr <- mse_perms_ssr - as.numeric(mse_ssr)

#Get mean drop and standard devation in dataframe
mse_perms_ssr_dat_all_rel <- data.frame(name = names(mse_perms_percent_ssr),
                                value = colMeans(mse_perms_percent_ssr),
                                sd = apply(mse_perms_percent_ssr,2,sd))

#Change Name to Make More Readable
mse_perms_ssr_dat_all_rel$name <-c("Gender",
                           "Indigenous\nStatus",
                           "Religion",
                           "Age\nDifference",
                           "Average\nAge",
                           "Wealth\nDifference",
                           "Average\nWealth",
                           "Education\nDifference",
                           "Average\nEducation",
                           "Household\nSharing",
                           "Has\nrelationship",
                           "Average\ndiet",
                           'Diet\ndifference',
                           'Average\nBristol\nScale',
                           'Different\nBristol\nScale',
                           'Water\nsource',
                           'Medication\nusage'
                           )

#Create plot
fi_all <- ggplot(mse_perms_ssr_dat_all_rel) +
  geom_bar(
    aes(x = reorder(name,-value), y = value),
    stat = "identity",
    fill = "skyblue",
    alpha = 0.7
  ) +
  geom_errorbar(
    aes(
      x = name,
      ymin = value - sd,
      ymax = value + sd
    ),
    width = 0.4,
    colour = "orange",
    alpha = 0.9,
    linewidth = 1.3
  ) +
  coord_cartesian(ylim = c(0, 3.5)) +
  xlab("Covariate") +
  ylab(bquote(MSE[perm] - MSE[orig])) +
  theme_bw() +
  ggtitle("All Social and Familial Relationships") +
  theme_pubr() +
  labs_pubr() +
  theme(axis.text.x = element_text( vjust = 1, hjust=.5, size = 9),
        plot.title = element_text(hjust=.5)
  )

```



```{r}
Downsamp_all_importance <- Downsamp_all_nkh %>%
  select(-c(ego, alter, bray_curtis_sim, predicted))

mse_perms_ssr <- data.frame(matrix(nrow = 100, ncol = 17))
colnames(mse_perms_ssr) <- c("gender", "indigenous_status", "religion", "age_difference","average_age","wealth_difference", "average_wealth",
                             "education_difference","average_education","household_same","related","average_diet", "different_diet", 'average_bristol','different_bristol',
                             'watersource_same','same_med_usage')

#Gender
print("gender")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  gender_cols <- dat_permuted[,c("gender.mm", "gender.mf")]
  gender_cols <- gender_cols[sample(nrow(gender_cols)),]
  dat_permuted[,c("gender.mm", "gender.mf")] <- gender_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$gender[i] <- mean(lm_perm$residuals^2)

}

#indigenous status
print("indigenous status")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  indigenous_cols <- dat_permuted[,c("indigenous.both", "indigenous.one")]
  indigenous_cols <- indigenous_cols[sample(nrow(indigenous_cols)),]
  dat_permuted[,c("indigenous.both", "indigenous.one")] <- indigenous_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$indigenous_status[i] <- mean(lm_perm$residuals^2)

}
#religion
print("religion")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$religion.same <- sample(dat_permuted$religion.same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$religion[i] <- mean(lm_perm$residuals^2)

}
#age difference
print("age difference")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$age_difference_abs <- sample(dat_permuted$age_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$age_difference[i] <- mean(lm_perm$residuals^2)

}
#average age
print("average age")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_age <- sample(dat_permuted$average_age)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_age[i] <- mean(lm_perm$residuals^2)

}
#wealth difference
print("wealth difference")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$wealth_difference_abs <- sample(dat_permuted$wealth_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$wealth_difference[i] <- mean(lm_perm$residuals^2)

}
#average wealth
print("average wealth")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_wealth <- sample(dat_permuted$average_wealth)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_wealth[i] <- mean(lm_perm$residuals^2)

}
#education
print("education")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$education_difference_abs <- sample(dat_permuted$education_difference_abs)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$education_difference[i] <- mean(lm_perm$residuals^2)

}
#average education
print("average education")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_education <- sample(dat_permuted$average_education)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_education[i] <- mean(lm_perm$residuals^2)

}
#related
print("related")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$related <- sample(dat_permuted$related)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$related[i] <- mean(lm_perm$residuals^2)

}

print("same_household")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$household_same <- sample(dat_permuted$household_same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$household_same[i] <- mean(lm_perm$residuals^2)

}
print("different diet")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$different_diet <- sample(dat_permuted$different_diet)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$different_diet[i] <- mean(lm_perm$residuals^2)

}
print("average diet")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_diet <- sample(dat_permuted$average_diet)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_diet[i] <- mean(lm_perm$residuals^2)

}
print("different bristol")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$different_bristol <- sample(dat_permuted$different_bristol)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$different_bristol[i] <- mean(lm_perm$residuals^2)

}
print("average bristol")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$average_bristol <- sample(dat_permuted$average_bristol)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$average_bristol[i] <- mean(lm_perm$residuals^2)

}
print("watersource_same")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  dat_permuted$watersource_same <- sample(dat_permuted$watersource_same)
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$watersource_same[i] <- mean(lm_perm$residuals^2)

}

print("same_med_usage")
dat_permuted <- Downsamp_all_importance
for(i in 1:100){
  med_cols <- dat_permuted[,c('same_usage_painkillers', 'same_usage_antibiotics', 'same_usage_antidiarrheal', 'same_usage_antiparasite', 
                              'same_usage_vitamins', 'same_usage_zinc', 'same_usage_antifungal', 'same_usage_antihypertensives', 
                              'same_usage_antidiabetics', 'same_usage_antiacids', 'same_usage_laxatives')]
  med_cols <- med_cols[sample(nrow(med_cols)),]
  dat_permuted[,c('same_usage_painkillers', 'same_usage_antibiotics', 'same_usage_antidiarrheal', 'same_usage_antiparasite', 
                              'same_usage_vitamins', 'same_usage_zinc', 'same_usage_antifungal', 'same_usage_antihypertensives', 
                              'same_usage_antidiabetics', 'same_usage_antiacids', 'same_usage_laxatives')] <- med_cols
  lm_perm <- lm(strain_sharing_rate ~ ., data = dat_permuted)
  mse_perms_ssr$same_med_usage[i] <- mean(lm_perm$residuals^2)

}

#Get original linear regression model
lm_ssr <- lm(strain_sharing_rate ~ . ,
                 data = Downsamp_all_importance)

#Get original mse
mse_ssr <-  mean(lm_ssr$residuals^2)

#Get percent change in auc from original under permutation
mse_perms_percent_ssr <- mse_perms_ssr
mse_perms_percent_ssr <- mse_perms_ssr - mse_ssr

#Get mean drop and standard devation in dataframe
mse_perms_ssr_dat_nk <- data.frame(name = names(mse_perms_percent_ssr),
                                value = colMeans(mse_perms_percent_ssr),
                                sd = apply(mse_perms_percent_ssr,2,sd))

#Change Name to Make More Readable
mse_perms_ssr_dat_nk$name <-c("Gender",
                           "Indigenous\nStatus",
                           "Religion",
                           "Age\nDifference",
                           "Average\nAge",
                           "Wealth\nDifference",
                           "Average\nWealth",
                           "Education\nDifference",
                           "Average\nEducation",
                           "Household\nSharing",
                           "Has\nrelationship",
                           "Average\ndiet",
                           'Diet\ndifference',
                           'Average\nBristol\nScale',
                           'Different\nBristol\nScale',
                           'Water\nsource',
                           'Medication\nusage'
                           )

#Create plot
fi_all_nkh <- ggplot(mse_perms_ssr_dat_nk) +
  geom_bar(
    aes(x = reorder(name,-value), y = value),
    stat = "identity",
    fill = "skyblue",
    alpha = 0.7
  ) +
  geom_errorbar(
    aes(
      x = name,
      ymin = value - sd,
      ymax = value + sd
    ),
    width = 0.4,
    colour = "orange",
    alpha = 0.9,
    linewidth = 1.3
  ) +
  coord_cartesian(ylim = c(0, 3)) +
  xlab("Covariate") +
  ylab(bquote(MSE[perm] - MSE[orig])) +
  theme_bw() +
  ggtitle("Non-Kin Different House Relationships") +
  theme_pubr() +
  labs_pubr() +
  theme(axis.text.x = element_text( vjust = 1, hjust=.5, size = 9),
        plot.title = element_text(hjust=.5)
  )
```


```{r}
fi_fig <- ggarrange(fi_all + rremove("ylab"),
                    fi_all_nkh+ rremove("ylab"),
                    nrow = 2,
                    labels = c("A", "B"))


svglite("Figures/sfigure20_full.svg", width = 14, height = 12, bg = 'transparent',fix_text_size = FALSE)
annotate_figure(fi_fig, 
                left = text_grob(bquote(MSE[perm] - MSE[orig]),rot = 90, size = 14),
                top = text_grob("Permutation Feature Importance", size = 14),
                )
dev.off()


annotate_figure(fi_fig, 
                left = text_grob(bquote(MSE[perm] - MSE[orig]),rot = 90, size = 14, ),
                top = text_grob("Permutation Feature Importance", size = 14),
                )

```
