---
title: "LinkPrediction"
author: "Jackson Pullman"
date: "2023-02-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pROC)
```

# Degradation by scrambling
```{r}
#Change format of covariates to merge onto edge list
Covars_ego <- covariates %>% merge(household_wealth_data) %>%
  unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |> 
  rename(ego = respondent_master_id, ego_age = age_at_survey, ego_gender = gender,
         ego_household = building_id,
         ego_household_wealth = household_wealth_index_w3, ego_education = b0100, ego_indigenous = indigenous_status, 
         ego_religion = b0600, ego_length_in_village = b0800, ego_length_in_village_years = b0900,
         ego_DDS = DDS, 
         ego_latitude = building_latitude, ego_longitude = building_longitude) %>%
  mutate(ego_education = dplyr::recode(ego_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         ego_indigenous = recode(ego_indigenous, "Lenca" = 1, "Ch'orti'/Maya Chorti" = 1, .default = 0)) %>% 
  dplyr::select(-c("village_name", "marital_name"))

Covars_alter <- covariates %>% merge(household_wealth_data) %>%
    unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |>
  rename(alter = respondent_master_id, alter_age = age_at_survey, alter_gender = gender,
         alter_household = building_id,
         alter_household_wealth = household_wealth_index_w3, alter_education = b0100, alter_indigenous = indigenous_status, 
         alter_religion = b0600, alter_length_in_village = b0800, alter_length_in_village_years = b0900,
         alter_latitude = building_latitude, alter_longitude = building_longitude) %>%
  mutate(alter_education = recode(alter_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         alter_indigenous = recode(alter_indigenous, "Lenca" = 1, "Ch'orti'/Maya Chorti" = 1, .default = 0)) %>% 
  dplyr::select(-c("village_name", "marital_name"))
```

```{r}
foreach(i = 1:18, .combine = rbind) %do% {
    get(paste0('sn_vil_graph_',i)) |>
    igraph::as_edgelist() |>
    as.data.frame() |>
    rename(ego =1, alter =2 ) |>
    rowwise() |>
    mutate(pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), '')) |>
    ungroup()
} -> orig

# reduced_SN_nonkin <- SN |>
#   group_by(pair_key) |> 
#   reframe(ego, alter, relationship = paste(relationship, collapse = ',') , village_name_w3, village_code_w3) |> 
#   distinct(pair_key, .keep_all = TRUE) |> 
#   mutate(is_kin = grepl('Mother|Father|Child|Sibling', relationship)) |>
#   filter(is_kin == FALSE)

cl1 <- parallel::makeCluster(12)
doParallel::registerDoParallel(cl1)
foreach(p = seq(from = .05, to = 1, by = .05), .packages = c('doParallel','dplyr','igraph')) %do% {
    print(p)
  foreach(i = 1:18, .combine = rbind) %do% {

    # ll <- inner_join(orig, reduced_SN_nonkin, by = join_by(pair == pair_key)) |> 
    #     filter(village_code_w3 == village_names[i]) |>
    #     select(1:2) |>
    #     rowwise() |> 
    #     mutate(p = list(c(ego.x, alter.x))) |>
    #     ungroup() |>
    #     pull(p) |>
    #     unlist()

    # subgraph.edges(get(paste0('sn_vil_graph_',i)), eids = get.edge.ids(get(paste0('sn_vil_graph_',i)), ll)) |>
    get(paste0('sn_vil_graph_',i)) |>
    rewire(each_edge(prob = p)) |>
    igraph::as_edgelist() |>
    as.data.frame() |>
    rename(ego =1, alter =2 ) |>
    rowwise() |>
    mutate(pair_key = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), '')) |>
    ungroup()
  } -> scram

    #Merge covariate data onto edge list
    SN_All_Covars <- scram |>
                    inner_join(Covars_ego, by = join_by("ego"=="ego")) |>
                    inner_join(Covars_alter, by = join_by("alter"=="alter")) |>
                    rowwise() |> 
                    mutate(strain_sharing_rate = strain_rate[ego, alter],
                        bray_curtis_sim = species_bray[ego, alter]) |>
                    ungroup() |>
                    rename(village_code_w3 = village_code_w3.y)

    #Get covariate matrix for people without a relationship
    village_names <- unique(SN_All_Covars$village_code_w3)
    foreach(v = village_names, .combine = rbind) %do%
    {
    #Split up matrix into villages
    SN_Village_w3 <- SN_All_Covars %>% filter(village_code_w3 == v)
    #IDs of everyone in village
    Village_IDs_w3 <- unique(c(as.character(SN_Village_w3$ego), as.character(SN_Village_w3$alter)))
    data.frame(t(combn(Village_IDs_w3, 2, simplify = TRUE))) |> 
        dplyr::rename(ego = X1, alter = X2) |> 
        mutate(pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), '')) |> 
        filter(!pair %in% SN_Village_w3$pair) |> 
        inner_join(Covars_ego, by = 'ego') |> 
        inner_join(Covars_alter, by = 'alter', suffix = c('_ego','_alter')) |> 
        mutate(
        relationship = "Un-Nominated Same Village",
        village_code_w3 = v,
        gender.mm = ego_gender == 'man' & alter_gender == 'man',
        gender.mf = ego_gender == "man" & alter_gender == "woman" | ego_gender == "woman" & alter_gender == "man",
        gender.ff = ego_gender == 'woman' & alter_gender == 'woman',
        indigenous.both = ego_indigenous == 1 & alter_indigenous == 1, 
        indigenous.one = ego_indigenous == 1 & alter_indigenous == 0 | ego_indigenous == 0 & alter_indigenous == 1,
        indigenous.none = ego_indigenous == 0 & alter_indigenous == 0,
        religion.same = ego_religion == alter_religion,
        age_difference_abs = abs(ego_age - alter_age),
        average_age = (ego_age + alter_age)/2,
        wealth_difference_abs = abs(ego_household_wealth - alter_household_wealth),
        average_wealth = (ego_household_wealth + alter_household_wealth)/2,
        education_difference_abs = abs(ego_education - alter_education),
        average_education = (ego_education + alter_education)/2,
        household_same = ego_household == alter_household
        ) |> 
        rowwise() |> 
        mutate(strain_sharing_rate = strain_rate[ego, alter],
            bray_curtis_sim = species_bray[ego, alter]) |>
        ungroup()
    } -> All_NoRel_Covars

    SN_All_Covars_for_Regression <- SN_All_Covars |> 
    distinct(pair_key, .keep_all = TRUE) |> 
    mutate(gender.mm = ego_gender == "man" & alter_gender == "man",
            gender.mf = ego_gender == "woman" & alter_gender == "man" | ego_gender == "man" & alter_gender == "woman",
            gender.ff = ego_gender == "woman" & alter_gender == "woman",
            indigenous.both = ego_indigenous == 1 & alter_indigenous == 1,
            indigenous.one = ego_indigenous == 1 & alter_indigenous == 0 | ego_indigenous == 0 & alter_indigenous == 1,
            indigenous.none = ego_indigenous == 0 & alter_indigenous == 0,
            religion.same = ego_religion == alter_religion,
            age_difference_abs = abs(ego_age - alter_age),
            average_age = (ego_age + alter_age)/2,
            wealth_difference_abs = abs(ego_household_wealth - alter_household_wealth),
            average_wealth = (ego_household_wealth + alter_household_wealth)/2,
            education_difference_abs = abs(ego_education - alter_education),
            average_education = (ego_education + alter_education)/2,
            household_same = ego_household == alter_household)

    #Make dataframe with only non-kin in different house
    SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
    filter(!(pair_key %in% family_house_pairs))


    #select predictors
    SN_All_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
    mutate(related = 1) %>% 
    dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
            "age_difference_abs", "average_age", "wealth_difference_abs",
            "average_wealth", "education_difference_abs","average_education", "household_same",
            "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")

    SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_Non_Kin_Dif_House_Covars_for_Regression %>%
    mutate(related = 1) %>% 
    dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
            "age_difference_abs", "average_age", "wealth_difference_abs",
            "average_wealth", "education_difference_abs","average_education","household_same",
            "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")


    All_NoRel_Covars_for_Regression <- All_NoRel_Covars %>%
    mutate(related = 0) %>%
    dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
                    "age_difference_abs", "average_age", "wealth_difference_abs",
                    "average_wealth", "education_difference_abs","average_education","household_same",
                    "related", "strain_sharing_rate", "village_code_w3", "bray_curtis_sim")#, "jaccard_sim")


    #Combine relationships and non relationship dataframe
    SN_All_Covars_for_Regression_complete <- SN_All_Covars_for_Regression[complete.cases(SN_All_Covars_for_Regression),]

    SN_Non_Kin_Dif_House_Covars_for_Regression_complete <- SN_Non_Kin_Dif_House_Covars_for_Regression[complete.cases(SN_Non_Kin_Dif_House_Covars_for_Regression),]

    All_for_Regression <- rbind(All_NoRel_Covars_for_Regression, SN_All_Covars_for_Regression)

    Non_Kin_House_for_Regression <- rbind(All_NoRel_Covars_for_Regression,
                                        SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

    #May want to check if this is missing completely at random or input columns
    #filter to complete cases
    All_for_Regression_complete <- All_for_Regression[complete.cases(All_for_Regression),]

    All_NoRel_Covars_for_Regression_complete <- All_NoRel_Covars_for_Regression[complete.cases(All_NoRel_Covars_for_Regression),]

    Non_Kin_House_for_Regression_complete <-
    Non_Kin_House_for_Regression[complete.cases(Non_Kin_House_for_Regression),]

    edge_counts_nkh <- SN_Non_Kin_Dif_House_Covars_for_Regression_complete %>%
    group_by(village_code_w3) %>%
    summarize(edge_count = sum(related))

    edge_counts_nkh <- edge_counts_nkh[match(village_names, edge_counts_nkh$village_code_w3), ] %>%
    filter(!is.na(village_code_w3)) |> 
    pull(edge_count, village_code_w3)

    foreach(v = names(edge_counts_nkh), .combine = rbind) %do% {
        All_NoRel_Covars_for_Regression_complete %>%
        filter(village_code_w3 == as.integer(v)) %>% slice_sample(n = edge_counts_nkh[[v]])
    } -> Downsamp_all_nkh

    Downsamp_all_nkh <- as.data.frame(Downsamp_all_nkh)
    Downsamp_all_nkh <- rbind(Downsamp_all_nkh, SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

    Downsamp_all_nkh <- Downsamp_all_nkh[complete.cases(Downsamp_all_nkh), ]

    cl <- parallel::makeCluster(5)
    doParallel::registerDoParallel(cl)
    foreach(i = c(1:5)) %dopar% {
    inds <- c(1:nrow(Downsamp_all_nkh))
    test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all_nkh)), replace = F)
    train1_inds <- inds[!(inds %in% test1_inds)]
    test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
    train2_inds <- inds[!(inds %in% test2_inds)]
    test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
    train3_inds <- inds[!(inds %in% test3_inds)]
    
    train1 <- Downsamp_all_nkh[train1_inds,]
    test1 <- Downsamp_all_nkh[test1_inds,]
    train2 <- Downsamp_all_nkh[train2_inds,]
    test2 <- Downsamp_all_nkh[test2_inds,]
    train3 <- Downsamp_all_nkh[train3_inds,]
    test3 <- Downsamp_all_nkh[test3_inds,]
    
    logit.test.1.all <- lme4::glmer(related ~ strain_sharing_rate + 
                            gender.mm + gender.mf + indigenous.both +
                            indigenous.one + religion.same + age_difference_abs +
                            average_age + wealth_difference_abs + average_wealth +
                            education_difference_abs + average_education + household_same + 
                            (0+strain_sharing_rate|village_code_w3),
                                data = train1, family = binomial)
    logit.test.2.all <- lme4::glmer(related ~ strain_sharing_rate + 
                            gender.mm + gender.mf + indigenous.both +
                            indigenous.one + religion.same + age_difference_abs +
                            average_age + wealth_difference_abs + average_wealth +
                            education_difference_abs + average_education + household_same + 
                            (0+strain_sharing_rate|village_code_w3),
                                data = train2, family = binomial)
    logit.test.3.all <- lme4::glmer(related ~ strain_sharing_rate + 
                            gender.mm + gender.mf + indigenous.both +
                            indigenous.one + religion.same + age_difference_abs +
                            average_age + wealth_difference_abs + average_wealth +
                            education_difference_abs + average_education + household_same + 
                            (0+strain_sharing_rate|village_code_w3),
                                data = train3, family = binomial)
    
    preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
    preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
    preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
    names(preds.3.all) <- test3_inds
    names(preds.2.all) <- test2_inds
    names(preds.1.all) <- test1_inds
    preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
    preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
    
    preds.round.all
    } -> preds
    parallel::stopCluster(cl)

    pred.all.all <- Reduce(`+`,preds) /5



    logit.all.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.all, ci=TRUE, plot=FALSE,
                    levels=c("0","1"), direction = "<")
    list(p, logit.all.roc)
} -> roc_list

    roc_list <- lapply(roc_list, `[[`, 2)
    names(roc_list)  <- seq(from = .05, to = 1, by = .05) * 100

    ci_list <- lapply(roc_list, ci.se, specificities = seq(0, 1, l = 25))

    dat.ci.list <- lapply(ci_list, function(ciobj) 
    data.frame(x = as.numeric(rownames(ciobj)),
                lower = ciobj[, 1],
                upper = ciobj[, 3]))

    roc_plot_scrambled <- ggroc(roc_list) +
    theme_minimal() +
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=1, color = "grey") +
    coord_equal() +
    theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "Percent of removed ties",
                         values=c("#68002d",
"#34ff99",
"#ff2ec3",
"#c6ff7c",
"#0158bc",
"#9c9c00",
"#b7005e",
"#82ffb5",
"#ff5c42",
"#00f1dd",
"#1c0200",
"#ffed93",
"#01779e",
"#ffdca8",
"#005452",
"#ffb3e5",
"#01be86",
"#bae5ff",
"#324e00",
"#a9ffea"),
        labels=unlist(Map(c, seq(from = .05, to = 1, by = .05) * 100, lapply(roc_list, function (x) c(round(x$auc,2), round(sqrt(pROC::var(x)),3)))) |> lapply(FUN = function(x) paste0(x[1],'% : AUC = ',x[2],' ± ', x[3], collapse = '')))) +
  ggtitle("Non-Kin Different House Relationships (Randomized ties)") + 
  ylab('Sensitivity') + xlab('Specificity')

roc_plot_scrambled
```


```{r}
t(sapply(roc_list, function(x) as.numeric(x$ci))) |>
as.data.frame() |>
tibble::rownames_to_column('percent') |>
mutate(percent = as.numeric(percent)) |>
rename(lower = 2, upper =4, AUC = 3) |> 
ggplot(aes(percent, AUC)) +
geom_point() +
geom_errorbar(aes(ymin = lower, ymax = upper ))+
scale_x_continuous(breaks = seq(0, 100, by = 5)) +
theme_pubclean() +
xlab('Percent of rewired ties') -> rewired_plot
```

```{r}
svglite('Figures/rewired_plot.svg',  fix_text_size = FALSE, height = 6, width = 8)
rewired_plot
dev.off()
```

```{r}
svglite('Figures/roc_ablation.svg',  fix_text_size = FALSE)
roc_plot_scrambled
dev.off()
```

#Predicted network of all social or familial relationships
```{r}
metrics_all_predictions <- Downsamp_all |> 
  inner_join(village_map, by = join_by(village_code_w3==village_code)) |> 
  group_by(village_name_deid) |>  
  summarize( `Percent predicted` = mean(predicted),
             `Percent real` = mean(related),
             TP = sum(predicted == 1 & related == 1 ),
             TN = sum(predicted == 0 & related == 0 ),
             FP = sum(predicted == 1 & related == 0 ),
             FN = sum(predicted == 0 & related == 1 ),
             TPR = TP/(TP+FN),
             FNR = FN/(TP+FN),
             TNR = TN/(TN+FP),
             Precision = TP/(TP+FP),
             Accuracy = (TP+TN)/(TP+TN+FP+FN),
             F1 = 2*TP / (2*TP + FP + FN)
          ) |> 
  rename(`Village name` = village_name_deid)
metrics_all_predictions
```
```{r}
write_tsv(metrics_all_predictions, 'tables/metrics_all_relationships_network_villages_prediction.tsv')
writexl::write_xlsx(metrics_all_predictions, 'tables/metrics_all_relationships_network_villages_prediction.xlsx')
```

#Predicted network of non-kin relationships
```{r}
metrics_non_kin_prediction <- Downsamp_all_nkh |> 
  inner_join(village_map, by = join_by(village_code_w3==village_code)) |> 
  group_by(village_name_deid) |>  
  summarize( `Percent predicted` = mean(predicted),
             `Percent real` = mean(related),
             TP = sum(predicted == 1 & related == 1 ),
             TN = sum(predicted == 0 & related == 0 ),
             FP = sum(predicted == 1 & related == 0 ),
             FN = sum(predicted == 0 & related == 1 ),
             TPR = TP/(TP+FN),
             FNR = FN/(TP+FN),
             TNR = TN/(TN+FP),
             Precision = TP/(TP+FP),
             Accuracy = (TP+TN)/(TP+TN+FP+FN),
             F1 = 2*TP / (2*TP + FP + FN)
          ) |> 
      rename(`Village name` = village_name_deid)

metrics_non_kin_prediction
```

```{r}
write_tsv(metrics_non_kin_prediction, 'tables/metrics_non_kin_network_villages_prediction.tsv')
writexl::write_xlsx(metrics_non_kin_prediction, 'tables/metrics_non_kin_network_villages_prediction.xlsx')
```
