---
title: "LinkPredictionFI_Species"
author: "Jackson Pullman"
date: "2023-02-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup
Link Prediction Methods
```{r}
#Change format of covariates to merge onto edge list
Covars_ego <- covariates %>% merge(household_wealth_data) %>%
  rename(ego = respondent_master_id, ego_age = age_at_survey, ego_gender = gender,
         ego_household_wealth = household_wealth_index_w3, ego_education = b0100, ego_indigenous = b0200, 
         ego_religion = b0600, ego_length_in_village = b0800, ego_length_in_village_years = b0900,
         ego_latitude = building_latitude, ego_longitude = building_longitude) %>%
  mutate(ego_education = recode(ego_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         ego_indigenous = recode(ego_indigenous, "No" = 0, "Dont_Know" = 0, "Yes, Lenca" = 1, "Yes, Maya Chorti"= 1)) %>% 
  dplyr::select(-c("village_name", "marital_name", "building_id"))

Covars_alter <- covariates %>% merge(household_wealth_data) %>%
  rename(alter = respondent_master_id, alter_age = age_at_survey, alter_gender = gender,
         alter_household_wealth = household_wealth_index_w3, alter_education = b0100, alter_indigenous = b0200, 
         alter_religion = b0600, alter_length_in_village = b0800, alter_length_in_village_years = b0900,
         alter_latitude = building_latitude, alter_longitude = building_longitude) %>%
  mutate(alter_education = recode(alter_education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
         alter_indigenous = recode(alter_indigenous, "No" = 0, "Dont_Know" = 0, "Yes, Lenca" = 1, "Yes, Maya Chorti"= 1)) %>% 
  dplyr::select(-c("village_name", "marital_name", "building_id"))

#Merge covariate data onto edge list
SN_All_Covars <- merge(SN, Covars_ego, by = "ego")
SN_All_Covars <- merge(SN_All_Covars, Covars_alter, by = "alter")

#Get covariate matrix for people without a relationship
for(v in 1:length(village_names)){
  #Split up matrix into villages
  SN_Village <- SN_All_Covars %>% filter(village_name_w3 == village_names[v])
  #IDs of everyone in village
  Village_IDs <- unique(c(as.character(SN_Village$ego), as.character(SN_Village$alter)))

  Village_Pairs <- unique(SN_Village$pair_key)
  
  Village_NoRels <- data.frame(matrix(NA,
                                      nrow = length(Village_IDs) * (length(Village_IDs)-1)/2 - length(Village_Pairs),
                                      ncol = 16))
  colnames(Village_NoRels) <- c("ego","alter","gender.mm","gender.ff", "gender.mf", "indigenous.both", "indigenous.one", "indigenous.none",
                                "religion.same", "age_difference_abs","average_age",
                                "wealth_difference_abs", "average_weatlh", "education_difference_abs",
                                "average_education", "village_name_w3")
  
  k <- 1
  for(i in 1:length(Village_IDs)){
    j <- i+1
    while(j <=  length(Village_IDs)){
      pair <- paste((sort(str_split(paste0(Village_IDs[i], Village_IDs[j]),"")[[1]])),sep="", collapse="")
      if(!pair %in% Village_Pairs){
        p1 <- Covars_ego[Covars_ego$ego == Village_IDs[i],]
        p2 <- Covars_alter[Covars_alter$alter == Village_IDs[j],]
        Village_NoRels$ego[k] <- p1$ego
        Village_NoRels$alter[k] <- p2$alter
        Village_NoRels$gender.mm[k] <- p1$ego_gender == "man" & p2$alter_gender == "man"
        Village_NoRels$gender.mf[k] <- 
          p1$ego_gender == "man" & p2$alter_gender == "woman" | p1$ego_gender == "woman" & p2$alter_gender == "man"
        Village_NoRels$gender.ff[k] <- p1$ego_gender == "woman" & p2$alter_gender == "woman"
        Village_NoRels$indigenous.both[k] <- p1$ego_indigenous == 1 & p2$alter_indigenous == 1
        Village_NoRels$indigenous.one[k] <- 
          p1$ego_indigenous == 1 & p2$alter_indigenous == 0 | p1$ego_indigenous == 0 & p2$alter_indigenous == 1
        Village_NoRels$indigenous.none[k] <- p1$ego_indigenous == 0 & p2$alter_indigenous == 0
        Village_NoRels$religion.same[k] <- p1$ego_religion == p2$alter_religion
        Village_NoRels$age_difference_abs[k] <- abs(p1$ego_age - p2$alter_age)
        Village_NoRels$average_age[k] <- (p1$ego_age + p2$alter_age)/2
        Village_NoRels$wealth_difference_abs[k] <- abs(p1$ego_household_wealth - p2$alter_household_wealth)
        Village_NoRels$average_wealth[k] <- (p1$ego_household_wealth + p2$alter_household_wealth)/2
        Village_NoRels$education_difference_abs[k] <- abs(p1$ego_education - p2$alter_education)
        Village_NoRels$average_education[k] <- (p1$ego_education + p2$alter_education)/2
        Village_NoRels$village_name_w3[k] <- village_names[v]
        k <- k+1
      }
      j <- j+1
    }
  }
  
  if(v ==1){
    All_NoRel_Covars <- Village_NoRels
  }
  else{
    All_NoRel_Covars <- rbind(All_NoRel_Covars,Village_NoRels)
  }
  #Check progress
  print(v)
}
#Set Un-nominated same village realtionship
All_NoRel_Covars$relationship <- "Un-Nominated Same Village"

#Attach strain sharing data to non-nominated relationships
for(i in 1:nrow(All_NoRel_Covars)){
  All_NoRel_Covars$strain_sharing_rate[i] <- strain_rate[rownames(strain_rate) == All_NoRel_Covars$ego[i],
                                                         colnames(strain_rate) == All_NoRel_Covars$alter[i]]
}

#Attach species similarity for non-nominated relationships
for(i in 1:nrow(All_NoRel_Covars)){
  All_NoRel_Covars$bray_curtis_sim[i] <- species_bray[rownames(species_bray) == All_NoRel_Covars$ego[i],
                                                         colnames(species_bray) == All_NoRel_Covars$alter[i]]
}

for(i in 1:nrow(All_NoRel_Covars)){
  All_NoRel_Covars$jaccard_sim[i] <- species_jaccard_sim[rownames(species_jaccard_sim) == All_NoRel_Covars$ego[i],
                                                         colnames(species_jaccard_sim) == All_NoRel_Covars$alter[i]]
}



#Get dataframe of relationships into format for regression
SN_All_Covars_for_Regression <- SN_All_Covars %>% distinct(pair_key, .keep_all = TRUE) %>%
  mutate(gender.mm = ego_gender == "man" & alter_gender == "man",
         gender.mf = ego_gender == "woman" & alter_gender == "man" | ego_gender == "man" & alter_gender == "woman",
         gender.ff = ego_gender == "woman" & alter_gender == "woman",
         indigenous.both = ego_indigenous == 1 & alter_indigenous == 1,
         indigenous.one = ego_indigenous == 1 & alter_indigenous == 0 | ego_indigenous == 0 & alter_indigenous == 1,
         indigenous.none = ego_indigenous == 0 & alter_indigenous == 0,
         religion.same = ego_religion == alter_religion,
         age_difference_abs = abs(ego_age - alter_age),
         average_age = (ego_age + alter_age)/2,
         wealth_difference_abs = abs(ego_household_wealth - alter_household_wealth),
         average_wealth = (ego_household_wealth + alter_household_wealth)/2,
         education_difference_abs = abs(ego_education - alter_education),
         average_education = (ego_education + alter_education)/2)

#Make dataframe with only non-kin in different house
SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
  filter(!(pair_key %in% family_house_pairs))


#select predictors
SN_All_Covars_for_Regression <- SN_All_Covars_for_Regression %>%
  mutate(related = 1) %>% 
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
         "age_difference_abs", "average_age", "wealth_difference_abs",
         "average_wealth", "education_difference_abs","average_education",
         "related", "strain_sharing_rate", "village_name_w3", "bray_curtis_sim", "jaccard_sim")

SN_Non_Kin_Dif_House_Covars_for_Regression <- SN_Non_Kin_Dif_House_Covars_for_Regression %>%
  mutate(related = 1) %>% 
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
         "age_difference_abs", "average_age", "wealth_difference_abs",
         "average_wealth", "education_difference_abs","average_education",
         "related", "strain_sharing_rate", "village_name_w3", "bray_curtis_sim", "jaccard_sim")



All_NoRel_Covars_for_Regression <- All_NoRel_Covars %>%
  mutate(related = 0) %>%
  dplyr::select("ego","alter","gender.mm", "gender.mf", "indigenous.both", "indigenous.one", "religion.same",
                "age_difference_abs", "average_age", "wealth_difference_abs",
                "average_wealth", "education_difference_abs","average_education",
                "related", "strain_sharing_rate", "village_name_w3", "bray_curtis_sim", "jaccard_sim")


#Combine relationships and non relationship dataframe
SN_All_Covars_for_Regression_complete <- SN_All_Covars_for_Regression[complete.cases(SN_All_Covars_for_Regression),]

SN_Non_Kin_Dif_House_Covars_for_Regression_complete <- SN_Non_Kin_Dif_House_Covars_for_Regression[complete.cases(SN_Non_Kin_Dif_House_Covars_for_Regression),]

All_for_Regression <- rbind(All_NoRel_Covars_for_Regression, SN_All_Covars_for_Regression)

Non_Kin_House_for_Regression <- rbind(All_NoRel_Covars_for_Regression,
                                      SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

#May want to check if this is missing completely at random or input columns
#filter to complete cases
All_for_Regression_complete <- All_for_Regression[complete.cases(All_for_Regression),]

All_NoRel_Covars_for_Regression_complete <- All_NoRel_Covars_for_Regression[complete.cases(All_NoRel_Covars_for_Regression),]

Non_Kin_House_for_Regression_complete <-
  Non_Kin_House_for_Regression[complete.cases(Non_Kin_House_for_Regression),]

edge_counts <- SN_All_Covars_for_Regression_complete %>%
  group_by(village_name_w3) %>%
  summarize(edge_count = sum(related)) 

edge_counts <- edge_counts[match(village_names, edge_counts$village_name_w3),] %>%
  pull(edge_count)

edge_counts_nkh <- SN_Non_Kin_Dif_House_Covars_for_Regression_complete %>%
  group_by(village_name_w3) %>%
  summarize(edge_count = sum(related))

edge_counts_nkh <- edge_counts_nkh[match(village_names, edge_counts_nkh$village_name_w3),] %>%
  pull(edge_count)



```

Downsample
```{r}
#Downsample
set.seed(96)
Downsamp1 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[1]) %>% slice_sample(n = edge_counts[1])
Downsamp2 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[2]) %>% slice_sample(n = edge_counts[2])
Downsamp3 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[3]) %>% slice_sample(n = edge_counts[3])
Downsamp4 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[4]) %>% slice_sample(n = edge_counts[4])
Downsamp5 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[5]) %>% slice_sample(n = edge_counts[5])
Downsamp6 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[6]) %>% slice_sample(n = edge_counts[6])
Downsamp7 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[7]) %>% slice_sample(n = edge_counts[7])
Downsamp8 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[8]) %>% slice_sample(n = edge_counts[8])
Downsamp9 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[9]) %>% slice_sample(n = edge_counts[9])
Downsamp10 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[10]) %>% slice_sample(n = edge_counts[10])
Downsamp11 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[11]) %>% slice_sample(n = edge_counts[11])
Downsamp12 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[12]) %>% slice_sample(n = edge_counts[12])
Downsamp13 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[13]) %>% slice_sample(n = edge_counts[13])
Downsamp14 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[14]) %>% slice_sample(n = edge_counts[14])
Downsamp15 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[15]) %>% slice_sample(n = edge_counts[15])
Downsamp16 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[16]) %>% slice_sample(n = edge_counts[16])
Downsamp17 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[17]) %>% slice_sample(n = edge_counts[17])
Downsamp18 <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[18]) %>% slice_sample(n = edge_counts[18])

Downsamp_all <- rbind(Downsamp1,Downsamp2,Downsamp3,Downsamp4,Downsamp5,
                      Downsamp6,Downsamp7,Downsamp8,Downsamp9,Downsamp10,Downsamp11,
                      Downsamp12,Downsamp13,Downsamp14,Downsamp15,
                      Downsamp16,Downsamp17,Downsamp18)

Downsamp_all <- rbind(Downsamp_all, SN_All_Covars_for_Regression_complete)

Downsamp_all <- Downsamp_all[complete.cases(Downsamp_all),]

#Non-kin different house
set.seed(96)
Downsamp1_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[1]) %>% slice_sample(n = edge_counts_nkh[1])
Downsamp2_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[2]) %>% slice_sample(n = edge_counts_nkh[2])
Downsamp3_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[3]) %>% slice_sample(n = edge_counts_nkh[3])
Downsamp4_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[4]) %>% slice_sample(n = edge_counts_nkh[4])
Downsamp5_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[5]) %>% slice_sample(n = edge_counts_nkh[5])
Downsamp6_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[6]) %>% slice_sample(n = edge_counts_nkh[6])
Downsamp7_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[7]) %>% slice_sample(n = edge_counts_nkh[7])
Downsamp8_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[8]) %>% slice_sample(n = edge_counts_nkh[8])
Downsamp9_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[9]) %>% slice_sample(n = edge_counts_nkh[9])
Downsamp10_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[10]) %>% slice_sample(n = edge_counts_nkh[10])
Downsamp11_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[11]) %>% slice_sample(n = edge_counts_nkh[11])
Downsamp12_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[12]) %>% slice_sample(n = edge_counts_nkh[12])
Downsamp13_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[13]) %>% slice_sample(n = edge_counts_nkh[13])
Downsamp14_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[14]) %>% slice_sample(n = edge_counts_nkh[14])
Downsamp15_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[15]) %>% slice_sample(n = edge_counts_nkh[15])
Downsamp16_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[16]) %>% slice_sample(n = edge_counts_nkh[16])
Downsamp17_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[17]) %>% slice_sample(n = edge_counts_nkh[17])
Downsamp18_nkh <- All_NoRel_Covars_for_Regression_complete %>%
  filter(village_name_w3 == village_names[18]) %>% slice_sample(n = edge_counts_nkh[18])


Downsamp_all_nkh <- rbind(Downsamp1_nkh,Downsamp2_nkh,Downsamp3_nkh,Downsamp4_nkh,Downsamp5_nkh,
                      Downsamp6_nkh,Downsamp7_nkh,Downsamp8_nkh,Downsamp9_nkh,Downsamp10_nkh,
                      Downsamp11_nkh,Downsamp12_nkh,Downsamp13_nkh,Downsamp14_nkh,Downsamp15_nkh,
                      Downsamp16_nkh,Downsamp17_nkh,Downsamp18_nkh)

Downsamp_all_nkh <- rbind(Downsamp_all_nkh, SN_Non_Kin_Dif_House_Covars_for_Regression_complete)

Downsamp_all_nkh <- Downsamp_all_nkh[complete.cases(Downsamp_all_nkh),]
```





Jaccard Similarity
```{r}
#Test out of sample
#Average over 5 CVs
for(i in 1:5){
  inds <- c(1:nrow(Downsamp_all))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]

  train1 <- Downsamp_all[train1_inds,]
  test1 <- Downsamp_all[test1_inds,]
  train2 <- Downsamp_all[train2_inds,]
  test2 <- Downsamp_all[test2_inds,]
  train3 <- Downsamp_all[train3_inds,]
  test3 <- Downsamp_all[test3_inds,]
  
  logit.test.1 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  if(i == 1){
    pred.all <- preds.round
    pred.all.covars <- preds.round.covars
    pred.all.all <- preds.round.all
  }
  else{
    pred.all <- pred.all + preds.round
    pred.all.covars <- pred.all.covars + preds.round.covars
    pred.all.all <- pred.all.all + preds.round.all
  }
  
}
#Could make this without random effect don't have to deal with this stuff
pred.all <- pred.all/5
pred.all.covars <- pred.all.covars/5
pred.all.all <- pred.all.all/5

#add on predictions from strain-sharing only model
pred.all.acc <- pred.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all$predicted <- pred.all.acc

#Create ROC object weird it got worse, could do this over multiple downsamples as well
#I think my predictions will be fairly consistent
logit.base.roc <- pROC::roc(Downsamp_all$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

pROC::auc(logit.base.roc)[1]
pROC::auc(logit.covars.roc)[1]
pROC::auc(logit.all.roc)[1]


roc.list <- list("Jaccard Similarity" = logit.base.roc,
                 "Jaccard + Age + Gender" = logit.covars.roc,
                 "Jaccard + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot.j <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
  coord_equal()

for(i in 1:3) {
  roc.plot.j <- roc.plot.j + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot.j <- roc.plot.j + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", "Green", "Blue"), 
                       labels=c(paste("Jaccard Similarity: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(var(logit.base.roc)),3), sep=""), 
                                paste("Jaccard + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.covars.roc)),3), sep=""),
                                paste("Jaccard + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("All Social or Familial Relationships")

```

Bray-Curtis Similarity

```{r}
#Test out of sample
#Average over 5 CVs
for(i in 1:5){
  inds <- c(1:nrow(Downsamp_all))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]

  train1 <- Downsamp_all[train1_inds,]
  test1 <- Downsamp_all[test1_inds,]
  train2 <- Downsamp_all[train2_inds,]
  test2 <- Downsamp_all[test2_inds,]
  train3 <- Downsamp_all[train3_inds,]
  test3 <- Downsamp_all[test3_inds,]
  
  logit.test.1 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  if(i == 1){
    pred.all <- preds.round
    pred.all.covars <- preds.round.covars
    pred.all.all <- preds.round.all
  }
  else{
    pred.all <- pred.all + preds.round
    pred.all.covars <- pred.all.covars + preds.round.covars
    pred.all.all <- pred.all.all + preds.round.all
  }
  
}
#Could make this without random effect don't have to deal with this stuff
pred.all <- pred.all/5
pred.all.covars <- pred.all.covars/5
pred.all.all <- pred.all.all/5

#add on predictions from strain-sharing only model
pred.all.acc <- pred.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all$predicted <- pred.all.acc

#Create ROC object weird it got worse, could do this over multiple downsamples as well
#I think my predictions will be fairly consistent
logit.base.roc <- pROC::roc(Downsamp_all$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

pROC::auc(logit.base.roc)[1]
pROC::auc(logit.covars.roc)[1]
pROC::auc(logit.all.roc)[1]


roc.list <- list("Bray-Curtis Similarity" = logit.base.roc,
                 "BC + Age + Gender" = logit.covars.roc,
                 "BC + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot.bc <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
  coord_equal()

for(i in 1:3) {
  roc.plot.bc <- roc.plot.bc + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot.bc <- roc.plot.bc + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", "Green", "Blue"), 
                       labels=c(paste("Bray-Curtis Similarity: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(var(logit.base.roc)),3), sep=""), 
                                paste("BC + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.covars.roc)),3), sep=""),
                                paste("BC + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("All Social or Familial Relationships")

```




Jaccard Similarity non-kin dif-house
```{r}
#Test out of sample
#Average over 5 CVs
for(i in 1:5){
  inds <- c(1:nrow(Downsamp_all_nkh))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all_nkh)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]

  train1 <- Downsamp_all_nkh[train1_inds,]
  test1 <- Downsamp_all_nkh[test1_inds,]
  train2 <- Downsamp_all_nkh[train2_inds,]
  test2 <- Downsamp_all_nkh[test2_inds,]
  train3 <- Downsamp_all_nkh[train3_inds,]
  test3 <- Downsamp_all_nkh[test3_inds,]
  
  logit.test.1 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ jaccard_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        jaccard_sim + (0+jaccard_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  if(i == 1){
    pred.all <- preds.round
    pred.all.covars <- preds.round.covars
    pred.all.all <- preds.round.all
  }
  else{
    pred.all <- pred.all + preds.round
    pred.all.covars <- pred.all.covars + preds.round.covars
    pred.all.all <- pred.all.all + preds.round.all
  }
  
}
#Could make this without random effect don't have to deal with this stuff
pred.all <- pred.all/5
pred.all.covars <- pred.all.covars/5
pred.all.all <- pred.all.all/5

#add on predictions from strain-sharing only model
pred.all.acc <- pred.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all_nkh$predicted <- pred.all.acc

#Create ROC object weird it got worse, could do this over multiple downsamples as well
#I think my predictions will be fairly consistent
logit.base.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

pROC::auc(logit.base.roc)[1]
pROC::auc(logit.covars.roc)[1]
pROC::auc(logit.all.roc)[1]


roc.list <- list("Jaccard Similarity" = logit.base.roc,
                 "Jaccard + Age + Gender" = logit.covars.roc,
                 "Jaccard + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot.j.nkh <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
  coord_equal()

for(i in 1:3) {
  roc.plot.j.nkh <- roc.plot.j.nkh + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot.j.nkh <- roc.plot.j.nkh + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", "Green", "Blue"), 
                       labels=c(paste("Jaccard Similarity: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(var(logit.base.roc)),3), sep=""), 
                                paste("Jaccard + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.covars.roc)),3), sep=""),
                                paste("Jaccard + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("Non-Kin Different House Relationships")

```

Bray-Curtis Similarity non kin house

```{r}
#Test out of sample
#Average over 5 CVs
for(i in 1:5){
  inds <- c(1:nrow(Downsamp_all_nkh))
  test1_inds <- sample(inds, size = floor(.33*nrow(Downsamp_all_nkh)), replace = F)
  train1_inds <- inds[!(inds %in% test1_inds)]
  test2_inds <- sample(train1_inds, size = floor(.5*length(train1_inds)), replace = F)
  train2_inds <- inds[!(inds %in% test2_inds)]
  test3_inds <- train2_inds[!(train2_inds %in% test1_inds)]
  train3_inds <- inds[!(inds %in% test3_inds)]

  train1 <- Downsamp_all_nkh[train1_inds,]
  test1 <- Downsamp_all_nkh[test1_inds,]
  train2 <- Downsamp_all_nkh[train2_inds,]
  test2 <- Downsamp_all_nkh[test2_inds,]
  train3 <- Downsamp_all_nkh[train3_inds,]
  test3 <- Downsamp_all_nkh[test3_inds,]
  
  logit.test.1 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3 <- lme4::glmer(related ~ bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  preds.1 <- predict(logit.test.1, newdata = test1, type = "response")
  preds.2 <- predict(logit.test.2, newdata = test2, type = "response")
  preds.3 <- predict(logit.test.3, newdata = test3, type = "response")
  names(preds.3) <- test3_inds
  names(preds.2) <- test2_inds
  names(preds.1) <- test1_inds
  preds.round <- c(preds.1, preds.2, preds.3)
  preds.round <- preds.round[order(as.numeric(names(preds.round)))]
  
  logit.test.1.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.covars <- lme4::glmer(related ~ bray_curtis_sim + gender.mm + gender.mf +
                        age_difference_abs + average_age + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.covars <- predict(logit.test.1.covars, newdata = test1, type = "response")
  preds.2.covars <- predict(logit.test.2.covars, newdata = test2, type = "response")
  preds.3.covars <- predict(logit.test.3.covars, newdata = test3, type = "response")
  names(preds.3.covars) <- test3_inds
  names(preds.2.covars) <- test2_inds
  names(preds.1.covars) <- test1_inds
  preds.round.covars <- c(preds.1.covars, preds.2.covars, preds.3.covars)
  preds.round.covars <- preds.round.covars[order(as.numeric(names(preds.round.covars)))]
  
  logit.test.1.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train1, family = binomial)
  logit.test.2.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train2, family = binomial)
  logit.test.3.all <- lme4::glmer(related ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education +
                        bray_curtis_sim + (0+bray_curtis_sim|village_name_w3),
                              data = train3, family = binomial)
  
  preds.1.all <- predict(logit.test.1.all, newdata = test1, type = "response")
  preds.2.all <- predict(logit.test.2.all, newdata = test2, type = "response")
  preds.3.all <- predict(logit.test.3.all, newdata = test3, type = "response")
  names(preds.3.all) <- test3_inds
  names(preds.2.all) <- test2_inds
  names(preds.1.all) <- test1_inds
  preds.round.all <- c(preds.1.all, preds.2.all, preds.3.all)
  preds.round.all <- preds.round.all[order(as.numeric(names(preds.round.all)))]
  
  if(i == 1){
    pred.all <- preds.round
    pred.all.covars <- preds.round.covars
    pred.all.all <- preds.round.all
  }
  else{
    pred.all <- pred.all + preds.round
    pred.all.covars <- pred.all.covars + preds.round.covars
    pred.all.all <- pred.all.all + preds.round.all
  }
  
}
#Could make this without random effect don't have to deal with this stuff
pred.all <- pred.all/5
pred.all.covars <- pred.all.covars/5
pred.all.all <- pred.all.all/5

#add on predictions from strain-sharing only model
pred.all.acc <- pred.all
pred.all.acc[pred.all.acc >=.5] <- 1
pred.all.acc[pred.all.acc <.5] <- 0

Downsamp_all_nkh$predicted <- pred.all.acc

#Create ROC object weird it got worse, could do this over multiple downsamples as well
#I think my predictions will be fairly consistent
logit.base.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.covars.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.covars, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

logit.all.roc <- pROC::roc(Downsamp_all_nkh$related, pred.all.all, ci=TRUE, plot=FALSE,
                levels=c("0","1"), direction = "<")

pROC::auc(logit.base.roc)[1]
pROC::auc(logit.covars.roc)[1]
pROC::auc(logit.all.roc)[1]


roc.list <- list("Bray-Curtis Similarity" = logit.base.roc,
                 "BC + Age + Gender" = logit.covars.roc,
                 "BC + All Socio-Dem Covars" = logit.all.roc)

ci.list <- lapply(roc.list, ci.se, specificities = seq(0, 1, l = 25))

dat.ci.list <- lapply(ci.list, function(ciobj) 
  data.frame(x = as.numeric(rownames(ciobj)),
             lower = ciobj[, 1],
             upper = ciobj[, 3]))

roc.plot.bc.nkh <- ggroc(roc.list) +
  theme_minimal() +
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
  coord_equal()

for(i in 1:3) {
  roc.plot.bc.nkh <- roc.plot.bc.nkh + geom_ribbon(
    data = dat.ci.list[[i]],
    aes(x = x, ymin = lower, ymax = upper),
    fill = i + 1,
    alpha = 0.2,
    inherit.aes = F) 
  } 

roc.plot.bc.nkh <- roc.plot.bc.nkh + 
theme(plot.title = element_text(size=10, hjust = .5),
      legend.position = c(0.6, 0.2),
      legend.text = element_text(size=10),
      text = element_text(size = 10)) + 
      scale_color_manual(name = "AUCs:",
                         values=c("Red", "Green", "Blue"), 
                       labels=c(paste("Bray-Curtis Similarity: ", round(logit.base.roc$auc,2),
                                      " ± ",round(sqrt(var(logit.base.roc)),3), sep=""), 
                                paste("BC + Age + Gender: ", round(logit.covars.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.covars.roc)),3), sep=""),
                                paste("BC + All Socio-Dem Covars: ", round(logit.all.roc$auc, 2),
                                      " ± ",round(sqrt(var(logit.all.roc)),3), sep="")
                                )
                       ) +
  ggtitle("Non-Kin Different House Relationships")



```

Plots
```{r}

rocs_1 <-ggarrange(roc.plot.bc, roc.plot.bc.nkh, nrow = 1, labels = c("A", "B"))
rocs_2 <-ggarrange(roc.plot.j, roc.plot.j.nkh, nrow = 1, labels = c("C", "D"))

svglite("../FiguresNew/SFigure8/sfigure8_full.svg")
ggarrange(rocs_1,
          rocs_2,
          ncol = 1)
dev.off()

```


