---
title: "Longitudinal Analysis"
author: "Francesco Beghini"
date: "2023-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, warning = FALSE, message = FALSE, cache.lazy = FALSE)
library(stringi)
library(stringr)
library(dplyr)
library(readr)
library(igraph)
library(doParallel)
library(foreach)
library(ggplot2)
library(tidyr)
library(lmerTest)
library(lme4)
```

```{r load_metadata_microbiome, message=FALSE, warning=FALSE}
metadata_followup <- read_csv('~/F_BEGHINI_HM/COHORT1_FOLLOWUP/v2/hmb_respondents_cohort1_followup_v2_f_beghini_2022-11-08.csv', na = c('NA','Dont_Know','Refused'),show_col_types = FALSE) |> 
  mutate(mb_m05 = str_replace(mb_m00, '-00$', '-15'),
  marital_name = if_else(!is.na(mb_c004),mb_c004, 'Married')) |> 
  filter(!is.na(mb_m05)) |> 
  mutate(BMI = (mb_d0100 / mb_d0200 **2) * 10000)

metadata_baseline <- read_csv('~/F_BEGHINI_HM/COHORT1/v3/hmb_respondents_cohort1_baseline_v3_f_beghini_2022-11-08.csv', na = c('NA','Dont_Know','Refused'),show_col_types = FALSE) |> 
  filter(respondent_master_id %in% metadata_followup$respondent_master_id,
         !is.na(mb_m05)) |> 
    mutate(BMI = (mb_d0100 / mb_d0200 **2) * 10000)


species_data_longitudinal <-  readr::read_tsv("~/F_BEGHINI_HM/mpa_test_merged_profiles.tsv", skip = 1) |> 
  filter(stringr::str_detect(clade_name, 't__')) |>
  tibble::column_to_rownames('clade_name') 

subset_samples_fw <- data.frame(sample_id = colnames(species_data_longitudinal)) |> 
  separate_wider_delim(cols = sample_id, delim = '-',names =c('village','subject','timepoint'), cols_remove = FALSE) |> 
  group_by(village, subject) |> 
  filter(n() > 1) |> 
  arrange(sample_id)

master_key_fw <- bind_rows(metadata_baseline,metadata_followup) |> dplyr::select(mb_m05, respondent_master_id, village_code) |> tibble::column_to_rownames('mb_m05')
```

```{r load_social_network_waves, message=FALSE, warning=FALSE}
SN_w1 <- read_csv("~/F_BEGHINI_G/WAVE1/v8/honduras_connections_WAVE1_v8_F_BEGHINI_2023-11-01.csv",show_col_types = FALSE) |> 
              filter(relationship %in% c('child_over12_other_house','closest_friend','father','free_time','mother','partner','personal_private','sibling') #Remove not get along
                     ) |>
              mutate(pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), ''),
                     wave = 1)

reduced_SN_w1 <- SN_w1 |> 
  group_by(pair) |> 
  summarize(ego, alter, relationship = paste(relationship, collapse = ','), across(starts_with('a2703'), ~ paste(unique(.x[!is.na(.x)]), collapse = ',')) , village_name_w1, village_code_w1) |> 
  distinct(pair, .keep_all = TRUE) |> 
  mutate(is_kin = grepl('mother|father|child|sibling', relationship)) |> 
  dplyr::select(ego, alter, everything()) |> 
  ungroup()

SN_w3 <- read_csv("~/F_BEGHINI_G/WAVE3/v3/honduras_connections_WAVE3_v3_F_BEGHINI_2021-09-27.csv", guess_max = 50000,show_col_types = FALSE) |> 
              filter(relationship %in% c('child_over12_other_house','closest_friend','father','free_time','mother','partner','personal_private','sibling'), #Remove not get along
                     ego %in% metadata_followup$respondent_master_id, 
                     alter %in% metadata_followup$respondent_master_id,
                     ego %in% metadata_baseline$respondent_master_id, 
                     alter %in% metadata_baseline$respondent_master_id
                     ) |> 
                mutate(pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), ''),
                       wave = 3)

SN_w4 <- read_csv("~/F_BEGHINI_G/WAVE4/v1/honduras_connections_WAVE4_v1_F_BEGHINI_2023-11-01.csv", guess_max = 50000,show_col_types = FALSE) |> 
              filter(relationship %in% c('child_over12_other_house','closest_friend','father','free_time','mother','partner','personal_private','sibling'), #Remove not get along
                     ego %in% metadata_followup$respondent_master_id, 
                     alter %in% metadata_followup$respondent_master_id) |> 
                mutate(pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), ''),
                       wave = 4)
respondents_w4 <- read_csv('~/F_BEGHINI_G/WAVE4/v1/honduras_respondents_WAVE4_v1_F_BEGHINI_2023-11-01.csv', guess_max = 50000,show_col_types = FALSE) |> 
              filter(respondent_master_id %in% metadata_followup$respondent_master_id)
```

```{r collapse_multiple_ties}
reduced_SN_w3 <- SN_w3 |> 
  unite(a2703a, a2703a, a2704a, na.rm = TRUE,) |> 
  unite(a2703b, a2703b, a2704b, na.rm = TRUE,) |> 
  unite(a2703c, a2703c, a2704c, na.rm = TRUE,) |> 
  unite(a2703d, a2703d, a2704d, na.rm = TRUE,) |> 
  unite(a2703e, a2703e, a2704e, na.rm = TRUE,) |> 
  unite(a2703f, a2703f, a2704f, na.rm = TRUE,) |> 
  unite(a2703g, a2703g, a2704g, na.rm = TRUE,) |> 
  mutate(across(starts_with('a2703'), ~ na_if(.x, ''))) |> 
  select(-a2703, -a2704, -question,-a2703h, -alter_source, -office_w3, -municipality_w3) |> 
  group_by(pair) |> 
  summarize(ego, alter, relationship = paste(relationship, collapse = ','), across(starts_with('a2703'), ~ paste(unique(.x[!is.na(.x)]), collapse = ',')) , village_name_w3, village_code_w3) |> 
  distinct(pair, .keep_all = TRUE) |> 
  mutate(is_kin = grepl('mother|father|child|sibling', relationship)) |> 
  select(ego, alter, everything()) |> 
  ungroup()

SN_w3_graph <- graph_from_data_frame((reduced_SN_w3 |> select(-village_name_w3, -village_code_w3)), 
                                     directed = FALSE, 
                                     vertices = (reduced_SN_w3 |> 
                                                   select(ego, alter, starts_with('village')) |> 
                                                   pivot_longer(cols = c(-village_name_w3, -village_code_w3), names_to = 'a', values_to = 'vertex') |> 
                                                   select(vertex, starts_with('village')) |> 
                                                   distinct()
                                                 )
                                     )

SN_w1_graph <- graph_from_data_frame((reduced_SN_w1 |> select(-village_code_w1, -village_name_w1)),
                                     directed = FALSE,
                                     vertices = (reduced_SN_w1 |> 
      select(ego, alter, starts_with('village')) |> 
                                                   pivot_longer(cols = c(-village_name_w1, -village_code_w1), names_to = 'a', values_to = 'vertex') |> 
                                                   select(vertex, starts_with('village')) |> 
                                                   distinct()
                                                 )
                                     )

```


```{r load_strainphlan_data, cache=FALSE}
species_per_sample <- readRDS('~/species_per_sample_acc') |>
inner_join(subset_samples_fw, by=join_by('sample' == 'sample_id')) |>
distinct(species, village, subject, .keep_all = TRUE) |>
count(species) |>
filter(n > 10)

kk <- combn(as.list(readRDS('~/species_per_sample_acc') |> mutate(present=TRUE) %>%
     pivot_wider(names_from=sample, values_from=present, values_fill=list(present=FALSE)) |> select(-species)),2, simplify = FALSE)

comb_names <- readRDS('~/species_per_sample_acc') |> 
  mutate(present=TRUE) |> 
  pivot_wider(names_from=sample, values_from=present, values_fill=list(present=FALSE)) |> 
  select(-species) |> 
  colnames() |> 
  combn(2, simplify = FALSE, FUN=function(x) paste0(sort(x), collapse='='))

shared_sgbs <- lapply(kk, function(x) sum(x[[1]]&x[[2]]))
shared_sgbs <- setNames(shared_sgbs, comb_names)

strain_shared_raw <- readRDS('/SCRATCH/tmp/shared.RDS')
strain_shared <- strain_shared_raw |> 
    filter(s1 %in% subset_samples_fw$sample_id & s2 %in% subset_samples_fw$sample_id ,
    species %in% species_per_sample$species) |> 
    mutate(ego = master_key_fw[s1, 'respondent_master_id' ],
         alter = master_key_fw[s2, 'respondent_master_id'],
         pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), ''),
         timepoint = case_when( 
           str_sub(s1,10)=='05' & str_sub(s2,10) == '05' ~ 'T1',
           str_sub(s1,10)=='15' & str_sub(s2,10) == '15' ~ 'T2',
           str_sub(s1,10)=='05' & str_sub(s2,10) == '15' ~ 'T1/T2',
           str_sub(s1,10)=='15' & str_sub(s2,10) == '05' ~ 'T2/T1',
           ),
          village_code_ego = master_key_fw[s1, 'village_code'],
         village_code_alter = master_key_fw[s2, 'village_code']
         ) |> 
    left_join((
    SN_w3 |> 
      select(pair, relationship) |> 
      distinct(pair, .keep_all = TRUE) |> 
      mutate(tie = 'yes')
    ), by = join_by(pair)) |> 
  mutate(tie = replace_na(tie, 'none'),
         relationship = replace_na(relationship, 'none'))

sharing_rate <- strain_shared_raw |>
  mutate(timepoint = case_when( 
           str_sub(s1,10)=='05' & str_sub(s2,10) == '05' ~ 'T1',
           str_sub(s1,10)=='15' & str_sub(s2,10) == '15' ~ 'T2',
           str_sub(s1,10)=='05' & str_sub(s2,10) == '15' ~ 'T1/T2',
           str_sub(s1,10)=='15' & str_sub(s2,10) == '05' ~ 'T2/T1',
           )) |>
  filter(timepoint %in% c('T1','T2')) |>
  group_by(pair, timepoint) |>  
  mutate(n=sum(shared)) |>
  ungroup() |>
  distinct(pair, n, timepoint) |>
  left_join(data.frame(pair=names(shared_sgbs), shared_sgbs=as.numeric(shared_sgbs))) |> 
  mutate( n1 = n/shared_sgbs) |> 
  mutate( n1 = case_when(shared_sgbs < 10 ~ NA, .default = n1))

# readRDS('/SCRATCH/tmp/sharing_rate_with_zero_long_with_followup.RDS') |> 
  # separate_wider_delim(pair, "=", names = c('s1','s2'))

sharing_rate <- sharing_rate |> 
    separate_wider_delim(pair, "=", names = c('s1','s2')) |>
  filter(s1 %in% subset_samples_fw$sample_id & s2 %in% subset_samples_fw$sample_id) |> 
  mutate(ego = master_key_fw[s1, 'respondent_master_id' ],
         alter = master_key_fw[s2, 'respondent_master_id'],
           pair = vapply(stri_split_boundaries(str_c(ego, alter), type='character'), function(x) stri_c(x[stri_order(x)], collapse = ''), ''),
         same_subject = str_sub(s1,1,8) == str_sub(s2,1,8),
         village_code_ego = master_key_fw[s1, 'village_code'],
         village_code_alter = master_key_fw[s2, 'village_code']
  )|> 
  left_join((
    SN_w3 |> 
      select(pair, relationship) |> 
      distinct(pair, .keep_all = TRUE) |> 
      mutate(tie = 'yes')
    ), by = join_by(pair)) |> 
  mutate(tie = replace_na(tie, 'none'),
         relationship = replace_na(relationship, 'none'),
         n1 = replace_na(n1, 0))
  

sharing_rate_T1_w3 <- sharing_rate |> 
  filter(timepoint=='T1') |> 
  left_join(SN_w3, by = join_by(pair, alter, ego))

sharing_rate_T2_w3 <- sharing_rate |> 
  filter(timepoint=='T2') |> 
  left_join(SN_w3, by = join_by(pair, alter, ego))

sharing_rate_inter <- sharing_rate |> 
  filter(timepoint=='T1/T2')
```

# Calculate SSR only on shared species between timepoints
```{r}
strain_shared |> 
  filter(timepoint %in% c('T1','T2')) |> 
  group_by(pair, timepoint) |> 
  summarize(l = list(unique(species))) |> 
  ungroup(timepoint) -> xx
  
xx
summarize(length(.[,timepoint=='T1',l]))
```


```{r edge_change_t1_t2, cache=FALSE}
cluster <- multidplyr::new_cluster(20)
multidplyr::cluster_library(cluster, "dplyr")
status_sharing_w3 <- strain_shared |> 
  filter(same_timepoint==TRUE) |> 
  select(s1,s2, pair, dist, species, timepoint, relationship=relationship.x, shared ) |> 
  distinct(pair, species, relationship, timepoint, .keep_all = TRUE) |> 
  arrange(species, timepoint) |> 
  group_by(pair, species, relationship) |> 
  multidplyr::partition(cluster) |> 
  summarise(status = dplyr::case_when(
    n() == 1 & timepoint=='T1' & shared == TRUE ~ 'sharing_lost_at_t2',
    n() == 1 & timepoint=='T2' & shared == TRUE ~ 'sharing_acquired_only_at_t2',
    n() == 2 & shared == TRUE                   ~ 'kept_sharing',
    .default = 'no_share'
  )) |> 
  collect()
```
```{r include=FALSE}
strain_shared |> 
  filter(same_subject==TRUE) |> 
  mutate(trans = dist <= threshold) |> 
  mutate(timepoint = 'Intra-timepoint') |>
  group_by(pair, timepoint, village_code_w3) |>  
  summarize(ssr=sum(trans==TRUE)/n()) |> 
  ggplot() + 
    geom_boxplot(aes(village_code_w3, ssr))
    #ggbeeswarm::geom_quasirandom(aes(timepoint, ssr))
```


```{r eval=FALSE, include=FALSE}
status_sharing_w3 |> 
  distinct() |> 
  filter(!is.na(relationship)) |> 
  ggplot(aes(relationship, fill=status)) +
  geom_bar(position="stack", stat="count")
```

```{r eval=FALSE, include=FALSE}
status_sharing_w3 |> 
  sample_n(100)
  distinct() |> 
  filter(!is.na(relationship)) |> 
  pivot_wider(-status)
  group_by(pair) |> 
  summarize()
```
```{r eval=FALSE, include=FALSE}
cols = c('T1'=NA,'T2'=NA,'T1/T2'=NA,'T2/T1'=NA)
all_pairs <- foreach(ego_l = c(SN_w3$ego, SN_w3$alter), .combine = 'rbind') %do% {
  ego_n = make_ego_graph(SN_w3_graph, nodes = ego_l, mindist = 0)[[1]]
  foreach(alter_l = setdiff(names(V(ego_n)), ego_l), .combine = 'rbind') %do%{
    pair_l = stri_c(stri_sort(stri_split_boundaries(str_c(ego_l, alter_l), type='character')[[1]]), collapse = '')
    c(pair_l, ego_l, alter_l)
  } 
}
colnames(all_pairs) = c('pairs','ego','alter')
all_pairs <- as.data.frame(all_pairs) |> 
  distinct(pairs, .keep_all = TRUE)

cl <- parallel::makeForkCluster(12)
doParallel::registerDoParallel(cl)

longitudinal_ds <- foreach(row = rownames(all_pairs), .combine = 'rbind') %dopar% {
  pair_l = all_pairs[row,'pairs']
  ego_l = all_pairs[row,'ego']
  alter_l = all_pairs[row,'alter']
  ego_kept_strain_overtime = strain_shared |> filter(ego==ego_l&alter==ego_l) |> select(-same_village,-threshold)
  alter_kept_strain_overtime = strain_shared |> filter(ego==alter_l & alter==alter_l) |> select(-same_village,-threshold)
    tmp <- strain_shared |> filter(pair == pair_l) |> 
      pivot_wider(id_cols = everything(), names_from = timepoint, values_from = shared)
    
     tmp <- tibble::add_column(tmp, !!!cols[setdiff(names(cols),names(tmp))]) |> 
      group_by(pair, species) |>
      summarise(T1 = sum(T1, na.rm = TRUE), 
                T2 = sum(T2, na.rm = TRUE),
                `T1/T2` = sum(`T1/T2`, na.rm = TRUE),
                `T2/T1` = sum(`T2/T1`, na.rm = TRUE)
                ) |> 
      arrange(species) |> 
      left_join(ego_kept_strain_overtime |> filter(ego == ego_l) |> select(species, ego_kept=shared), by=join_by(species)) |> 
      left_join(alter_kept_strain_overtime |> filter(alter == alter_l) |> select(species, alter_kept=shared), by=join_by(species)) |> 
      mutate(across(where(is.logical), ~ if_else(is.na(.x), 0, as.integer(.x)))) |> 
       ungroup()

     tmp
  
}
parallel::stopCluster(cl)
```

```{r eval=FALSE, include=FALSE}
longitudinal_ds |> 
  ungroup() |> 
  mutate(trans_only_t1 = as.integer(T1==1 & rowSums(across(starts_with('T')))==1 & rowSums(across(contains('_kept'))) == 0),
         trans_only_t2 = as.integer(T2==1 & rowSums(across(starts_with('T')))==1 & rowSums(across(contains('_kept'))) == 0),
         retained = as.integer(T1 == 1 & T2 == 1 & rowSums(across(contains('_kept'))) == 2 & rowSums(across(contains('/'))) ==2 )
         ) |> 
  group_by(pair) |> 
  summarize(srr = sum(retained) / n(),
            ssr_t1 = sum(T1) / n(),
            ssr_t2 = sum(T2) / n()) |> 
  left_join(SN_w3, by=join_by(pair)) |> 
  select(pair, relationship, srr, ssr_t1, ssr_t2) |> 
  pivot_longer(cols = 3:5, names_to = 'rate', values_to = 'value') |> 
  ggplot() +
  geom_boxplot(aes(relationship, value, fill=rate))
```


```{r}

ak <- inner_join(metadata_baseline, demographics2, by="respondent_master_id")
ak |> 
  filter(respondent_master_id %in% xxx[which(!xxx %in% pairwise_mahalanomis_long$s1)]) |> 
    unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |> 
  dplyr::select(respondent_master_id,
                building_id,
                BMI, 
                gender = gender.x,
                indigenous_status, 
                age_at_survey = age_at_survey.x,
                religion = b0600,
                education = b0100,
                status_mb,
                status_w3
                ) |> 
  left_join(household_wealth_data, by = join_by('building_id'))
  
```


```{r}
demographics <- read_csv("/WORKAREA/work/HONDURAS_MICROBIOME/J_PULLMAN/DATA/COHORT_1/v2/honduras_respondents_demographics_J_PULLMAN_2022-11-07.csv")
demographics2 <- read_csv("~/F_BEGHINI_G/WAVE3/v3/honduras_respondents_WAVE3_v3_F_BEGHINI_2023-10-23.csv")


household_wealth_data2 <- read.csv("~/F_BEGHINI_G/WAVE3/v3/honduras_households_WAVE2_v5_F_BEGHINI_2022-11-01.csv") |> 
  dplyr::select(building_id, l0400, household_wealth_index_w2)

household_wealth_data1 <- read.csv("~/F_BEGHINI_G/WAVE3/v3/honduras_households_WAVE1_v8_F_BEGHINI_2022-11-01.csv") |> 
  dplyr::select(building_id, l0400)

household_wealth_data <- read.csv("~/F_BEGHINI_G/WAVE3/v3/honduras_households_WAVE3_v3_F_BEGHINI_2023_10-23.csv") |> 
              dplyr::select(building_id, household_id, l0400, household_wealth_index_w3)

covariates <- inner_join(metadata_baseline, demographics, by="respondent_master_id") |> 
  left_join(household_wealth_data, by= join_by('building_id')) |> 
  mutate(across(starts_with('mb_ca'), ~ case_when(as.integer(factor(.x)) / 3 == 1 ~ 1, .default = 0  ))) |>
  mutate(dds_Cereals = as.integer(mb_ca0200|mb_ca0300|mb_ca0400),
         dds_Vegetables = mb_ca1000,
         dds_Fruits = as.integer(mb_ca1100|mb_ca1200),
         dds_Meat_poultry_offal = as.integer(mb_ca1300 |mb_ca1400),
         dds_Eggs = mb_ca0900,
         dds_Fish_seafood = mb_ca1600,
         dds_Legumes = mb_ca0100,
         dds_Dairy = as.integer(mb_ca0500 | mb_ca0600 | mb_ca0700 | mb_ca0800),
         dds_Fats = as.integer(mb_ca1500 | mb_ca1900),
         dds_Sugar = as.integer(mb_ca1700 | mb_ca1800),
         DDS = rowSums(across(starts_with('dds_')))
  )
sub_covar <- covariates |> 
  filter(respondent_master_id %in% metadata_followup$respondent_master_id) |> 
  unite('indigenous_status', mb_a0500a:mb_a0500i, na.rm = TRUE) |> 
  dplyr::select(respondent_master_id,
                building_id,
                BMI, 
                gender = gender.x,
                indigenous_status, 
                age_at_survey = age_at_survey.x, 
                DDS, 
                household_wealth_index_w3,
                religion = b0600,
                education = b0100,
                ) |> 
    mutate(education = recode(education, "Have not completed any type of school" = 0,
                                "1st grade" = 1, "2nd grade" = 2, "3rd grade" = 3,
                                "4th grade" = 4, "5th grade" = 5, "6th grade" = 6,
                                "Some secondary" = 7, "Secondary" = 8, "More than secondary" = 9),
           religion = recode(religion, "Catholic" = 1, "No Religion" = 0, "Protestant" =2 ),
           building_id = as.numeric(factor(building_id))
      )

sub_covar[sub_covar$respondent_master_id=='145q-7f4867c7-a4e1-47e8-9b7c-2d98a4294cdb','household_wealth_index_w3'] <- 5
sub_covar[sub_covar$respondent_master_id=='nZno-6b2d0c05-ebeb-464b-836e-31493a161740','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='cPP0-b47b9cbf-eeaf-430a-87bf-d6322e65108b','household_wealth_index_w3'] <- 2
sub_covar[sub_covar$respondent_master_id=='nZno-b1e42724-5fd4-4aad-8835-80e8a7f430bf','household_wealth_index_w3'] <- 2
sub_covar[sub_covar$respondent_master_id=='enz0-ce7dad59-da03-48d6-9649-40202eba50aa','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='enz0-54c4a166-642d-4707-9dd9-eac58c3452b0','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='cPP0-e7a61fe3-ea87-4f76-b992-bbfbde75393c','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='h4Ru-14c55d32-c61c-44da-9088-6559224a1ae9','household_wealth_index_w3'] <- 3
sub_covar[sub_covar$respondent_master_id=='nZno-66d3906b-0036-4943-bfbb-f5aabaa16123','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='cPP0-00ea6c4f-769a-4670-b7af-cc82af90a235','household_wealth_index_w3'] <- 4
sub_covar[sub_covar$respondent_master_id=='nZno-50e96e07-ae0e-4be2-a0f3-d45a3308204f','household_wealth_index_w3'] <- 2
sub_covar[sub_covar$respondent_master_id=='Obit-d4607866-a62f-4c9a-90b0-0b11db77f970','household_wealth_index_w3'] <- 3
sub_covar[sub_covar$respondent_master_id=='/BKO-5f5c3998-40ad-45fa-8430-244a6863c01d','household_wealth_index_w3'] <- 3
sub_covar[sub_covar$respondent_master_id=='Ers1-ae8fb0f9-6d87-476c-a9aa-b3c648e35c6a','household_wealth_index_w3'] <- 5
sub_covar[sub_covar$respondent_master_id=='enz0-0d3f9285-2398-47e6-aca2-ada2c6a8fc09','household_wealth_index_w3'] <- 3
sub_covar[sub_covar$respondent_master_id=='CfVZ-39bb93a1-bbc7-4dad-a261-c3eb047bfe12','household_wealth_index_w3'] <- 1

sub_covar[sub_covar$indigenous_status == '','indigenous_status'] = 'None of the above'
sub_covar$indigenous_status <- ifelse(sub_covar$indigenous_status=='None of the above', 0, 1)
sub_covar$genderm <- ifelse(sub_covar$gender == 'man', 1, 0)

sub_covar_mat <- sub_covar |> 
  select(-gender) |> 
  tibble::column_to_rownames('respondent_master_id')
pairwise_mahalanomis <- biotools::D2.dist(sub_covar_mat, cov = cov(sub_covar_mat, use='complete'))
pairwise_mahalanomis |> 
  as.matrix() |> as.data.frame() |>
  tibble::rownames_to_column('s1') |>
  pivot_longer(-s1, names_to = 's2', values_to = 'maha_dist') |> 
  rowwise() |> 
  mutate(pair = stri_c(stri_sort(stri_split_boundaries(str_c(s1, s2), type='character')[[1]]), collapse = '')) |> 
  distinct(pair, .keep_all = TRUE)-> pairwise_mahalanomis_long
```


```{r}
x <- strain_shared |> 
  filter(village_code_ego==village_code_alter,
         same_subject == FALSE,
         timepoint %in% c('T1','T2')) |> 
  dplyr::select(ego = ego, alter = alter, pair, relationship = relationship, timepoint, species, threshold, dist,village_code_ego) |> 
  distinct(pair, relationship, timepoint, species, .keep_all = TRUE) |> 
  mutate(relationship = replace_na(relationship, 'none')) |> 
  pivot_wider(names_from = 'timepoint', values_from = 'dist') |> 
  filter(!is.na(T1),
         !is.na(T2))
  # mutate(across(starts_with('T'), ~ replace_na(.x, 0))
         # )

# intra_distances <- strain_shared |> 
#   filter(same_subject==TRUE) |> 
#   mutate(timepoint ='intra') |> 
#   pivot_wider(names_from = 'timepoint', values_from = 'dist') |> 
#   dplyr::select(respondent_master_id=ego.x, species, intra) 

xcov <- merge(merge(x, sub_covar, by.x = "ego", by.y = 'respondent_master_id', ), sub_covar, by.x = 'alter', by.y = 'respondent_master_id', suffixes = c('_ego','_alter'))

# xcov <- merge(merge(xcov, intra_distances, by.x = c("ego",'species'), by.y = c('respondent_master_id','species'), all.x = TRUE), intra_distances, by.x =c('alter', 'species'), by.y =c('respondent_master_id', 'species'), suffixes = c('_ego','_alter'), all.x=TRUE)

# xcov$intra_alter[is.na(xcov$intra_alter)] <- 0
# xcov$intra_ego[is.na(xcov$intra_ego)] <- 0

xcov$gender.mm <- xcov$gender_ego == "man" & xcov$gender_alter == "man"
xcov$gender.mf <- xcov$gender_ego == "man" & xcov$gender_alter == "woman" | xcov$gender_ego == "woman" & xcov$gender_alter == "man"
xcov$gender.ff <- xcov$gender_ego == "woman" & xcov$gender_alter == "woman"
xcov$indigenous.both <- xcov$indigenous_status_ego != 0 & xcov$indigenous_status_alter != 0
xcov$indigenous.one <- xcov$indigenous_status_ego == 0 & xcov$indigenous_status_alter != 0 | xcov$indigenous_status_ego != 0 & xcov$indigenous_status_alter == 0
xcov$indigenous.none <- xcov$indigenous_status_ego == 0 & xcov$indigenous_status_alter == 0
xcov$age_difference_abs <- abs(xcov$age_at_survey_ego - xcov$age_at_survey_alter)
xcov$average_age <- (xcov$age_at_survey_ego + xcov$age_at_survey_alter)/2
xcov$wealth_difference_abs <- abs(xcov$household_wealth_index_w3_ego - xcov$household_wealth_index_w3_alter)
xcov$average_wealth <- (xcov$household_wealth_index_w3_ego + xcov$household_wealth_index_w3_alter)/2
xcov$DDS_difference_abs <- abs(xcov$DDS_ego - xcov$DDS_alter)
xcov$DDS_average <- (xcov$DDS_ego + xcov$DDS_alter)/2
xcov$education_difference_abs <- abs(xcov$education_ego - xcov$education_alter)
xcov$average_education <- (xcov$education_ego + xcov$education_alter)/2
xcov$religion_same <- xcov$religion_ego==xcov$religion_alter
xcov$building_same <- xcov$building_id_ego == xcov$building_id_alter

# colnames(xcov)[8] <- 'T2T1'
# colnames(xcov)[9] <- 'T1T2'

xcov$T1_t <- xcov$T1 < xcov$threshold
xcov$T2_t <- xcov$T2 < xcov$threshold
# xcov$T1T2_t <- xcov$T1T2 < xcov$threshold
# xcov$T2T1_t <- xcov$T2T1 < xcov$threshold
# xcov$intra_ego_t <- xcov$intra_ego < xcov$threshold
# xcov$intra_alter_t <- xcov$intra_alter < xcov$threshold

xcov$relationship <- ifelse(xcov$relationship == 'none', FALSE, TRUE)
xcov <- merge(xcov, pairwise_mahalanomis_long, by = 'pair')
```


# Mixed effect model
```{r eval=FALSE, include=FALSE}
# relationship + gender.mm + gender.ff + indigenous.both + indigenous.one + age_difference_abs + average_age + average_age + DDS_difference_abs 
#glmer(data = xcov, T2_t ~ T1_t*T2T1_t*T1T2_t*intra_ego_t*intra_alter_t + maha_dist + relationship + (1|species), family = binomial, nAGQ=0) -> lmer_species_rand
glmer(data = xcov, T2_t ~ T1_t*relationship + maha_dist + (1|species) + (1|village_code_ego) + (1|ego), family = binomial, nAGQ=0) -> lmer_species_rand
```

```{r}
summary(lmer_species_rand)
```

```{r}
 # relationship + gender.mm + gender.ff + indigenous.both + indigenous.one + age_difference_abs + average_age + average_age + DDS_difference_abs 
#glmer(data = xcov, T2_t ~ T1_t*relationship + maha_dist  + (1|village_code_w3_ego), family = binomial, nAGQ=0) -> lmer_species_rand
sharing_rate_only_followup <- sharing_rate |> 
  filter(village_code_ego == village_code_alter,
         same_subject==FALSE,
         timepoint != 'T1/T2') |> 
  group_by(pair) |> 
  filter(n()==2) |> 
  ungroup() |> 
  mutate(is_kin = grepl('mother|father|child|sibling', relationship)) |>
  select(pair, relationship=tie, timepoint, n1, is_kin, village_code_ego, ego, alter) |> 
  pivot_wider(names_from = timepoint, values_from = n1, values_fill = list(n1=0)) |> 
  left_join((pairwise_mahalanomis_long |> select(pair, maha_dist)), by = 'pair') |> 
  mutate(village_code_ego = as.factor(village_code_ego))
  
saveRDS(sharing_rate_only_followup, 'sharing_rate_only_followup.Rds')
```

```{r}
lmer_zero_model   <- lmer(T2 ~ T1 + relationship + (1|village_code_ego) + (1|ego), data = sharing_rate_only_followup)
lmer_first_model  <- lmer(T2 ~ T1 + relationship + maha_dist + (1|village_code_ego) + (1|ego), data = sharing_rate_only_followup)
lmer_second_model <- lmer(T2 ~ T1*relationship + maha_dist + (1|village_code_ego) + (1|ego), data = sharing_rate_only_followup)
lmer_third_model  <- lmer(T2 ~ T1 + relationship + relationship*maha_dist + maha_dist + (1|village_code_ego) + (1|ego), data = sharing_rate_only_followup)
lmer_thirdplus_model  <- lmer(T2 ~ T1*relationship*maha_dist + (1|village_code_ego) + (1|ego), data = sharing_rate_only_followup)
```


```{r}
summary(lmer_zero_model)
```

```{r}
summary(lmer_first_model)
```

```{r}
summary(lmer_second_model)
```

```{r}
summary(lmer_third_model)
```
```{r}
summary(lmer_thirdplus_model)
```

```{r}
dotplot_compare_models <- bind_rows(data.frame(summary(lmer_first_model)$coef[2:4,1:2], class = 'no_interact'), data.frame(class = 'interact', summary(lmer_second_model)$coef[2:4,1:2])) |>
  tibble::rownames_to_column('term') |>
  mutate(term = str_remove(term, '...[0-9]')) |>
  rename(SE = `Std..Error`) |>
  bind_rows(list(term='T1:relationshipyes', class='interact', Estimate = fixef(lmer_second_model)[[5]], SE = summary(lmer_second_model)$coef[5,2])) |>
  mutate(term = factor(term, levels = unique(term))) |>
  ggplot(aes(reorder(term, desc(term)), Estimate, group=class)) +
  geom_errorbar(aes(ymin=Estimate-SE, ymax=Estimate+SE, color = class),size = 1.5, width=.2, position = position_dodge(width = 0.4)) +
  geom_point(aes(color = class), size = 4, position = position_dodge(width = 0.4)) +
  coord_flip() +
  cowplot::theme_cowplot() + xlab('Terms') +
  scale_color_manual( values = c('orange', '#440154'))

dotplot_compare_models
```

```{r}
svglite('Figures/dotplot_compare_models.svg', fix_text_size = FALSE, bg='transparent')
dotplot_compare_models
dev.off()
```
```{r}

foreach(i = c(1:5)) %do% {
set.seed(1993)
xcov_inds <- c(1:nrow(xcov))
test_xcov1_inds <- sample(xcov_inds, size = floor(.33*nrow(xcov)), replace = F)
train_xcov1_inds <- xcov_inds[!(xcov_inds %in% test_xcov1_inds)]
test_xcov2_inds <- sample(train_xcov1_inds, size = floor(.5*length(train_xcov1_inds)), replace = F)
train_xcov2_inds <- xcov_inds[!(xcov_inds %in% test_xcov2_inds)]
test_xcov3_inds <- train_xcov2_inds[!(train_xcov2_inds %in% test_xcov1_inds)]
train_xcov3_inds <- xcov_inds[!(xcov_inds %in% test_xcov3_inds)]

test1_xcov <- xcov[test_xcov1_inds,]
train1_xcov <- xcov[train_xcov1_inds,]
test2_xcov <- xcov[test_xcov2_inds,]
train2_xcov <- xcov[train_xcov2_inds,]
test3_xcov <- xcov[test_xcov3_inds,]
train3_xcov <- xcov[train_xcov3_inds,]

cl2 <- parallel::makeCluster(3)

test_simple <- parLapply(cl=cl2,
                         list(train1_xcov, train2_xcov, train3_xcov), 
                        function(x) {glmmTMB::glmmTMB(data = x, T2_t ~ T1_t + (1|species) + (0+T1_t|village_code_w3_ego), family = binomial)}
)

preds_simple <- parLapply(cl2,
                          mapply(list, test_simple, list(test1_xcov, test2_xcov, test3_xcov),  SIMPLIFY=FALSE),
                          function(x) { 
                            m <- x[[1]]
                            test_set <- x[[2]] 
                            predict(m, test_set, type = "response", allow.new.levels = TRUE) 
                          }
)

names(preds_simple[[1]]) <- test_xcov1_inds
names(preds_simple[[2]]) <- test_xcov2_inds
names(preds_simple[[3]]) <- test_xcov3_inds
preds.simple <- unlist(preds_simple)
preds.simple <- preds.simple[order(as.numeric(names(preds.simple)))]


test_onlycovars <- parLapply(cl=cl2,
                         list(train1_xcov, train2_xcov, train3_xcov), 
                        function(x) {glmmTMB::glmmTMB(data = x, T2_t ~ T1_t + (1|species) + (0+T1_t|village_code_w3_ego), family = binomial)}
)

preds_onlycovars <- parLapply(cl2,
                          mapply(list, test_simple, list(test1_xcov, test2_xcov, test3_xcov),  SIMPLIFY=FALSE),
                          function(x) { 
                            m <- x[[1]]
                            test_set <- x[[2]] 
                            predict(m, test_set, type = "response", allow.new.levels = TRUE) 
                          }
)

names(preds_onlycovars[[1]]) <- test_xcov1_inds
names(preds_onlycovars[[2]]) <- test_xcov2_inds
names(preds_onlycovars[[3]]) <- test_xcov3_inds
preds.onlycovars <- unlist(preds_onlycovars)
preds.onlycovars <- preds.onlycovars[order(as.numeric(names(preds.simple)))]



test <- parLapply(cl2,
                  list(train1_xcov, train2_xcov, train3_xcov), 
                  function(x) {
                    glmmTMB::glmmTMB(data = x, 
                                     T2_t ~ T1_t*intra_ego_t*intra_alter_t + gender.mm + gender.ff + 
                                       religion_same + education_difference_abs + average_education + 
                                       indigenous.both + indigenous.one + 
                                       age_difference_abs + average_age + 
                                       wealth_difference_abs + average_wealth + 
                                       DDS_difference_abs + building_same + 
                                       relationship + (1|species) + (0+T1_t|village_code_w3_ego), 
                                     family = binomial
                                     )
                    }
                  )

preds <- parLapply(cl2,  
                          mapply(list, test, list(test1_xcov, test2_xcov, test3_xcov),  SIMPLIFY=FALSE),
                          function(x) { 
                            m <- x[[1]]
                            test_set <- x[[2]] 
                            predict(m, test_set, type = "response", allow.new.levels = TRUE) 
                          }
)

parallel::stopCluster(cl2)

names(preds[[1]]) <- test_xcov1_inds
names(preds[[2]]) <- test_xcov2_inds
names(preds[[3]]) <- test_xcov3_inds
preds.round <- unlist(preds)
preds.round <- preds.round[order(as.numeric(names(preds.round)))]

list(preds.simple, preds.round)
} -> preds


pred.all <- rowSums(sapply(preds, `[[`, 1))/5
pred.all.covars <- rowSums(sapply(preds, `[[`, 2))/5

#pred.all <- Reduce(`+`, preds)/5

roc_pred_simple <- pROC::roc(xcov$T2_t, pred.all, ci=TRUE, plot=TRUE, levels=c(FALSE, TRUE), direction = "<", na.rm=TRUE)
roc_pred <- pROC::roc(xcov$T2_t, pred.all.covars, ci=TRUE, plot=TRUE, levels=c(FALSE, TRUE), direction = "<", na.rm=TRUE)

ggroc(roc_pred)
```

```{r}
foreach(i = 1:4) %do% {
  v = unique(metadata_followup$village_code)[i]
  g <- get(paste0('sn_vil_graph_',match(v, village_names)))
  sg <- igraph::subgraph(g, match(intersect(unique(master_key_fw[subset_samples_fw |> filter(village == str_pad(v, 3, pad = 0)) |> pull(sample_id),'respondent_master_id']), V(g)$name), V(g)$name))
  
  sharing_rate |> 
    select(ego, alter, pair, tie, timepoint, n1) |>
    filter(ego %in% V(sg)$name & alter %in% V(sg)$name) |>
    pivot_wider(names_from = timepoint, values_from = n1) -> wide_ssr

    wide_ssr |>
    group_by(tie) |> summarize(median(T1), median(T2), mean(T1), mean(T2))
    
    ratio_plot <- wide_ssr |>
    #pivot_longer(cols = c(T1,T2), names_to = 'timepoint', values_to = 'ssr') |>
    mutate(delta_ssr = abs(T2-T1),
           tie = factor(wide_ssr$tie, labels = c('No','Yes'))) |>
    ggplot() + 
    geom_boxplot(aes(tie, delta_ssr, fill=tie)) + 
    coord_flip() +
    cowplot::theme_cowplot() + 
    xlab('Is tie present?') + ylab(bquote('Δ Strain-sharing' ~ rate[T])) +
    ylim(c(0,0.5)) + 
    guides(fill='none') +
    scale_fill_manual(values = c('white', '#027fffff'))

    wide_ssr |>
    filter(tie == 'yes') |>
    mutate(c = T1 > median(T1, na.rm = TRUE)) |> 
    graph_from_data_frame(directed=FALSE) -> sg_t1
  
    wide_ssr |>
    filter(tie == 'yes') |>
    mutate(c = T2 > median(T1, na.rm = TRUE)) |>
    graph_from_data_frame(directed=FALSE) -> sg_t2
  
  pred_colors <- edge_attr(sg_t1, "c")
  E(sg_t1)$size <- 2
  pred_colors[pred_colors == TRUE] <- "#027fffff"
  pred_colors[pred_colors == FALSE] <- "grey"  
  E(sg_t1)$color <- pred_colors

  pred_colors <- edge_attr(sg_t2, "c")
  E(sg_t2)$size <- 2
  pred_colors[pred_colors == TRUE] <- "#027fffff"
  pred_colors[pred_colors == FALSE] <- "grey"  
  E(sg_t2)$color <- pred_colors

  # par(mar=c(0,0,0,0)+.1)
  set.seed(1993)
  layout <- layout.fruchterman.reingold(sg_t1)
  v_t1 <- as.ggplot(expression(par(mar=c(0,0,0,0)+.1),plot(sg_t1,
       vertex.label = NA,
       vertex.size = 3,
       layout = layout,
       edge.width = E(sg_t1)$size,
       main = paste('T1', village_map[village_map$village_code == v,'village_name_deid', TRUE]))
      ))
  v_t2 <- as.ggplot(expression(par(mar=c(0,0,0,0)+.1), plot(sg_t2,
       vertex.label = NA,
       vertex.size = 3,
       layout = layout,
       edge.width = E(sg_t2)$size, 
       main = paste('T2', village_map[village_map$village_code == v,'village_name_deid', TRUE])),
  legend("topleft",
         legend=c(">median", "<median"),
         col=c("#027fffff", "grey"),
         lty = c(1,1),
         lwd = 2,
         bty = "n")))
  ggarrange(v_t1, v_t2, ratio_plot, nrow =3, heights = c(1,1,0.35))
} -> plots_t1t2
```

```{r}
png('/tmp/RtmpDF3hA7/vscode-R/plot1.png', width = 1500, height = 1100)
ggarrange(plotlist = plots_t1t2, nrow = 1)
dev.off()
```

```{r}
svglite(filename = 'Figures/timepoint_ssr_difference1.svg', width = 17, height = 10, bg='transparent', pointsize = 10, fix_text_size = FALSE)
ggarrange(plotlist = plots_t1t2, nrow = 1)
dev.off()
```


# Stability w1 w3
```{r overall_stability_across_waves}
pruned_SN_w3_graph <- subgraph(SN_w3_graph, intersect(names(V(SN_w3_graph)),names(V(SN_w1_graph))))
pruned_SN_w1_graph <- subgraph(SN_w1_graph, intersect(names(V(SN_w3_graph)),names(V(SN_w1_graph))))
```

```{r pervillage_stability_across_waves}
foreach(village = unique(reduced_SN_w1$village_code_w1), .combine = rbind) %do% {
  tmp_w3 <- subgraph(pruned_SN_w3_graph, subset(V(pruned_SN_w3_graph), V(pruned_SN_w3_graph)$village_code_w3 == village))
  tmp_w1 <- subgraph(pruned_SN_w1_graph, subset(V(pruned_SN_w1_graph), V(pruned_SN_w1_graph)$village_code_w1 == village))
  data.frame(village_code = as.character(village), stability=length(E(tmp_w3 %s% tmp_w1)) / length(E(tmp_w3 %u% tmp_w1)))
} |> bind_rows(data.frame(village_code = 'overall', stability=length(E(pruned_SN_w3_graph %s% pruned_SN_w1_graph)) / length(E(pruned_SN_w3_graph %u% pruned_SN_w1_graph))))
```

# New egdes in W3
```{r}
new_edges <- igraph::difference(pruned_SN_w3_graph, pruned_SN_w1_graph)
new_edges_attr_df <- data.frame(edge.attributes(new_edges))
nrow(lost_edges_attr_df)
```
# Egdes lost in W3
```{r}
lost_edges <- igraph::difference(pruned_SN_w1_graph, pruned_SN_w3_graph)
lost_edges_attr_df <- data.frame(edge.attributes(lost_edges))
nrow(lost_edges_attr_df)
```

# Number of ties retained
```{r eval=FALSE, include=FALSE}
w1w3_intersection <-  graph.intersection(pruned_SN_w1_graph, pruned_SN_w3_graph, byname = TRUE)
length(E(w1w3_intersection))
```


## Types of new relationships now disclosed in w3
```{r eval=FALSE, include=FALSE}
foreach(e = edge_attr(w1w3_intersection)$pair_1, .combine = c) %do% {
  setdiff(
    reduced_SN_w3 |> filter(pair == e ) |> pull(relationship) |> str_split(pattern = ',', simplify = TRUE) |> c(), 
    reduced_SN_w1 |> filter(pair == e ) |> pull(relationship) |> str_split(pattern = ',', simplify = TRUE) |> c()
  )
} |> table()

```

## Types of relationships not disclosed anymore in w3
```{r eval=FALSE, include=FALSE}
foreach(e = edge_attr(w1w3_intersection)$pair_1, .combine = c) %do% {
  setdiff(
    reduced_SN_w1 |> filter(pair == e ) |> pull(relationship) |> str_split(pattern = ',', simplify = TRUE) |> c(), 
    reduced_SN_w3 |> filter(pair == e ) |> pull(relationship) |> str_split(pattern = ',', simplify = TRUE) |> c()
  )
} |> table()

```
