---
title: "Network Comparison"
author: "Francesco Beghini"
date: "2023-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreach)
```

```{r}
strain_rate_vil_graph_1
sn_vil_graph_1
resample_graph <- function(g){
  return(rewire(g, keeping_degseq(niter = ecount(g)*10)))
}

asd = boot::boot(strain_rate_vil_graph_1, R=1000, parallel = 'multicore', statistic = function(x, ...){
  tmp = rewire(x, keeping_degseq(loops = FALSE, niter = ecount(x)*10))
  centralization.betweenness(tmp)$centralization
  })
asd1 = boot::boot(sn_vil_graph_1, R=1000, parallel = 'multicore', statistic = function(x, ...){
  tmp = rewire(x, keeping_degseq(loops = FALSE, niter = ecount(x)*10))
  centralization.betweenness(tmp)$centralization
  })

sdiff <- asd$t - asd1$t
diff_ci <- quantile(sdiff, probs = c(0.025, .975))
```

```{r}

foreach(i=1:length(village_names), .combine = 'rbind') %do% {
  sn_g <- get(paste0('sn_vil_graph_',i))
  st_g <- get(paste0('strain_rate_vil_graph_',i))
  sn_adj <- as_adjacency_matrix(sn_g, sparse = FALSE)
  sn_adj <- sn_adj[sort(rownames(sn_adj)),sort(colnames(sn_adj))]
  st_adj <- as_adjacency_matrix(st_g, sparse = FALSE)
  st_adj <- st_adj[sort(rownames(st_adj)),sort(colnames(st_adj))]

  all_nodes <- sort(V(sn_g)$name)

  edg_sn <- data.frame(as_edgelist(sn_g))
  edg_st <- data.frame(as_edgelist(simplify(st_g)))
  colnames(edg_sn) <- c('src','dst')
  colnames(edg_st) <- c('src','dst')
  edg_sn$src <- match(edg_sn$src, all_nodes)
  edg_sn$dst <- match(edg_sn$dst, all_nodes)
  edg_st$src <- match(edg_st$src, all_nodes)
  edg_st$dst <- match(edg_st$dst, all_nodes)
  degree_distribution_sn <- degree(sn_g)
  degree_distribution_st <- degree(st_g)
  data.frame(
       "Village name" = village_map[village_map$village_code==village_names[i],'village_name_deid'][[1]],
       "Clustering coefficient social network" = transitivity(sn_g, type = "global", isolates = 'zero'),
       "Clustering coefficient strain sharing network" = transitivity(st_g, type = "global", isolates = 'zero'),
       "Degree social network Min" = min(degree_distribution_sn),
       "Degree social network Max" = max(degree_distribution_sn),
       "Degree social network Median" = median(degree_distribution_sn),
       "Degree social network Mean" = mean(degree_distribution_sn),
       "Degree strain sharing network Min" = min(degree_distribution_st),
       "Degree strain sharing network Max" = max(degree_distribution_st),
       "Degree strain sharing network Median" = median(degree_distribution_st),
       "Degree strain sharing network Mean" = mean(degree_distribution_st),
       'Fraction of shared edges' = length(E(intersection(st_g, sn_g))) / length(E(union(st_g, sn_g)))
  )
} -> graph_distances

graph_distances
```
```{r}
writexl::write_xlsx(graph_distances, 'tables/graph_distances.xlsx')
```
```{r}
par(mfrow=c(3,2))
for (i in 1:length(village_names)) {
  igraph::plot.igraph(get(paste0('strain_rate_vil_graph_',i)),
                      vertex.label = NA,
                      vertex.size = 5,
                      #layout = layout.fruchterman.reingold(get(paste0('strain_rate_vil_graph_',i))),
                      edge.width = E(get(paste0('strain_rate_vil_graph_',i)))$width,
                      main = paste( village_map[village_map$village_code==village_names[i],'village_name_deid'][[1]], village_names[i])
                      )
}
```