---
title: "Species_Sharing_by_Degree"
author: "Jackson Pullman"
date: "2023-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Make species sharing network
```{r}
#Make species sharing networks

for(i in 1:length(village_names)){
  graph <- get(paste0("bray_vil_graph_", i))
  test_g <- make_full_graph(length(V(graph)))
  test_g <- set.vertex.attribute(test_g,
                                 "name",
                                 value = names(V(graph)))
  E(test_g)$weight <- 0
  test_g <- set.edge.attribute(test_g,
                               "weight",
                               index = as_ids(E(test_g)[na.omit(match(as_ids(E(graph)), as_ids(E(test_g))))]),
                               value = E(graph)$weight)
  assign(paste0("bray_vil_graph_", i), test_g)
}

for(i in 1:length(village_names)){
  graph <- get(paste0("jaccard_vil_graph_", i))
  test_g <- make_full_graph(length(V(graph)))
  test_g <- set.vertex.attribute(test_g,
                                 "name",
                                 value = names(V(graph)))
  E(test_g)$weight <- 0
  test_g <- set.edge.attribute(test_g,
                               "weight",
                               index = as_ids(E(test_g)[na.omit(match(as_ids(E(graph)), as_ids(E(test_g))))]),
                               value = E(graph)$weight)
  assign(paste0("jaccard_vil_graph_", i), test_g)
}
```



Bray

```{r}
#Get connected graphs for each village

for(i in 1:length(village_names)){
  #Create second degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_2"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),2)), get(paste0("sn_vil_graph_all_",i))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_2"), get(paste0("sn_vil_graph_all_", i,"_dg_2")))
  
  #Create third degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_3"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),3)),
                    simplify(connect(get(paste0("sn_vil_graph_all_",i)),2))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_3"), get(paste0("sn_vil_graph_all_", i,"_dg_3")))
  
  #Create fourth degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_4"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),4)),
                    simplify(connect(get(paste0("sn_vil_graph_all_",i)),3))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_4"), get(paste0("sn_vil_graph_all_", i,"_dg_4")))
  
  #Filter just to nodes in our strain sharing set
  assign(paste0("sn_vil_graph_all_",i),
         delete_vertices(get(paste0("sn_vil_graph_all_",i)),
                        V(get(paste0("sn_vil_graph_all_",i)))$name[!(V(get(paste0("sn_vil_graph_all_",i)))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 2
  assign(paste0("sn_vil_graph_all_",i,"_dg_2"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_2")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_2")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_2")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 3
  assign(paste0("sn_vil_graph_all_",i,"_dg_3"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_3")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_3")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_3")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 4
  assign(paste0("sn_vil_graph_all_",i,"_dg_4"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_4")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_4")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_4")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  
  #Rename graphs for convenience
  assign(paste0("sn_vil_graph_", i,"_dg_2"),
          get(paste0("sn_vil_graph_all_", i,"_dg_2")))
  
  assign(paste0("sn_vil_graph_", i,"_dg_3"),
          get(paste0("sn_vil_graph_all_", i,"_dg_3")))
  
  assign(paste0("sn_vil_graph_", i,"_dg_4"),
          get(paste0("sn_vil_graph_all_", i,"_dg_4")))
  
  assign(paste0("sn_vil_graph_", i),
          get(paste0("sn_vil_graph_all_", i)))
  
  
}

observed_weights_1 <-
  median(
    c(
      E(intersection(bray_vil_graph_1, sn_vil_graph_1))$weight,
      E(intersection(bray_vil_graph_2, sn_vil_graph_2))$weight,
      E(intersection(bray_vil_graph_3, sn_vil_graph_3))$weight,
      E(intersection(bray_vil_graph_4, sn_vil_graph_4))$weight,
      E(intersection(bray_vil_graph_5, sn_vil_graph_5))$weight,
      E(intersection(bray_vil_graph_6, sn_vil_graph_6))$weight,
      E(intersection(bray_vil_graph_7, sn_vil_graph_7))$weight,
      E(intersection(bray_vil_graph_8, sn_vil_graph_8))$weight,
      E(intersection(bray_vil_graph_9, sn_vil_graph_9))$weight,
      E(intersection(bray_vil_graph_10, sn_vil_graph_10))$weight,
      E(intersection(bray_vil_graph_11, sn_vil_graph_11))$weight,
      E(intersection(bray_vil_graph_12, sn_vil_graph_12))$weight,
      E(intersection(bray_vil_graph_13, sn_vil_graph_13))$weight,
      E(intersection(bray_vil_graph_14, sn_vil_graph_14))$weight,
      E(intersection(bray_vil_graph_15, sn_vil_graph_15))$weight,
      E(intersection(bray_vil_graph_16, sn_vil_graph_16))$weight,
      E(intersection(bray_vil_graph_17, sn_vil_graph_17))$weight,
      E(intersection(bray_vil_graph_18, sn_vil_graph_18))$weight
    ), na.rm = TRUE
  )


observed_weights_2 <- median(
  c(E(intersection(bray_vil_graph_1,sn_vil_graph_1_dg_2))$weight,
                             E(intersection(bray_vil_graph_2,sn_vil_graph_2_dg_2))$weight,
                             E(intersection(bray_vil_graph_3,sn_vil_graph_3_dg_2))$weight,
                             E(intersection(bray_vil_graph_4,sn_vil_graph_4_dg_2))$weight,
                             E(intersection(bray_vil_graph_5,sn_vil_graph_5_dg_2))$weight,
                             E(intersection(bray_vil_graph_6,sn_vil_graph_6_dg_2))$weight,
                             E(intersection(bray_vil_graph_7,sn_vil_graph_7_dg_2))$weight,
                             E(intersection(bray_vil_graph_8,sn_vil_graph_8_dg_2))$weight,
                             E(intersection(bray_vil_graph_9,sn_vil_graph_9_dg_2))$weight,
    E(intersection(bray_vil_graph_10,sn_vil_graph_10_dg_2))$weight,
                             E(intersection(bray_vil_graph_11,sn_vil_graph_11_dg_2))$weight,
                             E(intersection(bray_vil_graph_12,sn_vil_graph_12_dg_2))$weight,
                             E(intersection(bray_vil_graph_13,sn_vil_graph_13_dg_2))$weight,
                             E(intersection(bray_vil_graph_14,sn_vil_graph_14_dg_2))$weight,
                             E(intersection(bray_vil_graph_15,sn_vil_graph_15_dg_2))$weight,
                             E(intersection(bray_vil_graph_16,sn_vil_graph_16_dg_2))$weight,
                             E(intersection(bray_vil_graph_17,sn_vil_graph_17_dg_2))$weight,
                             E(intersection(bray_vil_graph_18,sn_vil_graph_18_dg_2))$weight),
                             na.rm = TRUE
  )


observed_weights_3 <- median(c(E(intersection(bray_vil_graph_1,sn_vil_graph_1_dg_3))$weight,
                             E(intersection(bray_vil_graph_2,sn_vil_graph_2_dg_3))$weight,
                             E(intersection(bray_vil_graph_3,sn_vil_graph_3_dg_3))$weight,
                             E(intersection(bray_vil_graph_4,sn_vil_graph_4_dg_3))$weight,
                             E(intersection(bray_vil_graph_5,sn_vil_graph_5_dg_3))$weight,
                             E(intersection(bray_vil_graph_6,sn_vil_graph_6_dg_3))$weight,
                             E(intersection(bray_vil_graph_7,sn_vil_graph_7_dg_3))$weight,
                             E(intersection(bray_vil_graph_8,sn_vil_graph_8_dg_3))$weight,
                             E(intersection(bray_vil_graph_9,sn_vil_graph_9_dg_3))$weight,
                             E(intersection(bray_vil_graph_10,sn_vil_graph_10_dg_3))$weight,
                             E(intersection(bray_vil_graph_11,sn_vil_graph_11_dg_3))$weight,
                             E(intersection(bray_vil_graph_12,sn_vil_graph_12_dg_3))$weight,
                             E(intersection(bray_vil_graph_13,sn_vil_graph_13_dg_3))$weight,
                             E(intersection(bray_vil_graph_14,sn_vil_graph_14_dg_3))$weight,
                             E(intersection(bray_vil_graph_15,sn_vil_graph_15_dg_3))$weight,
                             E(intersection(bray_vil_graph_16,sn_vil_graph_16_dg_3))$weight,
                             E(intersection(bray_vil_graph_17,sn_vil_graph_17_dg_3))$weight,
                             E(intersection(bray_vil_graph_18,sn_vil_graph_18_dg_3))$weight),
                             na.rm = TRUE)


observed_weights_4 <- median(c(E(intersection(bray_vil_graph_1,sn_vil_graph_1_dg_4))$weight,
                             E(intersection(bray_vil_graph_2,sn_vil_graph_2_dg_4))$weight,
                             E(intersection(bray_vil_graph_3,sn_vil_graph_3_dg_4))$weight,
                             E(intersection(bray_vil_graph_4,sn_vil_graph_4_dg_4))$weight,
                             E(intersection(bray_vil_graph_5,sn_vil_graph_5_dg_4))$weight,
                             E(intersection(bray_vil_graph_6,sn_vil_graph_6_dg_4))$weight,
                             E(intersection(bray_vil_graph_7,sn_vil_graph_7_dg_4))$weight,
                             E(intersection(bray_vil_graph_8,sn_vil_graph_8_dg_4))$weight,
                             E(intersection(bray_vil_graph_9,sn_vil_graph_9_dg_4))$weight,
                             E(intersection(bray_vil_graph_10,sn_vil_graph_10_dg_4))$weight,
                             E(intersection(bray_vil_graph_11,sn_vil_graph_11_dg_4))$weight,
                             E(intersection(bray_vil_graph_12,sn_vil_graph_12_dg_4))$weight,
                             E(intersection(bray_vil_graph_13,sn_vil_graph_13_dg_4))$weight,
                             E(intersection(bray_vil_graph_14,sn_vil_graph_14_dg_4))$weight,
                             E(intersection(bray_vil_graph_15,sn_vil_graph_15_dg_4))$weight,
                             E(intersection(bray_vil_graph_16,sn_vil_graph_16_dg_4))$weight,
                             E(intersection(bray_vil_graph_17,sn_vil_graph_17_dg_4))$weight,
                             E(intersection(bray_vil_graph_18,sn_vil_graph_18_dg_4))$weight),
                             na.rm = TRUE)


for(i in 1:length(village_names)){
  assign(paste0("bray_vil_graph_scram_", i), get(paste0("bray_vil_graph_", i)))
}
```


```{r}
#Strain Sharing Rate Test
perm_null_weights_1 <- rep(NA, 1000)
perm_null_weights_2 <- rep(NA, 1000)
perm_null_weights_3 <- rep(NA, 1000)
perm_null_weights_4 <- rep(NA, 1000)

for(i in 1:1000){
  bray_vil_graph_scram_1 <- set.vertex.attribute(bray_vil_graph_scram_1, "name",
                                       value = sample(vertex_attr(bray_vil_graph_scram_1, "name")))
  bray_vil_graph_scram_2 <- set.vertex.attribute(bray_vil_graph_scram_2, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_2, "name")))
  bray_vil_graph_scram_3 <- set.vertex.attribute(bray_vil_graph_scram_3, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_3, "name")))
  bray_vil_graph_scram_4 <- set.vertex.attribute(bray_vil_graph_scram_4, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_4, "name")))
  bray_vil_graph_scram_5 <- set.vertex.attribute(bray_vil_graph_scram_5, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_5, "name")))
  bray_vil_graph_scram_6 <- set.vertex.attribute(bray_vil_graph_scram_6, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_6, "name")))
  bray_vil_graph_scram_7 <- set.vertex.attribute(bray_vil_graph_scram_7, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_7, "name")))
  bray_vil_graph_scram_8 <- set.vertex.attribute(bray_vil_graph_scram_8, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_8, "name")))
  bray_vil_graph_scram_9 <- set.vertex.attribute(bray_vil_graph_scram_9, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_9, "name")))
  bray_vil_graph_scram_10 <- set.vertex.attribute(bray_vil_graph_scram_10, "name",
                                       value = sample(vertex_attr(bray_vil_graph_scram_10, "name")))
  bray_vil_graph_scram_11 <- set.vertex.attribute(bray_vil_graph_scram_11, "name",
                                       value = sample(vertex_attr(bray_vil_graph_scram_11, "name")))
  bray_vil_graph_scram_12 <- set.vertex.attribute(bray_vil_graph_scram_12, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_12, "name")))
  bray_vil_graph_scram_13 <- set.vertex.attribute(bray_vil_graph_scram_13, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_13, "name")))
  bray_vil_graph_scram_14 <- set.vertex.attribute(bray_vil_graph_scram_14, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_14, "name")))
  bray_vil_graph_scram_15 <- set.vertex.attribute(bray_vil_graph_scram_15, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_15, "name")))
  bray_vil_graph_scram_16 <- set.vertex.attribute(bray_vil_graph_scram_16, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_16, "name")))
  bray_vil_graph_scram_17 <- set.vertex.attribute(bray_vil_graph_scram_17, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_17, "name")))
  bray_vil_graph_scram_18 <- set.vertex.attribute(bray_vil_graph_scram_18, "name",
                                                  value = sample(vertex_attr(bray_vil_graph_scram_18, "name")))

  
  perm_null_weights_1[i] <- median(c(E(intersection(bray_vil_graph_scram_1,sn_vil_graph_1))$weight,
                      E(intersection(bray_vil_graph_scram_2,sn_vil_graph_2))$weight,
                      E(intersection(bray_vil_graph_scram_3,sn_vil_graph_3))$weight,
                      E(intersection(bray_vil_graph_scram_4,sn_vil_graph_4))$weight,
                      E(intersection(bray_vil_graph_scram_5,sn_vil_graph_5))$weight,
                      E(intersection(bray_vil_graph_scram_6,sn_vil_graph_6))$weight,
                      E(intersection(bray_vil_graph_scram_7,sn_vil_graph_7))$weight,
                      E(intersection(bray_vil_graph_scram_8,sn_vil_graph_8))$weight,
                      E(intersection(bray_vil_graph_scram_9,sn_vil_graph_9))$weight,
                      E(intersection(bray_vil_graph_scram_10,sn_vil_graph_10))$weight,
                      E(intersection(bray_vil_graph_scram_11,sn_vil_graph_11))$weight,
                      E(intersection(bray_vil_graph_scram_12,sn_vil_graph_12))$weight,
                      E(intersection(bray_vil_graph_scram_13,sn_vil_graph_13))$weight,
                      E(intersection(bray_vil_graph_scram_14,sn_vil_graph_14))$weight,
                      E(intersection(bray_vil_graph_scram_15,sn_vil_graph_15))$weight,
                      E(intersection(bray_vil_graph_scram_16,sn_vil_graph_16))$weight,
                      E(intersection(bray_vil_graph_scram_17,sn_vil_graph_17))$weight,
                      E(intersection(bray_vil_graph_scram_18,sn_vil_graph_18))$weight),
                             na.rm = TRUE)
  
  
  perm_null_weights_2[i] <- median(c(E(intersection(bray_vil_graph_scram_1,sn_vil_graph_1_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_2,sn_vil_graph_2_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_3,sn_vil_graph_3_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_4,sn_vil_graph_4_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_5,sn_vil_graph_5_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_6,sn_vil_graph_6_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_7,sn_vil_graph_7_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_8,sn_vil_graph_8_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_9,sn_vil_graph_9_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_10,sn_vil_graph_10_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_11,sn_vil_graph_11_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_12,sn_vil_graph_12_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_13,sn_vil_graph_13_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_14,sn_vil_graph_14_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_15,sn_vil_graph_15_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_16,sn_vil_graph_16_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_17,sn_vil_graph_17_dg_2))$weight,
                      E(intersection(bray_vil_graph_scram_18,sn_vil_graph_18_dg_2))$weight),
                             na.rm = TRUE)


  
  perm_null_weights_3[i] <- median(c(E(intersection(bray_vil_graph_scram_1,sn_vil_graph_1_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_2,sn_vil_graph_2_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_3,sn_vil_graph_3_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_4,sn_vil_graph_4_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_5,sn_vil_graph_5_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_6,sn_vil_graph_6_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_7,sn_vil_graph_7_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_8,sn_vil_graph_8_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_9,sn_vil_graph_9_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_10,sn_vil_graph_10_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_11,sn_vil_graph_11_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_12,sn_vil_graph_12_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_13,sn_vil_graph_13_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_14,sn_vil_graph_14_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_15,sn_vil_graph_15_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_16,sn_vil_graph_16_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_17,sn_vil_graph_17_dg_3))$weight,
                      E(intersection(bray_vil_graph_scram_18,sn_vil_graph_18_dg_3))$weight),
                             na.rm = TRUE)
  

  
  perm_null_weights_4[i] <- median(c(E(intersection(bray_vil_graph_scram_1,sn_vil_graph_1_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_2,sn_vil_graph_2_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_3,sn_vil_graph_3_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_4,sn_vil_graph_4_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_5,sn_vil_graph_5_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_6,sn_vil_graph_6_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_7,sn_vil_graph_7_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_8,sn_vil_graph_8_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_9,sn_vil_graph_9_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_10,sn_vil_graph_10_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_11,sn_vil_graph_11_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_12,sn_vil_graph_12_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_13,sn_vil_graph_13_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_14,sn_vil_graph_14_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_15,sn_vil_graph_15_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_16,sn_vil_graph_16_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_17,sn_vil_graph_17_dg_4))$weight,
                      E(intersection(bray_vil_graph_scram_18,sn_vil_graph_18_dg_4))$weight),
                             na.rm = TRUE)
  

  #Check progress
  if(i%%100 == 0){
    print(i)
  }

}

sum(perm_null_weights_1 >= observed_weights_1)/1000
sum(perm_null_weights_2 >= observed_weights_2)/1000
sum(perm_null_weights_3 >= observed_weights_3)/1000
sum(perm_null_weights_4 >= observed_weights_4)/1000


deg_df <- data.frame(Model = rep(c("Bray Network", "Null Network"), each = 4),
                     Degree = c(1,2,3,4, 1,2,3,4),
                     Precision = c(observed_weights_1, observed_weights_2, observed_weights_3, observed_weights_4,
                                   mean(perm_null_weights_1), mean(perm_null_weights_2), mean(perm_null_weights_3), mean(perm_null_weights_4)),
                     SD = c(0,0,0,0,sd(perm_null_weights_1), sd(perm_null_weights_2), sd(perm_null_weights_3), sd(perm_null_weights_4)))


#Damn doesn't change, wrird the 4th degree has gone down more, I noow have mroe 4th degree from the bigger networks

deg_df$Model[deg_df$Model == "Bray Network"] <- "Bray-Curtis Network"
#deg_df$Model[deg_df$Model == "Strain Network"] <- "Species-Sharing Network"
deg_df$Model <- factor(deg_df$Model)
deg_df$Model <- factor(deg_df$Model, levels = rev(levels(deg_df$Model)))

bray_by_degree_plot <- ggplot(deg_df, aes(x=Degree, y=Precision, group=Model, color = Model)) +
  geom_line(aes(color=Model, linetype = Model))+
  geom_pointrange(aes(ymin=Precision-SD, ymax=Precision+SD))+
  scale_linetype_manual(values=c("solid", "dashed")) + 
  scale_color_manual(values = c("#2E9FDF", "#FC4E07"))+
  #ggtitle("Average Strain-Sharing Rate By Geodesic Distance") +
  ylab("Median Bray-Curtis SImilarity") + 
  xlab("Geodesic Distance") +
  theme_pubr() +
  theme(legend.position = c(0.75, 0.75),
        plot.title = element_text(hjust = .5),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12)) + 
  labs_pubr()

#Damn it's true
SN %>% distinct(pair_key, .keep_all = TRUE) %>% pull(bray_curtis_sim) %>% median(na.rm= TRUE)
bray_by_degree_plot
```






Jaccard

```{r}
#Get connected graphs for each village

for(i in 1:length(village_names)){
  #Create second degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_2"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),2)), get(paste0("sn_vil_graph_all_",i))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_2"), get(paste0("sn_vil_graph_all_", i,"_dg_2")))
  
  #Create third degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_3"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),3)),
                    simplify(connect(get(paste0("sn_vil_graph_all_",i)),2))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_3"), get(paste0("sn_vil_graph_all_", i,"_dg_3")))
  
  #Create fourth degree
  assign(paste0("sn_vil_graph_all_", i,"_dg_4"),
         difference(simplify(connect(get(paste0("sn_vil_graph_all_",i)),4)),
                    simplify(connect(get(paste0("sn_vil_graph_all_",i)),3))))
  
  #assign(paste0("sn_vil_graph_scram_all_", i,"_dg_4"), get(paste0("sn_vil_graph_all_", i,"_dg_4")))
  
  #Filter just to nodes in our strain sharing set
  assign(paste0("sn_vil_graph_all_",i),
         delete_vertices(get(paste0("sn_vil_graph_all_",i)),
                        V(get(paste0("sn_vil_graph_all_",i)))$name[!(V(get(paste0("sn_vil_graph_all_",i)))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 2
  assign(paste0("sn_vil_graph_all_",i,"_dg_2"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_2")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_2")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_2")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 3
  assign(paste0("sn_vil_graph_all_",i,"_dg_3"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_3")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_3")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_3")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  #Degree 4
  assign(paste0("sn_vil_graph_all_",i,"_dg_4"),
         delete_vertices(get(paste0("sn_vil_graph_all_",i,"_dg_4")),
                        V(get(paste0("sn_vil_graph_all_",i,"_dg_4")))$name[!(V(get(paste0("sn_vil_graph_all_",i,"_dg_4")))$name %in%
                                                                       V(get(paste0("sn_vil_graph_",i)))$name)]))
  
  #Rename graphs for convenience
  assign(paste0("sn_vil_graph_", i,"_dg_2"),
          get(paste0("sn_vil_graph_all_", i,"_dg_2")))
  
  assign(paste0("sn_vil_graph_", i,"_dg_3"),
          get(paste0("sn_vil_graph_all_", i,"_dg_3")))
  
  assign(paste0("sn_vil_graph_", i,"_dg_4"),
          get(paste0("sn_vil_graph_all_", i,"_dg_4")))
  
  assign(paste0("sn_vil_graph_", i),
          get(paste0("sn_vil_graph_all_", i)))
  
  
}




observed_weights_1 <-
  median(
    c(
      E(intersection(jaccard_vil_graph_1, sn_vil_graph_1))$weight,
      E(intersection(jaccard_vil_graph_2, sn_vil_graph_2))$weight,
      E(intersection(jaccard_vil_graph_3, sn_vil_graph_3))$weight,
      E(intersection(jaccard_vil_graph_4, sn_vil_graph_4))$weight,
      E(intersection(jaccard_vil_graph_5, sn_vil_graph_5))$weight,
      E(intersection(jaccard_vil_graph_6, sn_vil_graph_6))$weight,
      E(intersection(jaccard_vil_graph_7, sn_vil_graph_7))$weight,
      E(intersection(jaccard_vil_graph_8, sn_vil_graph_8))$weight,
      E(intersection(jaccard_vil_graph_9, sn_vil_graph_9))$weight,
      E(intersection(jaccard_vil_graph_10, sn_vil_graph_10))$weight,
      E(intersection(jaccard_vil_graph_11, sn_vil_graph_11))$weight,
      E(intersection(jaccard_vil_graph_12, sn_vil_graph_12))$weight,
      E(intersection(jaccard_vil_graph_13, sn_vil_graph_13))$weight,
      E(intersection(jaccard_vil_graph_14, sn_vil_graph_14))$weight,
      E(intersection(jaccard_vil_graph_15, sn_vil_graph_15))$weight,
      E(intersection(jaccard_vil_graph_16, sn_vil_graph_16))$weight,
      E(intersection(jaccard_vil_graph_17, sn_vil_graph_17))$weight,
      E(intersection(jaccard_vil_graph_18, sn_vil_graph_18))$weight
    ), na.rm = TRUE
  )


observed_weights_2 <- median(
  c(E(intersection(jaccard_vil_graph_1,sn_vil_graph_1_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_2,sn_vil_graph_2_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_3,sn_vil_graph_3_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_4,sn_vil_graph_4_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_5,sn_vil_graph_5_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_6,sn_vil_graph_6_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_7,sn_vil_graph_7_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_8,sn_vil_graph_8_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_9,sn_vil_graph_9_dg_2))$weight,
    E(intersection(jaccard_vil_graph_10,sn_vil_graph_10_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_11,sn_vil_graph_11_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_12,sn_vil_graph_12_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_13,sn_vil_graph_13_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_14,sn_vil_graph_14_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_15,sn_vil_graph_15_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_16,sn_vil_graph_16_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_17,sn_vil_graph_17_dg_2))$weight,
                             E(intersection(jaccard_vil_graph_18,sn_vil_graph_18_dg_2))$weight),
                             na.rm = TRUE
  )


observed_weights_3 <- median(c(E(intersection(jaccard_vil_graph_1,sn_vil_graph_1_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_2,sn_vil_graph_2_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_3,sn_vil_graph_3_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_4,sn_vil_graph_4_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_5,sn_vil_graph_5_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_6,sn_vil_graph_6_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_7,sn_vil_graph_7_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_8,sn_vil_graph_8_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_9,sn_vil_graph_9_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_10,sn_vil_graph_10_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_11,sn_vil_graph_11_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_12,sn_vil_graph_12_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_13,sn_vil_graph_13_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_14,sn_vil_graph_14_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_15,sn_vil_graph_15_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_16,sn_vil_graph_16_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_17,sn_vil_graph_17_dg_3))$weight,
                             E(intersection(jaccard_vil_graph_18,sn_vil_graph_18_dg_3))$weight),
                             na.rm = TRUE)


observed_weights_4 <- median(c(E(intersection(jaccard_vil_graph_1,sn_vil_graph_1_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_2,sn_vil_graph_2_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_3,sn_vil_graph_3_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_4,sn_vil_graph_4_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_5,sn_vil_graph_5_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_6,sn_vil_graph_6_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_7,sn_vil_graph_7_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_8,sn_vil_graph_8_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_9,sn_vil_graph_9_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_10,sn_vil_graph_10_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_11,sn_vil_graph_11_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_12,sn_vil_graph_12_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_13,sn_vil_graph_13_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_14,sn_vil_graph_14_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_15,sn_vil_graph_15_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_16,sn_vil_graph_16_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_17,sn_vil_graph_17_dg_4))$weight,
                             E(intersection(jaccard_vil_graph_18,sn_vil_graph_18_dg_4))$weight),
                             na.rm = TRUE)


for(i in 1:length(village_names)){
  assign(paste0("jaccard_vil_graph_scram_", i), get(paste0("bray_vil_graph_", i)))
}
```


```{r}
#Strain Sharing Rate Test
perm_null_weights_1 <- rep(NA, 1000)
perm_null_weights_2 <- rep(NA, 1000)
perm_null_weights_3 <- rep(NA, 1000)
perm_null_weights_4 <- rep(NA, 1000)

for(i in 1:1000){
  jaccard_vil_graph_scram_1 <- set.vertex.attribute(jaccard_vil_graph_scram_1, "name",
                                       value = sample(vertex_attr(jaccard_vil_graph_scram_1, "name")))
  jaccard_vil_graph_scram_2 <- set.vertex.attribute(jaccard_vil_graph_scram_2, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_2, "name")))
  jaccard_vil_graph_scram_3 <- set.vertex.attribute(jaccard_vil_graph_scram_3, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_3, "name")))
  jaccard_vil_graph_scram_4 <- set.vertex.attribute(jaccard_vil_graph_scram_4, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_4, "name")))
  jaccard_vil_graph_scram_5 <- set.vertex.attribute(jaccard_vil_graph_scram_5, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_5, "name")))
  jaccard_vil_graph_scram_6 <- set.vertex.attribute(jaccard_vil_graph_scram_6, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_6, "name")))
  jaccard_vil_graph_scram_7 <- set.vertex.attribute(jaccard_vil_graph_scram_7, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_7, "name")))
  jaccard_vil_graph_scram_8 <- set.vertex.attribute(jaccard_vil_graph_scram_8, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_8, "name")))
  jaccard_vil_graph_scram_9 <- set.vertex.attribute(jaccard_vil_graph_scram_9, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_9, "name")))
  jaccard_vil_graph_scram_10 <- set.vertex.attribute(jaccard_vil_graph_scram_10, "name",
                                       value = sample(vertex_attr(jaccard_vil_graph_scram_10, "name")))
  jaccard_vil_graph_scram_11 <- set.vertex.attribute(jaccard_vil_graph_scram_11, "name",
                                       value = sample(vertex_attr(jaccard_vil_graph_scram_11, "name")))
  jaccard_vil_graph_scram_12 <- set.vertex.attribute(jaccard_vil_graph_scram_12, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_12, "name")))
  jaccard_vil_graph_scram_13 <- set.vertex.attribute(jaccard_vil_graph_scram_13, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_13, "name")))
  jaccard_vil_graph_scram_14 <- set.vertex.attribute(jaccard_vil_graph_scram_14, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_14, "name")))
  jaccard_vil_graph_scram_15 <- set.vertex.attribute(jaccard_vil_graph_scram_15, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_15, "name")))
  jaccard_vil_graph_scram_16 <- set.vertex.attribute(jaccard_vil_graph_scram_16, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_16, "name")))
  jaccard_vil_graph_scram_17 <- set.vertex.attribute(jaccard_vil_graph_scram_17, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_17, "name")))
  jaccard_vil_graph_scram_18 <- set.vertex.attribute(jaccard_vil_graph_scram_18, "name",
                                                  value = sample(vertex_attr(jaccard_vil_graph_scram_18, "name")))

  
  perm_null_weights_1[i] <- median(c(E(intersection(jaccard_vil_graph_scram_1,sn_vil_graph_1))$weight,
                      E(intersection(jaccard_vil_graph_scram_2,sn_vil_graph_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_3,sn_vil_graph_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_4,sn_vil_graph_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_5,sn_vil_graph_5))$weight,
                      E(intersection(jaccard_vil_graph_scram_6,sn_vil_graph_6))$weight,
                      E(intersection(jaccard_vil_graph_scram_7,sn_vil_graph_7))$weight,
                      E(intersection(jaccard_vil_graph_scram_8,sn_vil_graph_8))$weight,
                      E(intersection(jaccard_vil_graph_scram_9,sn_vil_graph_9))$weight,
                      E(intersection(jaccard_vil_graph_scram_10,sn_vil_graph_10))$weight,
                      E(intersection(jaccard_vil_graph_scram_11,sn_vil_graph_11))$weight,
                      E(intersection(jaccard_vil_graph_scram_12,sn_vil_graph_12))$weight,
                      E(intersection(jaccard_vil_graph_scram_13,sn_vil_graph_13))$weight,
                      E(intersection(jaccard_vil_graph_scram_14,sn_vil_graph_14))$weight,
                      E(intersection(jaccard_vil_graph_scram_15,sn_vil_graph_15))$weight,
                      E(intersection(jaccard_vil_graph_scram_16,sn_vil_graph_16))$weight,
                      E(intersection(jaccard_vil_graph_scram_17,sn_vil_graph_17))$weight,
                      E(intersection(jaccard_vil_graph_scram_18,sn_vil_graph_18))$weight),
                             na.rm = TRUE)
  
  
  perm_null_weights_2[i] <- median(c(E(intersection(jaccard_vil_graph_scram_1,sn_vil_graph_1_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_2,sn_vil_graph_2_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_3,sn_vil_graph_3_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_4,sn_vil_graph_4_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_5,sn_vil_graph_5_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_6,sn_vil_graph_6_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_7,sn_vil_graph_7_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_8,sn_vil_graph_8_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_9,sn_vil_graph_9_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_10,sn_vil_graph_10_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_11,sn_vil_graph_11_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_12,sn_vil_graph_12_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_13,sn_vil_graph_13_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_14,sn_vil_graph_14_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_15,sn_vil_graph_15_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_16,sn_vil_graph_16_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_17,sn_vil_graph_17_dg_2))$weight,
                      E(intersection(jaccard_vil_graph_scram_18,sn_vil_graph_18_dg_2))$weight),
                             na.rm = TRUE)


  
  perm_null_weights_3[i] <- median(c(E(intersection(jaccard_vil_graph_scram_1,sn_vil_graph_1_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_2,sn_vil_graph_2_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_3,sn_vil_graph_3_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_4,sn_vil_graph_4_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_5,sn_vil_graph_5_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_6,sn_vil_graph_6_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_7,sn_vil_graph_7_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_8,sn_vil_graph_8_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_9,sn_vil_graph_9_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_10,sn_vil_graph_10_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_11,sn_vil_graph_11_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_12,sn_vil_graph_12_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_13,sn_vil_graph_13_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_14,sn_vil_graph_14_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_15,sn_vil_graph_15_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_16,sn_vil_graph_16_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_17,sn_vil_graph_17_dg_3))$weight,
                      E(intersection(jaccard_vil_graph_scram_18,sn_vil_graph_18_dg_3))$weight),
                             na.rm = TRUE)
  

  
  perm_null_weights_4[i] <- median(c(E(intersection(jaccard_vil_graph_scram_1,sn_vil_graph_1_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_2,sn_vil_graph_2_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_3,sn_vil_graph_3_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_4,sn_vil_graph_4_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_5,sn_vil_graph_5_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_6,sn_vil_graph_6_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_7,sn_vil_graph_7_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_8,sn_vil_graph_8_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_9,sn_vil_graph_9_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_10,sn_vil_graph_10_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_11,sn_vil_graph_11_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_12,sn_vil_graph_12_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_13,sn_vil_graph_13_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_14,sn_vil_graph_14_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_15,sn_vil_graph_15_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_16,sn_vil_graph_16_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_17,sn_vil_graph_17_dg_4))$weight,
                      E(intersection(jaccard_vil_graph_scram_18,sn_vil_graph_18_dg_4))$weight),
                             na.rm = TRUE)
  

  #Check progress
  if(i%%100 == 0){
    print(i)
  }

}
sum(perm_null_weights_1 >= observed_weights_1)/1000
sum(perm_null_weights_2 >= observed_weights_2)/1000
sum(perm_null_weights_3 >= observed_weights_3)/1000
sum(perm_null_weights_4 >= observed_weights_4)/1000

deg_df <- data.frame(Model = rep(c("Jaccard Network", "Null Network"), each = 4),
                     Degree = c(1,2,3,4, 1,2,3,4),
                     Precision = c(observed_weights_1, observed_weights_2, observed_weights_3, observed_weights_4,
                                   mean(perm_null_weights_1), mean(perm_null_weights_2), mean(perm_null_weights_3), mean(perm_null_weights_4)),
                     SD = c(0,0,0,0,sd(perm_null_weights_1), sd(perm_null_weights_2), sd(perm_null_weights_3), sd(perm_null_weights_4)))


#Damn doesn't change, wrird the 4th degree has gone down more, I noow have mroe 4th degree from the bigger networks

deg_df$Model[deg_df$Model == "Jaccard Network"] <- "Jaccard Index Network"
#deg_df$Model[deg_df$Model == "Strain Network"] <- "Species-Sharing Network"
deg_df$Model <- factor(deg_df$Model)
deg_df$Model <- factor(deg_df$Model, levels = rev(levels(deg_df$Model)))

jaccard_by_degree_plot <- ggplot(deg_df, aes(x=Degree, y=Precision, group=Model, color = Model)) +
  geom_line(aes(color=Model, linetype = Model))+
  geom_pointrange(aes(ymin=Precision-SD, ymax=Precision+SD))+
  scale_linetype_manual(values=c("solid", "dashed")) + 
  scale_color_manual(values = c("#2E9FDF", "#FC4E07"))+
  #ggtitle("Average Strain-Sharing Rate By Geodesic Distance") +
  ylab("Median Jaccard Index") + 
  xlab("Geodesic Distance") +
  theme_pubr() +
  theme(legend.position = c(0.75, 0.75),
        plot.title = element_text(hjust = .5),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12)) + 
  labs_pubr()

#Damn it's true
SN %>% distinct(pair_key, .keep_all = TRUE) %>% pull(jaccard_sim) %>% median(na.rm= TRUE)
jaccard_by_degree_plot
```


Make Figures
```{r}
svglite("../FiguresNew/SFigure10/sfigure10_full.svg")
ggarrange(bray_by_degree_plot, jaccard_by_degree_plot, nrow = 1, labels = c("A", "B"))
dev.off()
```


