---
title: "Strain-sharing prediction"
author: 
    - "Francesco Beghini, Jackson Pullman, Marcus Alexander, Shivkumar Vishnempet Shridhar,"
    - "Drew Prinster, Adarsh Singh, Rigoberto Matute Juárez,"
    - "Edoardo M. Airoldi, Ilana L. Brito, Nicholas A. Christakis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Downsamp_all <- readRDS('Downsamp_all.Rds')
Downsamp_all_nkh <- readRDS('Downsamp_all_nkh.Rds')
```

# Calculate R^2 for all relationships
```{r, echo=FALSE}
llm_all_kin_for2 <- lmerTest::lmer(strain_sharing_rate ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education + household_same +
                        related + (1|village_code_w3),
                              data = Downsamp_all)
summary(llm_all_kin_for2)
```
```{r}
r2glmm::r2beta(llm_all_kin_for2, method = 'nsj')
```
\newpage
# Calculate R^2 for non-kin relationships
```{r, echo=FALSE}
llm_non_kin_for2 <- lmerTest::lmer(strain_sharing_rate ~ gender.mm + gender.mf + indigenous.both +
                        indigenous.one + religion.same + age_difference_abs +
                        average_diet + different_diet + average_bristol + different_bristol + watersource_same + 
                        same_usage_painkillers + same_usage_antibiotics + same_usage_antidiarrheal + same_usage_antiparasite + same_usage_vitamins + same_usage_zinc + same_usage_antifungal + same_usage_antihypertensives + same_usage_antidiabetics + same_usage_antiacids + same_usage_laxatives +
                        average_age + wealth_difference_abs + average_wealth +
                        education_difference_abs + average_education + household_same + related + (1|village_code_w3),
                              data = Downsamp_all_nkh)
summary(llm_non_kin_for2)
```

```{r}
r2glmm::r2beta(llm_non_kin_for2, method = 'nsj')
```
